- integration_tests/common.luxinc
- integration_tests/migrations/bidirectional.lux
- integration_tests/migrations/simple_test.lux
- integration_tests/multi_dc/sysbench_tests.lux
- integration_tests/single_dc/sysbench_tests.lux
- lib/electric/postgres/postgres_manager.ex
- lib/electric/replication/postgres/logical_replication_producer.ex
- lib/electric/replication/postgres/tcp_server.ex
Work in progress, add simple e2e test with multiple PG instances operating on different schema versions.
> E2E migration test with different versions used

- Makefile
- compose-mounts.yaml
- compose.yaml
- integration_tests/single_dc/bidirectional_multiple_electric.lux
- lib/electric/postgres/postgres_manager.ex
- lib/electric/replication/postgres/client.ex
- test/electric/to_vaxine_test.exs
Move with_conn to pg client, catch exit message if trap_exit in set to true
> Move with_conn to pg client

- README.md
- config/config.exs
- config/dev.exs
- config/runtime.exs
- config/test.exs
- integration_tests/common.mk
- integration_tests/migrations/shared.luxinc
- integration_tests/multi_dc/Makefile
- integration_tests/multi_dc/electric.template
- integration_tests/multi_dc/shared.luxinc
- integration_tests/single_dc/electric.exs
- integration_tests/single_dc/electric_b.exs
- integration_tests/single_dc/shared.luxinc
- integration_tests/single_dc/sysbench_ws.lux
- lib/electric.ex
- lib/electric/satellite/auth/jwt.ex
- lib/electric/satellite/satellite_auth.ex
- lib/electric/satellite/satellite_protocol.ex
- lib/electric/satellite_ws_server.ex
- lib/mix/tasks/electric.gen.token.ex
- test/electric/satellite/satellite_ws_test.exs
- test/electric_test.exs
- test/mix/tasks/electric.gen.token_test.exs
https://linear.app/vaxine/issue/VAX-395/electric-auth-configuration-is-not-in-sync-with-console
> Update auth configuration to match provisioning

- Dockerfile
- Makefile
- integration_tests/Makefile
- integration_tests/common.luxinc
- integration_tests/common.mk
- integration_tests/elixir_client/.gitignore
- integration_tests/elixir_client/Makefile
- integration_tests/satellite_client/.gitignore
- integration_tests/services_templates.yaml
* Fix deps caching in electric docker image
* Fix dependencies reuse between local filesystem and docker for elixir test_client
> chore: Fix elixir test_client dependencies.

- .github/workflows/clients_typescript_tests.yml
- .github/workflows/components_electric_tests.yml
- .github/workflows/e2e.yml
Learn more about the `concurrency` option here -
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency.
> ci: Cancel duplicate CI workflow runs when new changes are pushed

- README.md
Only a minor pass pending a proper refresh and some better content. Basically added some badges and videos and a pass on the description etc.
Ideally this should have some component diagrammes and summary code but let's hold that until the v2. It looks like this: https://github.com/electric-sql/electric/tree/thruflo/readme-pass
> Quick pass on the README.

- clients/typescript/src/migrators/triggers.ts
> Fix text column

- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/shapes/cache.ts
- clients/typescript/src/satellite/shapes/index.ts
- clients/typescript/src/satellite/shapes/manager.ts
- clients/typescript/src/satellite/shapes/types.ts
- clients/typescript/src/util/proto.ts
- clients/typescript/src/util/types.ts
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/satellite/server_ws_stub.ts
* handle FK constraints in gc/applying txn
* send unsubscribe messages on error
* map proto errors to sat errors
> feat(satellite): improvements to the subscription proto

- clients/typescript/src/_generated/protocol/satellite.ts
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/shapes/cache.ts
- clients/typescript/src/satellite/shapes/index.ts
- clients/typescript/src/satellite/shapes/manager.ts
- clients/typescript/src/satellite/shapes/types.ts
- clients/typescript/src/util/proto.ts
- clients/typescript/src/util/types.ts
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/satellite/server_ws_stub.ts
- components/electric/lib/electric/satellite/protobuf_messages.ex
- protocol/satellite.proto
- Distinguish between subscribe request errors and subscription data errors
- Client-side generated subscription ids
- (Piggy-back) load subscriptions manager state from storage
> feat(satellite) improve subscribe request

- clients/typescript/src/satellite/shapes/manager.ts
Minor simplification that removes an unnecessary if test that was always truthy.
> chore(Satellite): remove obsolete if test

- .changeset/grumpy-buses-hammer.md
- components/electric/lib/electric/postgres/extension/migrations/20230605141256_electrify_function/electrify.sql
- components/electric/test/electric/postgres/extension/electrify_test.exs
- components/electric/test/electric/replication/electrification_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
> fix(electric): Make it so that trying to electrify an electrified table fails

- clients/typescript/src/auth/util.ts
- clients/typescript/test/satellite/common.ts
Context: https://discord.com/channels/933657521581858818/1079688869852753981/1136612631218765904
> fixt(client): Correctly subtract 1 second instead of 1000 in the JWT "iat" claim

- pnpm-lock.yaml
> chore(client): update lock file

- .changeset/tall-moles-speak.md
Adds the changeset for PR #312 for which we forgot to generate a changeset.
> fix(client): Changeset for a prior modification of the ts-client

- docs/reference/literature.md
> docs: literature page copy tweak.

- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/test/electric/replication/postgres/logical_replication_producer_test.exs
> chore(electric): Explicitly set those configuration parameters that affect formatting of values of certain types

- .changeset/neat-laws-wonder.md
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/util/common.ts
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/lib/satellite/protocol_helpers.ex
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/satellite/serialization_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- e2e/satellite_client/src/client.ts
- e2e/tests/03.13_node_satellite_can_sync_timestamps.lux
- e2e/tests/_satellite_macros.luxinc
> feat(electric, satellite): Add support for timestamp and timestamptz column types

- .changeset/six-items-grow.md
- components/electric/lib/electric/postgres/dialect/sqlite.ex
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/plug_test.exs
- components/electric/test/electric/postgres/dialect/sqlite_test.exs
- components/electric/test/electric/postgres/extension/electrify_test.exs
- components/electric/test/electric/postgres/extension/schema_cache_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/satellite/serialization_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- components/electric/test/support/postgres_test_connection.ex
- e2e/init.sql
- e2e/tests/02.02_migrations_get_streamed_to_satellite.lux
- e2e/tests/03.05_fresh_node_satellite_receives_all_migrations_during_initial_sync.lux
- e2e/tests/04.01_electric_api_returns_migrations.lux
- e2e/tests/_shared.luxinc
> feat(electric, satellite): Add support for UUID data type in electrified tables

- .changeset/forty-actors-sin.md
- clients/typescript/src/satellite/client.ts
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/satellite/serialization_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- e2e/tests/03.14_node_satellite_can_sync_dates.lux
> feat(electric): Add support for DATE data type in electrified tables

- .changeset/brown-pots-brake.md
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/util/common.ts
- clients/typescript/test/satellite/serialization.test.ts
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/satellite/serialization_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- e2e/tests/03.15_node_satellite_can_sync_booleans.lux
> feat(electric): Add support for BOOLEAN data type in electrified tables

- examples/starter/package.json
Forgot to bump the version of the starter.
> chore (starter): bump version

- .changeset/quiet-garlics-compare.md
- clients/typescript/src/client/execution/db.ts
- clients/typescript/src/client/execution/nonTransactionalDB.ts
- clients/typescript/src/client/execution/transactionalDB.ts
- clients/typescript/src/squel.d.ts
Changes to the query builder of the DAL to use squel's support for parametrized queries.
> fix (DAL): parametrized squel queries

- .changeset/light-stingrays-listen.md
- components/electric/lib/electric/replication/postgres_connector.ex
- components/electric/lib/electric/replication/postgres_manager.ex
> fix(electric): Monitor PostgresConnectorSup and restart it whenever Postgres is up

- docs/quickstart/_setup_generator.md
- examples/starter/README.md
Most of the work moved to #VAX-1057
> Change docs to use create-electric-app@latest

- docs/intro/real-world.md
> chore(docs): No motion graphics explainer for now

- docs/integrations/backend/phoenix.md
Similar idea as electric - listen to the WAL and do things directly in Elixir
> Add WalEx to phoenix.md

- .changeset/thirty-lemons-smile.md
Forgot to add one in https://github.com/electric-sql/electric/pull/520.
> chore: Add a changelog entry for the new migrations mgmt in examples/starter

- docs/integrations/backend/adonis.md
Adding [Adonis JS](https://github.com/adonisjs)  integration under backends.
A Framework by [Harminder Virk](https://github.com/thetutlage)
> New Backend Integration for Adonis JS

- .changeset/bright-kiwis-laugh.md
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/migrations/20231009121515_allow_large_migrations.ex
- components/electric/lib/electric/postgres/extension/migrations/20231010123118_add_priority_to_version.ex
- components/electric/test/electric/postgres/extension/ddl_capture_test.exs
- e2e/tests/04.03_prisma_migration_version_captured.lux
> fix(electric): Handle large migration bodies

- docs/integrations/drivers/mobile/expo.md
- docs/integrations/drivers/mobile/react-native.md
- docs/integrations/drivers/server/node.md
- docs/integrations/drivers/web/wa-sqlite.md
Corrected a typo in the documentation.
> Fixed spelling in documentation

- docs/usage/installation/service.md
- examples/beer-stars/backend/compose.yaml
- examples/expo/backend/compose/docker-compose.yaml
- examples/linearlite/backend/compose/docker-compose.yaml
- examples/react-native/backend/compose/docker-compose.yaml
- examples/starter/template/backend/compose/docker-compose.yaml
- examples/web-wa-sqlite/backend/compose/docker-compose.yaml
- local-stack/Makefile
- local-stack/docker-compose.yaml
This removes the bits that were missed in 79dbc84 and de1c571.
> chore: Remove yet more remnants of offset storage

- components/electric/lib/electric/postgres/proxy/injector.ex
This is a follow-up to https://github.com/electric-sql/electric/pull/587#discussion_r1368945549.
> chore(electric): Rewrite the splitting algorithm in Proxy.Injector to be more concise

- examples/expo/backend/compose/.envrc
- examples/expo/package.json
- examples/expo/src/styles.tsx
- examples/expo/yarn.lock
Fixes the version of expo-sqlite that is used and the height that is allocated to the items display.
> fix (examples): fixes for expo example app

- .buildkite/docker-image.yml
> chore(release): Loosen the tag regex a little more

- examples/starter/src/index.ts
JS deps were easy to change.
As for the Docker image, in order to find available tags, we have to reach out to Docker Hub's API. That was a bit over my pay-grade in terms of implementing that quickly in TypeScript as part of the starter. I've added a command-line flag that allows passing the image tag, as demonstration.
Now, we can actually fetch the list of tags from Docker Hub API without authentication and then pick the one that has the same digest as `latest` and whose name matches the `x.y` version format. Here's what I mean:
```
$ curl https://hub.docker.com/v2/namespaces/electricsql/repositories/electric/tags >electric-tags.txt
$ cat electric-tags.txt | jq '.results[]
| select(.name == "latest")
| {name: .name, digest: .digest}'
{
"name": "latest",
"digest": …
```
> chore(starter): Update version pinning behaviour in the starter template

- .changeset/gentle-guests-knock.md
- clients/typescript/test/migrators/builder.test.ts
This PR fixes some assertions that were wrongly being used.
> chore (client): fix assertions in unit tests

- README.md
- examples/expo/backend/compose/.envrc
- examples/ionic-demo/backend/compose/.envrc
- examples/linearlite/backend/compose/.envrc
- examples/react-native/backend/compose/.envrc
- examples/starter/template/backend/compose/dot_envrc
- examples/web-wa-sqlite/backend/compose/.envrc
> chore(electric): Remove leftover mentions of the local stack

- .changeset/ten-cups-know.md
Adds the changeset that was missing from PR https://github.com/electric-sql/electric/pull/687
> chore (client): add changeset for Windows fix

- docs/reference/alternatives.md
> Add CASE to alternatives (Other local-first projects)

- docs/usage/data-modelling/types.md
Key thing in this release is support for more types, plus some bug fixes.
> chore(docs): Update docs for v0.8

- docs/usage/data-modelling/types.md
This link just threw me for a *huge* loop when I thought it meant I'd have to abandon Electric after spending awhile setting it up, since it references a significantly outdated version of this file. Not sure if this is how you want to handle it though, or just moving up the commit pointer.
Thanks for the great work, excited to try it out!
> Update Types doc to reference main branch

- docs/integrations/deployment/_fly.md
- docs/integrations/deployment/fly.md
- docs/usage/installation/postgres.md
Preview -- https://deploy-preview-78--electric-sql-website.netlify.app/docs/integrations/deployment/fly
> chore(docs): Add a simplified guide for Fly deployment

- docs/examples/checkout.md
- docs/integrations/deployment/supabase.md
- docs/integrations/event-sourcing/supabase.md
Tweak docs to align with new Secure Transactions post. And split out the Supabase event sourcing info to a page in the event sourcing section.
> docs: add supabase event sourcing page.

- components/electric/lib/electric/postgres/proxy/handler.ex
- components/electric/lib/electric/postgres/proxy/handler/tracing.ex
- components/electric/lib/electric/postgres/proxy/injector.ex
- components/electric/lib/electric/postgres/proxy/injector/electric.ex
- components/electric/lib/electric/postgres/proxy/injector/operation.ex
- components/electric/lib/electric/postgres/proxy/injector/prisma.ex
- components/electric/lib/electric/postgres/proxy/injector/shadow.ex
- components/electric/lib/electric/postgres/proxy/injector/transparent.ex
- components/electric/lib/electric/postgres/proxy/parser.ex
- components/electric/lib/electric/postgres/proxy/upstream_connection.ex
- components/electric/test/electric/postgres/proxy/injector/shadow_test.exs
- components/electric/test/electric/postgres/proxy/injector_test.exs
> fix(electric): Support Prisma shadow database in electric proxy

- .buildkite/docker-image.yml
This reverts commit ffcb8a94cd6d08f093ec81df03dabe3c0d6386aa.
> Revert "(tmp) Do not publish to Docker Hub from Buildkite. Only echo the versions (#775)"

- examples/node-sidecar/README.md
Add pre-reqs section to node-sidecar
> Update node-sidecar README.md

- examples/web-wa-sqlite/yarn.lock
> fix(example/web-wa-sqlite) Fix broken yarn lock file

- components/electric/lib/electric/postgres/dialect/sqlite.ex
- components/electric/lib/electric/postgres/extension/functions/electrify.sql.eex
- components/electric/lib/electric/postgres/extension/functions/generate_electrified_sql.sql.eex
- components/electric/lib/electric/postgres/extension/functions/validate_table_column_types.sql.eex
- components/electric/lib/electric/postgres/extension/schema_cache.ex
- components/electric/lib/electric/postgres/extension/schema_cache/global.ex
- components/electric/lib/electric/postgres/oid_database.ex
- components/electric/lib/electric/postgres/oid_database/pg_type.ex
- components/electric/lib/electric/postgres/schema.ex
- components/electric/lib/electric/postgres/schema/proto/messages.ex
- components/electric/lib/electric/postgres/schema/update.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/migration_consumer.ex
- components/electric/lib/electric/replication/postgres/tcp_server.ex
- components/electric/lib/electric/replication/postgres_manager.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/postgres/extension/ddl_capture_test.exs
- components/electric/test/electric/postgres/extension/schema_cache_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/postgres/table_test.exs
- components/electric/test/electric/replication/postgres/migration_consumer_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- e2e/satellite_client/src/client.ts
- e2e/satellite_client/src/generated/client/index.ts
- e2e/satellite_client/src/prisma/schema.prisma
- e2e/tests/03.20_node_satellite_can_sync_enums.lux
- e2e/tests/_satellite_macros.luxinc
- protocol/postgres_schema.proto
Closes VAX-1040, VAX-1041.
Supersedes https://github.com/electric-sql/electric/pull/564.
> feat(electric): Enable electrification of tables with columns of user-defined PG ENUM types

- components/electric/lib/electric/postgres/proxy/errors.ex
- components/electric/lib/electric/postgres/proxy/query_analyser.ex
Follow-up to https://github.com/electric-sql/electric/pull/819.
> chore(electric): Consistent Proxy error numbering and formatting

- docs/api/cli.md
- docs/deployment/digital-ocean.md
- docs/deployment/fly.md
- docs/examples/notes/running.md
- docs/integrations/drivers/mobile/react-native.md
- docs/integrations/drivers/server/node.md
- docs/integrations/drivers/web/wa-sqlite.md
- docs/quickstart/_modelling_generator.md
- docs/quickstart/_setup_generator.md
- docs/quickstart/_setup_manual.md
- docs/usage/installation/client.md
Preview: https://deploy-preview-94--electric-sql-website.netlify.app/docs/api/cli
> chore(docs) Docs for new CLI and Starter

- .changeset/strange-timers-trade.md
- components/electric/config/runtime.exs
- components/electric/lib/electric/config.ex
> chore(electric): Support sslmode query option in DATABASE_URL

- .changeset/wise-geckos-cough.md
- clients/typescript/package.json
- pnpm-lock.yaml
This seems to fix VAX-1524, but may need more testing with Prisma schemas.
> fix(client) Upgrade Prisma dep to 5.2 in the client, Fixes VAX-1524

- .changeset/khaki-adults-sip.md
- clients/typescript/src/cli/migrations/migrate.ts
Thanks to @davidmartos96 for suggestion.
> chore(client) Validate the the --with-migrations command successfully ran before generating client

- .changeset/quiet-rice-punch.md
- clients/typescript/src/cli/tunnel/command-proxy-tunnel.ts
> fix(cli): Map http(s) scheme in service URL to ws(s) when starting proxy-tunnel

- docs/api/_DATABASE_REQUIRE_SSL.md
- docs/api/_DATABASE_URL.md
Documentation update for https://github.com/electric-sql/electric/pull/848.
> chore(docs): Document the support for sslmode in DATABASE_URL

- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres_connector.ex
> chore(electric): Log an error when DATABASE_URL points to a connection pool

- .changeset/friendly-queens-teach.md
- components/electric/lib/electric/postgres/schema/update.ex
- components/electric/lib/electric/replication/postgres/migration_consumer.ex
- components/electric/test/electric/postgres/extension/ddl_capture_test.exs
- components/electric/test/electric/replication/postgres/migration_consumer_test.exs
> fix(electric): Deduplicate enum type definitions in the electrified schema

- .changeset/tender-falcons-speak.md
- components/electric/lib/electric/postgres/extension/schema_loader/epgsql.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres_manager.ex
- components/electric/test/support/postgres_test_connection.ex
> feat(electric): Enable SSL certificate validation for database connections

- .changeset/gorgeous-pans-repair.md
- components/electric/lib/electric/postgres/proxy/upstream_connection.ex
> fix(electric): Pass ssl_opts from the main connection options to Proxy.UpstreamConnection

- docs/deployment/fly.md
Preview: https://deploy-preview-101--electric-sql-website.netlify.app/docs/deployment/fly
> chore(docs): Update Fly deployment doc

- clients/typescript/test/cli/config-options.test.ts
Minor improvement to the new config options test. With this we can detect when a new option is added and it doesn't get added to the list.
> chore(cli): Improve CLI options test

- docs/api/_AUTH_JWT_KEY.md
- docs/api/service.md
Preview - https://deploy-preview-111--electric-sql-website.netlify.app/
> chore(docs): Document supported formats for AUTH_JWT_KEY

- docs/integrations/drivers/mobile/expo.md
Follow up to https://github.com/electric-sql/electric/pull/867.
> chore(docs): Update Expo driver docs to include expo-sqlite/next

- examples/web-wa-sqlite-vuejs/package-lock.json
- examples/web-wa-sqlite-vuejs/package.json
- examples/web-wa-sqlite-vuejs/src/ElectricProvider.vue
- examples/web-wa-sqlite-vuejs/src/auth.ts
- examples/web-wa-sqlite/package-lock.json
- examples/web-wa-sqlite/package.json
- examples/web-wa-sqlite/src/Example.tsx
- examples/web-wa-sqlite/src/auth.ts
Updates the example apps for react and vue to use the new auth APIs
> chore(starter): Update starter templates to use electric `0.9.3`

- docs/integrations/frontend/react.md
Was mentioned in this issue https://github.com/electric-sql/electric/issues/990
> chore(docs): Make `isMounted` a mutable variable in React docs

- docs/reference/architecture.md
> Fix a typo in architecture.md

- .changeset/four-lions-listen.md
Forgot to add a changeset for this fix https://github.com/electric-sql/electric/pull/1029
> chore(client): Add changeset for `upsert` fix

- .changeset/healthy-turkeys-smell.md
- clients/typescript/package.json
Fixes VAX-1723
Needed for LiveStore
> chore(client) Export websocket implementations to enable use in custom drivers

- .changeset/flat-flowers-drive.md
- clients/typescript/package.json
- clients/typescript/src/drivers/react-native-sqlite-storage/adapter.ts
- clients/typescript/src/drivers/react-native-sqlite-storage/database.ts
- clients/typescript/src/drivers/react-native-sqlite-storage/index.ts
- clients/typescript/src/drivers/react-native-sqlite-storage/mock.ts
- clients/typescript/test/drivers/react-native-sqlite-storage.test.ts
- clients/typescript/test/frameworks/react.test.tsx
- pnpm-lock.yaml
It was using wrong typings so the `dbName` was actually `dbname` and causing issues.
I've also refactored it to use the serial database adapter to simplify it.
> chore(client): Fix implementation of `react-native-sqlite-driver`

- docs/reference/release_notes.md
- docs/reference/roadmap.md
Preview - https://deploy-preview-112--electric-sql-website.netlify.app/docs/reference/release_notes
> chore(docs): Add a new Release notes page to document compatibility issues

- clients/typescript/package.json
- pnpm-lock.yaml
Fix for unreleased op-sqlite support added in #1047
Local builds complain about missing types.
> fix(client): Add op-sqlite to devDependencies

- .changeset/green-lemons-rescue.md
- clients/typescript/package.json
- clients/typescript/src/drivers/expo-sqlite-next/index.ts
- clients/typescript/src/drivers/expo-sqlite/index.ts
- clients/typescript/src/drivers/op-sqlite/index.ts
- clients/typescript/src/util/random.ts
- docs/integrations/drivers/mobile/_crypto_polyfill_warning.md
- docs/integrations/drivers/mobile/expo.md
- docs/integrations/drivers/mobile/react-native.md
- pnpm-lock.yaml
Follow up to https://github.com/electric-sql/electric/pull/1063
See website preview from https://github.com/electric-sql/website/pull/117:
[Expo preview](https://deploy-preview-117--electric-sql-website.netlify.app/docs/integrations/drivers/mobile/expo)
[React Native preview](https://deploy-preview-117--electric-sql-website.netlify.app/docs/integrations/drivers/mobile/react-native)
> chore(docs): Add warning about `react-native-get-random-values` polyfill to RN driver docs

- docs/integrations/frontend/vue.md
Follow up to https://github.com/electric-sql/electric/pull/1011
> chore(docs): Add documentation for `useConnectivityState` API for Vue.js bindings

- clients/typescript/src/notifiers/event.ts
Log the list of tables that were changed. Useful for debugging and during development.
> feat(client): Log the tables that were actually changed

- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
This was supposed to go into https://github.com/electric-sql/electric/pull/1099 but that got merged too soon.
> chore(electric): Add an explanation for magic writes in LogicalReplicationProducer

- docs/quickstart/_setup_generator.md
Followup to https://github.com/electric-sql/electric/pull/1142
> chore(docs): Mention all available create-electric-app templates

- examples/introduction/src/components/ConnectivityControl/index.tsx
- examples/introduction/src/components/ItemsWidget/index.tsx
- examples/introduction/src/components/PlayerWidget/index.tsx
- examples/introduction/src/components/SliderInput/index.tsx
- examples/introduction/src/demos/local-first/instant.jsx
- examples/introduction/src/demos/multi-user/realtime.jsx
- examples/introduction/src/demos/offline/connectivity.jsx
- examples/introduction/src/demos/offline/integrity.jsx
See website PR: https://github.com/electric-sql/website/pull/125
Adds e2e tests for the website widgets, having test ids makes it easier to make assertions.
> chore(website): Add test ids to demos for easier e2e testing

- docs/reference/release_notes.md
Preview: https://deploy-preview-123--electric-sql-website.netlify.app/docs/reference/release_notes#2024-10-14---v010.
> chore(docs): Add release notes for the v0.10 release

- docs/api/clients/typescript.md
Fixes a number of wrong field names in client docs.
> chore (docs): fix typos in client docs

- docs/api/_DATABASE_USE_IPV6.md
- docs/api/service.md
- docs/deployment/fly.md
- docs/deployment/supabase.md
Doc update for https://github.com/electric-sql/electric/pull/1210.
> chore(docs): Update the documentation of DATABASE_USE_IPv6

- .netlify/bin/build-with-proxy-tunnel.sh
- examples/linearlite/src/components/LeftMenu.tsx
- examples/linearlite/src/components/Modal.tsx
- examples/linearlite/src/components/contextmenu/PriorityMenu.tsx
Fix minor linearlite issues and update deploy script to make generic
> chore(examples): Update netlify deploy script to make generic

- docs/reference/release_notes.md
Preview: https://deploy-preview-129--electric-sql-website.netlify.app/docs/reference/release_notes#2024-05-02---v0102
> chore(docs): Update release notes

- .changeset/shy-tigers-repair.md
- examples/_testing/e2e/web/basic.spec.ts
- examples/expo/package-lock.json
- examples/expo/package.json
- examples/node-sidecar/apps/node/package-lock.json
- examples/node-sidecar/apps/node/package.json
- examples/node-sidecar/sidecar/package-lock.json
- examples/node-sidecar/sidecar/package.json
- examples/react-native/package-lock.json
- examples/react-native/package.json
- examples/recipes/package-lock.json
- examples/recipes/package.json
- examples/starter/package.json
- examples/tauri-sqlite/package-lock.json
- examples/tauri-sqlite/package.json
- examples/web-pglite/package-lock.json
- examples/web-pglite/package.json
- examples/web-wa-sqlite-vuejs/package-lock.json
- examples/web-wa-sqlite-vuejs/package.json
- examples/web-wa-sqlite/package-lock.json
- examples/web-wa-sqlite/package.json
- pnpm-lock.yaml
Update most examples to electric 0.12 and bump starter CLI to release version with the new templates
> chore(examples): Update examples to 0.12

- components/electric/README.md
I had a couple of issues when setting up the environment. This PR updates the README to make it clearer so that hopefully the next person to follow those instructions doesn't make the same mistakes I did.
> Update pre-reqs section in README

- docs/deployment/fly.md
Addresses the feedback and suggestion here: https://github.com/electric-sql/electric/issues/1344#issuecomment-2164696333
> docs: Add client app note to Fly doc page.

- packages/typescript-client/README.md
Was giving this a whirl today and noticed this small issue.
> Update README.md to use '@electric-sql/client'

- CONTRIBUTING.md
- docs/about.md
- docs/api/http.md
- docs/guides/telemetry.md
Hello
I found and fixed several spelling issues in your docs.
Br, Elias.
> Docs fix spelling issues

- docs/.vitepress/config.mts
- docs/guides/local-development.md
Several people have hit this so let's document the fix
> docs: Add guide for local-development that explains work-around for http/1.1 issues

- .changeset/olive-tools-report.md
Changeset for https://github.com/electric-sql/electric/pull/1606 - forgot to add one.
Follow links for actually relevant commit.
> chore: Add changeset for log chunking

- packages/react-hooks/README.md
Same fix as https://github.com/electric-sql/electric/pull/1612
> doc: fix React README code sample

- website/use-cases/local-first-software.md
> web: update local-first-software.md

- packages/sync-service/README.md
This addition helps users to understand better the sync service.
> docs: complete the TODO tag in sync-service README

- packages/sync-service/config/runtime.exs
This change makes it possible to start exporting traces to Honeycomb without the need to run a separate OpenTelemetry Collector.
> chore: Add shortcut OT export config for Honeycomb.io

- README.md
PR #1570 changed the location of the `electric-api.yaml` file. This PR adjusts sources to changes.
> docs: update `electric-api.yaml` reference

- .changeset/great-maps-fail.md
- packages/sync-service/lib/electric/shapes/dispatcher.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shapes/dispatcher_test.exs
> Don't crash when there are no active shapes

- website/docs/guides/deployment.md
Closes #1720.
Preview - https://deploy-preview-1727--electric-next.netlify.app/docs/guides/deployment
> doc: Deployment/DataPersistence guide

- examples/redis-sync/README.md
- examples/redis-sync/db/migrations/01-create_items_table.sql
I forgot to `git add` them in https://github.com/electric-sql/electric/pull/1793
> chore: Add forgotten files for redis-sync

- website/docs/reference/telemetry.md
This doc change is to be merged after https://github.com/electric-sql/electric/pull/1765 has been included in a published release.
> docs: Update the Telemetry page to match the new behaviour in the code

- website/about/jobs/pglite-engineer.md
https://deploy-preview-1819--electric-next.netlify.app/about/jobs/pglite-engineer
> jobs: clarify the basis and co-funding of PGlite role.

- .changeset/small-pears-hide.md
- .changeset/wet-nails-poke.md
- packages/react-hooks/test/react-hooks.test.tsx
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/src/shape.ts
- packages/typescript-client/test/cache.test.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/fetch.test.ts
- packages/typescript-client/test/integration.test.ts
Fix for https://github.com/electric-sql/electric/issues/1838
> Set a much longer max-age for -1 offsets and don't return 

- .changeset/honest-boxes-share.md
for https://github.com/electric-sql/electric/pull/1857/
> Add missing changeset

- .github/workflows/ts_test.yml
- integration-tests/tests/_macros.luxinc
- packages/react-hooks/test/react-hooks.test.tsx
- packages/react-hooks/test/support/global-setup.ts
- packages/react-hooks/test/support/test-context.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/support/global-setup.ts
- packages/typescript-client/test/support/test-context.ts
Fixes https://github.com/electric-sql/electric/issues/1875
Attempting to reduce flakiness - still getting some errors I can't quite pinpoint every now and then but seems like an improvement
> chore: Fix flaky TS tests

- .github/workflows/elixir_tests.yml
- .github/workflows/integration_tests.yml
- .github/workflows/ts_test.yml
Fixes https://github.com/electric-sql/electric/issues/1728
Ignores changes to the `website` folder as well as to any `README.md` file - should cover the basic cases.
> chore: Ignore doc changes

- .changeset/big-shoes-care.md
- .changeset/chatty-adults-heal.md
- .changeset/fuzzy-rats-drive.md
- integration-tests/scripts/electric_dev.sh
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/resuming-replication-at-consistent-point.lux
- packages/sync-service/.env.dev
- packages/sync-service/config/runtime.exs
- packages/sync-service/dev/docker-compose-otel.yml
- packages/sync-service/dev/otel-collector-honeycomb-config.yaml
- website/docs/guides/deployment.md
- website/docs/reference/telemetry.md
Fix https://github.com/electric-sql/electric/issues/1927
> chore: rename env variables so consitently prefixed with ELECTRIC_

- website/docs/api/clients/typescript.md
- website/electric-api.yaml
> Documentation for `replica` parameter

- packages/react-hooks/README.md
- website/docs/integrations/react.md
> docs: fix react import path.

- .github/workflows/elixir_client_tests.yml
- .github/workflows/elixir_tests.yml
- .github/workflows/integration_tests.yml
- .github/workflows/ts_test.yml
Update caching strategy for the elixir apps to speed up CI runs.
Also use a matrix for tests against different PG versions.
> chore: refactor elixir ci tests

- packages/sync-service/lib/electric/control_plane.ex
- packages/sync-service/lib/electric/tenant_manager.ex
One more followup to https://github.com/electric-sql/electric/pull/1967
> fix: Fix control plane bug

- website/about/contact.md
PR fixes the logo references found in https://electric-sql.com/about/contact.
> fix: update logo references

- .changeset/strange-spiders-provide.md
- packages/elixir-client/lib/electric/client.ex
- packages/elixir-client/lib/electric/client/fetch/request.ex
- packages/elixir-client/lib/electric/client/stream.ex
- packages/elixir-client/test/electric/client/fetch/request_test.exs
- packages/elixir-client/test/electric/client_test.exs
- packages/elixir-client/test/support/db_setup.ex
Plus fix use of old `update_mode` parameter.
> elixir-client: Add database id configuration

- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/dynamic_consumer_supervisor.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
For better visibility while using the observer:
> chore (sync-service): Set process labels

- website/docs/guides/shapes.md
https://deploy-preview-2148--electric-next.netlify.app/docs/guides/shapes#defining-shapes
> docs: add missing information about columns selection to shape guide

- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
> Set OTEL span status to error when an exception is recorded for it

- examples/linearlite/db/load_data.js
This allows for easier benchmarking of transaction processing in Electric.
> linearlite: make transaction batching configurable when loading seed data

- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/config_parser.ex
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/lib/electric/telemetry/call_home_reporter.ex
and tidy up telemetry config a little and make the call-home url configurable
> Add cpu and memory usage info

- .changeset/chilly-peaches-tease.md
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/test/electric/telemetry_test.exs
Fixes https://github.com/electric-sql/electric/issues/2200.
> fix: Guard system memory stat calculations against missing data points and division by zero

- website/docs/api/clients/typescript.md
saw this while reading docs, just wanted to submit a quick fix.
> fix missing import in docs

- .github/workflows/deploy_examples.yml
- examples/linearlite-read-only/src/pages/Issue/Comments.tsx
- examples/linearlite-read-only/src/shapes.ts
- examples/linearlite-read-only/sst.config.ts
- examples/linearlite/src/sync.ts
- examples/linearlite/sst.config.ts
- examples/nextjs/app/shape-proxy/route.ts
- examples/nextjs/sst.config.ts
- examples/proxy-auth/app/shape-proxy/route.ts
- examples/proxy-auth/sst.config.ts
- examples/todo-app/src/routes/index.tsx
- examples/todo-app/sst.config.ts
- examples/write-patterns/shared/app/config.ts
- examples/write-patterns/sst.config.ts
- examples/yjs/app/shape-proxy/[...table]/route.ts
- examples/yjs/sst.config.ts
- website/docs/api/clients/typescript.md
- website/electric-api.yaml
Also fix other problems with example deployments:
- new admin api endpoint
- nextjs example renamed
- add support for pooled connections
> Rename database_id to source_id in examples deployment

- website/.vitepress/config.mts
- website/product/cloud.md
- website/product/cloud/onboarding.md
- website/product/cloud/sign-up.md
https://deploy-preview-2236--electric-next.netlify.app/product/cloud/onboarding
> docs: cloud onboarding doc.

- .github/workflows/deploy_all_examples.yml
- .github/workflows/deploy_examples.yml
- examples/linearlite-read-only/sst.config.ts
- examples/linearlite/sst.config.ts
- examples/nextjs/sst.config.ts
- examples/proxy-auth/sst.config.ts
- examples/todo-app/sst.config.ts
- examples/write-patterns/sst.config.ts
- examples/yjs/.eslintignore
- examples/yjs/sst.config.ts
To run sst locally, you'll need to have a `marketing` credential setup in `~/.aws/credentials`
> Set aws profile to marketing & add workflow to deploy all examples on demand

- website/product/cloud/onboarding.md
https://deploy-preview-2266--electric-next.netlify.app/product/cloud/onboarding
> docs: update cloud onboarding docs.

- .changeset/modern-toes-drop.md
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/test/electric/shape_cache/file_storage_test.exs
> fix: invalid json while reading a concurrently written snapshot

- .changeset/wet-days-rush.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/test/electric/shape_cache_test.exs
> chore: ensure correct span connection for snapshot creation

- .changeset/eighty-masks-battle.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/schema.ex
- packages/sync-service/lib/electric/shapes/shape.ex
> fix: don't show column details if they weren't selected

- .changeset/sixty-queens-agree.md
- packages/sync-service/lib/electric/log_items.ex
- packages/sync-service/lib/electric/shape_cache/file_storage/log_file.ex
- packages/sync-service/test/electric/log_item_test.exs
- packages/sync-service/test/electric/shape_cache/file_storage/compaction_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
> feat: change `txid` header to be `txids` 

- .changeset/brown-poems-watch.md
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/plug/router_test.exs
as seen by a particular shape.
Closes #2286
> feat: mark `last` the last operation for a given transaction

- .changeset/fast-emus-grow.md
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
> feat: add info about the last-processed lsn to up-to-date message

- packages/sync-service/lib/electric/connection/manager.ex
The "passthrough" trick didn't work as planned since the error handling code has been moved around a bit after it got introduced.
To prevent a recursive call loop, we just need to replace the recursive call with different function call.
> Fix connection error handling

- packages/typescript-client/src/client.ts
- packages/typescript-client/src/constants.ts
- packages/typescript-client/test/client.test.ts
> feat(typescript-client): ShapeStream.forceDisconnectAndRefresh method

- examples/write-patterns/package.json
- pnpm-lock.yaml
This PR fixes the error in `examples/write-patterns`, the 4th patterns write through the DB sync.
Ref: https://discord.com/channels/933657521581858818/933657523049885698/1341336665528074351
> fix(examples): update pglite packages for `write-patterns`

- .changeset/warm-pets-arrive.md
- packages/sync-service/lib/electric/utils.ex
- quote postgres reserved words
- quote names that start with a number
> sync-service: improve relation_to_sql quoting logic

- website/.vitepress/config.mts
- website/.vitepress/theme/Layout.vue
- website/.vitepress/theme/custom.css
- website/.vitepress/theme/index.js
- website/blog/posts/2024-12-10-electric-beta-release.md
- website/docs/reference/benchmarks.md
- website/index.md
- website/product/cloud.md
- website/product/cloud/onboarding.md
- website/product/cloud/sign-up.md
- website/product/cloud/usage.md
- website/product/electric.md
- website/product/pglite.md
- website/src/components/NavSignupButton.vue
- website/src/components/SiteFooter.vue
https://deploy-preview-2383--electric-next.netlify.app
> website: promote cloud sign-up to primary CTA.

- packages/sync-service/lib/electric/application.ex
Fix for bug introduced [here](https://github.com/electric-sql/electric/commit/bd2d9974e945555534886f15862d3fb5cbfb74ae#diff-a5dbb59702303b89823106bc2b74d99eae176b5be8ba6bda5ffc1dc565289e33)
> Fix app telemetry

- .changeset/spicy-pugs-drive.md
- packages/sync-service/lib/electric/shapes/api/options.ex
> fix: allow `traceparent` headers

- .changeset/silent-parrots-smile.md
- packages/sync-service/lib/electric/shape_cache/file_storage/action_file.ex
- packages/sync-service/lib/electric/shape_cache/file_storage/key_index.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/utils_test.exs
> fix: improve file merging performance

- .changeset/hot-taxis-judge.md
I forgot to add a changeset to the secure mode PR https://github.com/electric-sql/electric/pull/2404.
> chore: changeset for secure mode

- website/electric-api.yaml
> docs: document `api_secret` query parameter (#2471)

- packages/sync-service/test/electric/plug/router_test.exs
Was triaging https://github.com/electric-sql/electric/issues/2469 and I added two integration tests:
1. Ensure most types get replicated correctly, both for the initial snapshot and subsequent log updates
2. Ensure large binaries (>1 MB) get replicated correctly as well
Both tests are passing but I think they are worth including in the test suite.
I think we need to change the title of the above issue as looking at it more closely the problem is that we return a body with a 204 response, which is against the spec (and is what the error is reporting as well).
> fix: Add tests for binary columns

- scripts/llms.js
- scripts/patch_api_spec_version.js
- website/docs/intro.md
- website/docs/llms/_intro_redux.md
- website/docs/llms/_quickstart_redux.md
- website/electric-api.yaml
- website/llms.txt.template
- website/package.json
https://deploy-preview-2481--electric-next.netlify.app/llms.txt
Without:
With:
Claude wrote the llms.js script. Basically pulling in the content from the docs, so it doesn't get out of date. With some horrible hacks to slim down and get the nesting and spacing right.
Don't judge me. I was just following the vibes.
> llms: build and expose `/llms.txt`.

- .changeset/shy-eagles-search.md
Fixes an error in the changeset
> chore: Update changeset from minor to patch bump

- integration-tests/tests/secure-mode.lux
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/test/electric/plug/router_test.exs
- website/electric-api.yaml
Fixes https://github.com/orgs/electric-sql/projects/13/views/1?pane=issue&itemId=104307653&issue=electric-sql%7Celectric%7C2475
Accompanying docs PR: https://github.com/electric-sql/electric/pull/2547
> chore: Rename api_secret query param to secret

- packages/sync-service/lib/electric/debug/process.ex
> Resolve races in Electric.Debug.Process

- website/docs/integrations/next.md
Small PR - Commit ade15b9526978f9dd3fba1e569d1cdebdd403d9c moved the nextjs example files. This PR adjusts sources to changes. Relevant page: https://electric-sql.com/docs/integrations/next
> docs: update nextjs example

- website/docs/quickstart.md
- update the curl command outputs for the latest
- use a "scores" table instead of a "foo" table — a user's feedback was it feels much more concrete to have a real-ish example (which I agree with)
> Freshen up the Quickstart

- packages/sync-service/lib/electric/plug/health_check_plug.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/status_monitor.ex
- packages/sync-service/test/electric/plug/health_check_plug_test.exs
- packages/sync-service/test/electric/status_monitor_test.exs
Following on from #2576 , this PR does a little bit of refactoring, mostly suggestions from @alco
> chore(sync-service): minor status monitor refactor

- packages/sync-service/lib/electric/plug/utils.ex
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
Fix https://github.com/electric-sql/electric/issues/2492
> Make explicit the headers that clients need to be able read

- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
- packages/sync-service/test/electric/shapes/consumer_test.exs
Follow-up to https://github.com/electric-sql/electric/pull/2617.
> Introduce a helper function for looking up the DB pool process by name

- examples/.shared/lib/database.ts
Closes https://github.com/electric-sql/electric/issues/2645
The optimal solution is to use a proper Pulumi provider which is in the works, but to avoid blocking on that I've used a Pulumi command like we've done for Neon.
It uses the output from the `create` command in the `delete` command in order to delete the source using the ID generated in the creation step.
I've added a 10s sleep after the delete to ensure the Neon database is not deleted until the Electric source is cleaned up - technically this should be solved on the cloud (if cleanup fails cause the database no longer exists we should consider the cleanup to be successful), but adding it here to ensure cleanups go smoothly.
Only concern is if delete fails with 404 because source has already been deleted it will currently not …
> fix: Create and delete Electric sources for examples

- .changeset/ninety-toes-talk.md
- integration-tests/tests/invalidated-replication-slot.lux
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/timeline.ex
> fix: ensure continued replication when WAL slot size is exceeded

- .changeset/giant-mails-punch.md
- examples/yjs/sst.config.ts
- packages/y-electric/README.md
prefix for the server domain is out of place
> Fix yjs demo deployment

- .changeset/loud-squids-watch.md
- integration-tests/scripts/electric_dev.sh
- integration-tests/test_utils/connection_manager_ping.exs
- integration-tests/tests/_macros.luxinc
- packages/sync-service/lib/electric/connection/manager.ex
> Implement a test helper that pings connection manager periodically

- README.md
Closes https://github.com/electric-sql/electric/issues/2719
> fix: Use correct commands for macOS setup

- .github/workflows/ts_test.yml
- examples/tanstack/sst.config.ts
- packages/experimental/package.json
- packages/experimental/vitest.config.ts
- packages/react-hooks/package.json
- packages/react-hooks/vitest.config.ts
- packages/typescript-client/package.json
- packages/typescript-client/vitest.config.ts
- packages/y-electric/package.json
- packages/y-electric/vitest.config.ts
- pnpm-lock.yaml
Removing bundle analysis plugin cause I realised we don't actually use Vite to build them 🙃
Also fixing the test command that we run to actually produce coverage.
> fix: Fix CodeCov upload action

- .github/workflows/elixir_client_tests.yml
Slowly but surely I'll manage to not forget something.
> fix: Actually run coverage tests for elixir client

- .changeset/large-windows-peel.md
- packages/sync-service/Dockerfile
- packages/sync-service/config/runtime.exs
> Fix the env var reading issue introduced when Elixir dependencies where upgraded

- website/docs/integrations/phoenix.md
We are way over half a century in to this programming thing; text editing and spell checkers will continue to be an unsolved problem next century too.
---
Thanks for all the awesome work, noticed this while reading through. The documentation you all have is fantastic. Looking forward to exploring integrating this.
> Fix libarary -> library typo

- .changeset/tidy-teachers-fetch.md
- packages/elixir-client/lib/electric/client/embedded.ex
- packages/elixir-client/test/electric/client/embedded_test.exs
> elixir-client: Fix consumption of client streams across processes

- .changeset/shiny-sloths-accept.md
- packages/elixir-client/lib/electric/client/ecto_adapter/postgres.ex
- packages/elixir-client/test/electric/client/ecto_adapter/postgres_test.exs
Fixes https://github.com/electric-sql/phoenix_sync/issues/57
> elixir-client: Add support for array params

- .changeset/fast-doors-rule.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/test/electric/postgres/lock_connection_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/test_utils.ex
> Catch pooled connection errors in Connection.Manager process

- packages/sync-service/test/electric/shape_cache_test.exs
Before this change, it was easy to see the test fail after just a handful of runs. The reason was that the simulated snapshotter process would be resumed before the test process had started waiting on the snapshot.
This change makes sure there's a process in the consumer's waiting list before resuming the simulated snapshotter, though it does make the test aware of implementation details.
This test has failed in two CI jobs spawned by the [commit in `main`](https://github.com/electric-sql/electric/commit/fbbcad415db1a719e2acef50e337641086d30609) that was supposed to publish a new version of Electric and other packages.
> Fix flaky ShapeCache test

- .changeset/curly-mirrors-speak.md
- packages/sync-service/lib/electric/postgres/logical_replication/decoder.ex
- packages/sync-service/test/electric/postgres/decoder_test.exs
> Fix decoding of TRUNCATE message options

- .changeset/brave-jars-speak.md
- packages/elixir-client/config/runtime.exs
- packages/elixir-client/mix.exs
- packages/elixir-client/test/support/db_setup.ex
Mirror PR: https://github.com/electric-sql/phoenix_sync/pull/23
> elixir-client: Stop explicitly obfuscating the DB password

- packages/sync-service/lib/electric/connection/manager.ex
Followup to https://github.com/electric-sql/electric/pull/2866
We brutally kill the lock connection because it can hang on connecting and be unable to be killed - the 5 second timeout is too long for the lock connection cleanup
> fix: Brutally kill the lock connection

- .changeset/kind-donuts-melt.md
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
> fix: make sure CPU telemetry reporting doesn't crash

- examples/tanstack-db-web-starter/README.md
just stumbled upon this, correct starter command should be 
npx gitpick electric-sql/electric/tree/main/examples/tanstack-db-web-starter my-tanstack-db-project
> fix starter command in readme.md

- .changeset/violet-wasps-agree.md
- packages/elixir-client/lib/electric/client.ex
- packages/elixir-client/lib/electric/client/ecto_adapter.ex
- packages/elixir-client/test/electric/client/ecto_adapter_test.exs
> elixir-client: Support specifying column subsets via Ecto.Query.select/3

- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/replication/log_offset.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/replication/shape_log_collector/flush_tracker.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/pure_file_storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/postgres/replication_client_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector/flush_tracker_test.exs
> feat: correctly track disk flushes across all shapes

- website/docs/api/config.md
- website/docs/guides/deployment.md
https://deploy-preview-2936--electric-next.netlify.app/docs/api/config#electric-manual-table-publishing
> Document the ELECTRIC_MANUAL_TABLE_PUBLISHING config option

- packages/sync-service/lib/electric/shape_cache/pure_file_storage.ex
- packages/sync-service/test/electric/shape_cache/pure_file_storage_test.exs
Fixing issue in https://github.com/electric-sql/electric/pull/3042
No changeset as it has not been released
> fix: Do not cache and recover ETS caching table

- .changeset/spotty-wombats-relax.md
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/plug/router_test.exs
> feat: support 3+ layers of subqueries

- .changeset/witty-monkeys-sit.md
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/replication/eval/parser_test.exs
- packages/sync-service/test/electric/replication/eval/runner_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
> feat: allow $n param usage in subqueries

- .changeset/little-schools-destroy.md
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/ipv6-to-ipv4-fallback.lux
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/manager/connection_resolver.ex
- packages/sync-service/lib/electric/connection/manager/pool.ex
- packages/sync-service/lib/electric/connection/manager/supervisor.ex
- packages/sync-service/test/electric/connection/manager/connection_resolver_test.exs
- packages/sync-service/test/electric/connection/manager/pool_test.exs
- packages/sync-service/test/electric/connection/manager_test.exs
> fix(sync-service): Move connection opts discovery into external process

- .changeset/friendly-llamas-count.md
- integration-tests/tests/manual-table-publishing.lux
- integration-tests/tests/not-owner-of-the-publication.lux
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/test/electric/plug/low_privilege_router_test.exs
- packages/sync-service/test/support/component_setup.ex
> Proper error handling when Electric doesn't have read permissions for user tables

- .changeset/cold-ladybugs-tickle.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/async_deleter.ex
- packages/sync-service/lib/electric/shape_cache/pure_file_storage.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/async_deleter_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/support/component_setup.ex
> fix(sync-service): Keep trash directory in same filesystem as shape storage

- .changeset/polite-rats-decide.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> fix: ensure correct tagging of live requests in metrics

- website/docs/api/clients/typescript.md
- website/docs/api/http.md
- website/docs/guides/client-development.md
- website/electric-api.yaml
> docs: added docs for offset=now, subset snapshots and mode=changes_only
