electric-sql/electric

- lib/electric/migration_utils.ex
New environment variable is introduced to provide possibility to overwrite configuration provided in the config file for migrations directory
> Intoduce ELECTRIC_MIGRATIONS_DIR

- Makefile
- README.md
- apply-local-migration.sh
Moves the "apply local migrations" instructions into this repo and provides a makefile entrypoint. This currently just runs the direct curl commands to apply a named migration.
> Add script and instructions to apply local migrations.

- lib/electric.ex
- lib/electric/replication/connectors.ex
- lib/electric/replication/vaxine/log_consumer.ex
- lib/electric/satellite/satellite_client_manager.ex
- lib/electric/satellite/satellite_protocol.ex
- test/electric/replication/vaxine/log_consumer_test.exs
- test/electric/satellite/satellite_ws_test.exs
- test/support/satellite_ws_client.ex
> [vax-390] Forbid multiple connections that use same client_id

- .gitignore
- Dockerfile
- Makefile
- README.md
- config/dev.exs
- config/prod.exs
- config/runtime.exs
- config/test.exs
- lib/electric/migration_utils.ex
- lib/electric/replication/offset_storage.ex
- Makes migration dir & file suffix more configurable
- Makes sure we're calling `System.get_env` or `fetch_env`
only in `runtime.exs`
- Adds documentation for all current environment variables,
apart from auth since it's changed in another open PR
- Moves out offset storage configuration from compile-time to runtime
> chore: streamlined environment variable usage & documentation

- integration_tests/migrations/satellite_test.lux
- integration_tests/migrations/simple_test.lux
- lib/electric/postgres/postgres_manager.ex
- do not try to migrate if migration is not available
- previously in case of an error postgres manager would have left system half-initialised, which would eventually lead to a crash on a next attempt. This has been fixed.
> VAX-469 Better error handling and fail recovery after unsuccesfull migration

- integration_tests/satellite_client/src/client.ts
- integration_tests/satellite_client/yarn.lock
Companion patch to update integration tests config.
> VAX-483: `replication.insecure` field is required on the config object

- compose-mounts.yaml
- integration_tests/common.luxinc
- integration_tests/common.mk
- integration_tests/migrations/compose.yaml
- integration_tests/multi_dc/compose.yaml
- integration_tests/services_templates.yaml
- integration_tests/single_dc/compose.yaml
This change requires Docker engine 18.06.0+ to be installed. That's more than 2 years ago so I think that's ok for our modern dev. `electric` and `vaxine` containers don't seem to handle SIGTERMs in how they implement entrypoints, so this makes them behave.
A more universal approach would be to bake in `tini` or smth like that into the docker images, but this is faster for now.
References:
1. https://vsupalov.com/docker-compose-stop-slow/
2. https://github.com/krallin/tini
> fix: use init that makes containers handle SIGTERM

- integration_tests/satellite_client/Makefile
Tiny pr for bumping version based on the commit.
> chore: Add target to bump electric-sql version for satellite client

- .github/workflows/ci.yml
Instead of creating a comment with coverage on each push, now one comment will be created and updated with each push instead
> chore: fixed duplicating coverage comment on CI

- integration_tests/Makefile
Tiny PR for stopping all docker instances in integration tests.
> chore: Add stop target for all integration tests

- lib/electric/replication/postgres/logical_replication_producer.ex
Referencing `State.origin` and `State.conn` from within lambda function will add the entire `State` to the free variables of the fun, which will cause immerse memory growth when sending this message to a different process, because it will affectively copy the whole state in it.
> [VAX-585] Fix memory explosion when running load tests

- local-stack/compose/docker-compose-templates.yaml
```
local-stack-postgres_1-1  | 2023-04-07 08:34:18.833 GMT [181] FATAL:  role "electric" does not exist
```
> local-stack: fix `pg_isready` healthcheck username.

- clients/typescript/src/satellite/merge.ts
- clients/typescript/src/satellite/oplog.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.migration.test.ts
- clients/typescript/test/satellite/process.test.ts
Fixes VAX-659: Updates are translated to an insert of the modified columns. However, if some columns are not updated, it will not be part of the insert query and thus we loose those values.
This PR fixes this issue by using the complete row information in insert.
However, we need to be careful that this row contains the latest information for all columns, i.e. the incoming entry may have a bigger timestamp than the local change but if some column was only changed locally we should take that value and only use LWW for columns that were modified by both the incoming and the local change.
> fix: insert all column values on update

- components/electric/lib/electric/telemetry.ex
The warning is logged during application startup:
```
12:19:25.206 pid=<0.452.0> [warning] Metric name already exists. Dropping measure. metric_name:=[:electric, :satellite, :connection, :authorized_connection]
```
> electric: fix a duplicate metric warning

- clients/typescript/src/client/model/builder.ts
- clients/typescript/test/client/model/builder.test.ts
- clients/typescript/test/client/model/table.test.ts
Adds support for `not` and `notIn` filters (closes VAX-692).
Adds support for `lt`, `lte`, `gt`, `gte`, `contains`, `startsWith`, and `endsWith` filters (closes VAX-525).
> feat: add support for filters in 'where' argument in DAL

- components/electric/test/electric/to_vaxine_test.exs
- components/electric/test/test_helper.exs
Two tests are skipped in this PR. They need to be reviewed later. I've created https://linear.app/electric-sql/issue/VAX-688/review-the-handling-of-tags-in-unit-tests-after-vaxine-removal so as not to lose track of this.
> Fix electric tests

- components/electric/lib/electric/replication/postgres/migration_consumer.ex
In trying to understand the logic in the code, I found it helpful to refactor it to use a more functional programming style. There's no change in behaviour.
I recommend reviewing this PR one commit at a time.
> refactor(electric): Refactor event processing in Replication.Postgres.MigrationConsumer

- .github/workflows/e2e.yml
- components/electric/Makefile
This step causes the CI workflow to fail for outside contributors.
> ci: Remove the "docker push ghcr.io" step from E2E runs on CI

- clients/typescript/src/migrators/schema.ts
- components/electric/test/electric/to_vaxine_test.exs
- components/electric/test/test_helper.exs
The initial migration was still using String instead of Text when defining the tables.
> fix(satellite): use proper `TEXT` type for shadow table columns

- clients/typescript/src/client/input/createInput.ts
- clients/typescript/src/client/input/deleteInput.ts
- clients/typescript/src/client/input/findInput.ts
- clients/typescript/src/client/input/inputNarrowing.ts
- clients/typescript/src/client/input/updateInput.ts
- clients/typescript/src/client/input/upsertInput.ts
- clients/typescript/src/client/model/builder.ts
- clients/typescript/src/client/model/schema.ts
- clients/typescript/src/client/model/table.ts
- clients/typescript/src/client/util/types.ts
- clients/typescript/src/client/validation/validation.ts
- clients/typescript/test/client/model/table.errors.test.ts
This PR introduces some type magic that modifies the Prisma-generated types to expose only the supported operations.
The various input types (cf. `clients/typescript/src/client/input` folder) are narrowed using the types defined in `clients/typescript/src/client/input/inputNarrowing.ts`.
Additionally, this PR adds unit tests to check that illegal uses throw type errors as well as runtime errors.
The code has been fixed in various places in order to throw meaningful errors.
> feat: Specialise API types

- components/electric/config/config.exs
- components/electric/mix.exs
These are generating a lot of noise. SASL progress reports are generally not useful whereas process crashes are already logged by the Elixir logger.
> Disable SASL logs

- clients/typescript/src/cli/index.ts
- clients/typescript/src/cli/migrator.ts
- clients/typescript/src/migrators/builder.ts
- clients/typescript/src/migrators/index.ts
- clients/typescript/test/migrators/builder.test.ts
This PR fixes a problem with the current main where non NodeJS applications crash because `clients/typescript/src/migrators/index.ts` exported a CLI related function that uses NodeJS to read and write files. But NodeJS is not available in the browser and hence the app crashes.
This PR fixes this problem by moving all CLI related functions that use NodeJS specific methods to the `clients/typescript/src/cli` package. This package should only be used in dev mode when building Electric applications but should never be imported by the rest of the typescript client. Later, we will probably move the CLI package out of the typescript client to a package of its own.
> fix(satellite): do not expose CLI methods in migrators index

- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
It is definitely not the intended alias. Besides, it gets shadowed by the Electric.Postgres.LogicalReplication.Messages.Relation alias further down
> chore(electric): Remove an erroneous alias call

- components/electric/test/test_helper.exs
Reasoning: no use waiting a whole minute for a deadlocked test to time out. In my limited testing, 5 seconds has proven to be reasonable for all current unit tests to pass.
> chore(electric): Lower the default test timeout to 5 seconds

- components/electric/lib/electric/postgres/logical_replication/decoder.ex
- components/electric/lib/electric/postgres/logical_replication/encoder.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/test/electric/postgres/logical_replication/decoder_test.exs
- components/electric/test/electric/postgres/logical_replication/encoder_test.exs
- components/electric/test/electric/replication/postgres/logical_replication_producer_test.exs
Using tuples as the internal representation of row data requires additional list -> tuple -> list transforms throughout the lifetime of the data.
This pr just uses lists throughout thus removing the need for this transform.
Checks:
> chore(electric): Remove use of tuples to hold row data

- clients/typescript/src/migrators/bundle.ts
- clients/typescript/src/migrators/index.ts
- clients/typescript/src/migrators/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/migrators/bundle.test.ts
This PR introduces a safeguard in Satellite that applies incoming migrations only if they were not already applied.
> feat(satellite): ignore already applied migrations

- clients/typescript/src/satellite/oplog.ts
- clients/typescript/test/satellite/process.test.ts
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/migrations/20230328113927_setup_extension.ex
- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers.ex
- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/electric_tag_type_and_operators.sql
- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/shadow_table_creation_and_update.sql
- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/trigger_function_installers.sql
- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/utility_functions.sql
- components/electric/lib/electric/postgres/extension/migrations/20230605141256_electrify_function/electrify.sql
- components/electric/lib/electric/postgres/schema.ex
- components/electric/lib/electric/postgres/shadow_table_transformation.ex
- components/electric/lib/electric/replication/downstream_producer.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/lib/electric/replication/postgres/migration_consumer.ex
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/lib/electric/replication/postgres_connector_sup.ex
- components/electric/lib/electric/replication/satellite_collector_consumer.ex
- components/electric/lib/electric/replication/satellite_collector_producer.ex
- components/electric/lib/electric/replication/satellite_connector.ex
- components/electric/test/electric/postgres/extension/ddl_capture_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/postgres/shadow_table_transformation_test.exs
- components/electric/test/electric/replication/downstream_producer_test.exs
- components/electric/test/electric/replication/postgres/migration_consumer_test.exs
- components/electric/test/electric/replication/postgres/slot_server_test.exs
- components/electric/test/electric/satellite/satellite_ws_test.exs
- components/electric/test/support/downstream_producer_mock.ex
- components/electric/test/support/dummy_consumer.ex
- components/electric/test/support/extension_case.ex
This PR addresses the "write path" from Satellites to PG.
It introduces special conflict resolution triggers, that are installed and/or updated for electrified tables. The general logic is that each Satellite operation is mapped to two operations on PG: one on the shadow table, and one on the main table, with main table operation coming first in the replication stream to keep with the lock order that PG does on transactions that are done via psql. When receiving the writes from PG, we also need to "merge" shadow and main table operations (although we're interested only in one column, `_tags`, from the shadow table. We also use the `_tag` column as a transient value - it doesn't get conflict-resolved, which means that for every transaction it'll stay the same. We're using that knowledge to …
> feat!(pg): move conflict resolution to PG using special triggers

- clients/typescript/src/cli/migrations/handler.ts
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/test/cli/migrations/handler.test.ts
- components/electric/lib/electric/plug/migrations.ex
- components/electric/test/electric/plug_test.exs
This PR introduces an optional `--watch` flag for the CLI's `generate` command.
When running with the `--watch` flag, the process periodically polls Electric's migration endpoint for new migrations. Use it as follows:
```sh
npx electric-sql generate --watch
```
We modified the Electric http endpoint to return a 204 if there are no new migrations.
> feat(CLI): watch flag for generate command

- components/electric/lib/electric/application.ex
- components/electric/lib/electric/postgres/cached_wal/api.ex
- components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
- components/electric/lib/electric/postgres/cached_wal/producer.ex
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/postgres_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/satellite/satellite_ws_test.exs
- components/electric/test/support/postgres_case.ex
- components/electric/test/support/postgres_test_connection.ex
- e2e/tests/3.1_node_satellite_loads_local_migrations.lux
- e2e/tests/3.5_fresh_node_satellite_receives_all_migrations_during_initial_sync.lux
- e2e/tests/compose.yaml
Closes VAX-669.
This PR implements a "full initial sync" that sends the migration history as well as all data from electrified tables to a fresh client in one go. Subsequent improvements are coming up as defined by VAX-732, VAX-733, and VAX-734.
Note that the commits authored by Ilia in this PR overlap with the changes made in https://github.com/electric-sql/electric/pull/205. Once that PR is merged, I will rebase mine on top.
> feat(electric): Initial sync from PG

- clients/typescript/src/client/input/findInput.ts
- clients/typescript/src/client/input/syncInput.ts
- clients/typescript/src/client/model/builder.ts
- clients/typescript/src/client/model/model.ts
- clients/typescript/src/client/model/schema.ts
- clients/typescript/src/client/model/shapes.ts
- clients/typescript/src/client/model/table.ts
- clients/typescript/src/electric/index.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/shapes/cache.ts
- clients/typescript/src/satellite/shapes/types.ts
- clients/typescript/test/client/model/builder.test.ts
- clients/typescript/test/client/model/shapes.test.ts
- clients/typescript/test/client/model/table.errors.test.ts
- clients/typescript/test/client/model/table.test.ts
- clients/typescript/test/client/notifications.test.ts
- clients/typescript/test/satellite/process.test.ts
This PR extends the DAL with functionality to sync shapes.
The signature of this `sync` method is:
```
sync<T extends SyncInput<Include>>(i?: T): Promise<Sub>
interface SyncInput<Include> {
include?: Include
}
type Sub = {
dataReceived: Promise<void>
}
```
The returned promise resolves when the subscription request is accepted by Electric.
The value to which it resolves is an object containing a `dataReceived` property that is again a promise.
The `dataReceived` promise resolves when the subscription request is fulfilled, i.e. all data has been loaded.
Example usage:
```
// Sync only the `Post` table
const { dataReceived } = await db.Post.sync()
await dataReceived
// Sync the `Post` table and the tables for the related `author` and `profile` fields
const { dataReceived } = await …
```
> feat(DAL, Satellite): add sync shape functionality to DAL

- components/electric/lib/electric/postgres/shadow_table_transformation.ex
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/test/electric/postgres/shadow_table_transformation_test.exs
- e2e/tests/2.5_delete_gets_registered_correctly.lux
Internal representation of tags on PG is done in a way that any PG-originating tag has it's origin component set to NULL, and then NULL origins are ordered higher than any strings. When PG-originating tags are sent to Satellites, we preprocess tags to replace NULL values with pg origin name. But the inverse path has an error, whereby on a return trip the pg origin in observed tags is not set back to NULL before being set to PG like it should.
Closes VAX-762
> fix(electric): tag serialization wasn't working assigning `null` to tags

- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/test_helper.exs
Adds support for the `SatUnsubsReq` message, that stops ongoing subscriptions. That means the client will no longer receive data for that particular subscription, and any yet-unfulfilled subscription listed in the unsubscribe request will get immediately cancelled and their data discarded.
Note: E2E tests are missing because although `unsubscribe` call can be issued by the client, we're yet to expose a public interface for it to e2e test.
> feat(electric): support unsubscribe messages

- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/common.ts
- clients/typescript/test/satellite/process.tags.test.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/satellite/process.timing.test.ts
- Removes `| SatelliteError` from return types in Satellite client (we properly raise the errors, they shouldn't have been in the type)
- Uses proper AVA test type casting to not have `t.context as ContextType` in every test
> chore: fix types in tests

- clients/typescript/test/client/generated/index.ts
- clients/typescript/test/client/model/shapes.test.ts
- clients/typescript/test/client/model/table.errors.test.ts
- clients/typescript/test/client/model/table.test.ts
- clients/typescript/test/client/notifications.test.ts
- clients/typescript/test/example-typing-usage/better-sqlite3.ts
- clients/typescript/test/example-typing-usage/cordova-sqlite-storage.ts
- clients/typescript/test/example-typing-usage/expo-sqlite.ts
- clients/typescript/test/example-typing-usage/react-native-sqlite-storage.ts
- clients/typescript/test/frameworks/react.test.tsx
- e2e/satellite_client/src/client.ts
- e2e/satellite_client/src/generated/models/index.ts
- examples/web-wa-sqlite/README.md
- examples/web-wa-sqlite/src/Example.tsx
- generator/src/functions/tableDescriptionWriters/writeTableSchemas.ts
Hey, mind if I rename this? It just makes all the initial instantiation examples much sweeter to be:
```tsx
await electrify(conn, schema, config)
```
As opposed to:
```tsx
await electrify(conn, dbSchema, config)
```
I'll obviously update the docs. I think this catches all the current uses, certainly in the monorepo.
> client: rename dbSchema to schema.

- components/electric/lib/electric/plug/migrations.ex
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/plug_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/support/extension_case.ex
- components/electric/test/support/schema_loader.ex
- e2e/tests/3.5_fresh_node_satellite_receives_all_migrations_during_initial_sync.lux
Closes VAX-734.
These changes are based on https://github.com/electric-sql/electric/pull/222 so that PR needs to be merged first.
This PR fixes the issue described in the ticket as follows:
* `Extension.migration_history()` is updated to include `txid` and `txts` of migration transactions in its return value.
* Those `txid` and `txts` are included in the `Transaction` structs created by InitialSync.
* The `txid` of the most recent migration is stored in WsServer's state.
* When WsServer receives a transaction from CachedWal.Producer, it checks whether it is a migration and whether its `xid` is greater than the `txid` stored in its state. If not, the transaction is dropped because it was already included in the initial sync previously.
NOTE: If a newly connected client doesn't do initial …
> fix(electric): Initial sync of migrations

- components/electric/lib/electric/postgres/cached_wal/api.ex
- components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
Closes VAX-735.
These changes are based on https://github.com/electric-sql/electric/pull/225 so that PR needs to be merged first.
This PR implement a check to see if the client's LSN falls into the cached WAL window. If not, `BEHIND_WINDOW` error is returned in `SatInStartReplicationResp` which then results in the client dropping all of its subscriptions, as implemented in https://github.com/electric-sql/electric/commit/bc9589702906926af334164c1ab7f7035f95dec3.
Remaining work:
* ~[ ] Write an e2e test that verifies the client discards its subscriptions when it receives the `BEHIND_WINDOW` error.~ I couldn't implement the ability to stop a client and write its LSN in e2e tests. Another way to write the e2e test would be to configure CachedWal.EtsBacked.max_cache_count per test but that …
> feat(electric): Detect when a client is outside of the cached WAL window

- clients/typescript/test/satellite/serialization.test.ts
I added some additional serialization test cases, as only Strings and null values were being tested.
Related to this, does Electric support Blob columns? I haven't found any example in the tests, so I'm not sure if it's supported or not.
> Expand serialization tests with float and integer values

- clients/typescript/src/client/model/model.ts
- clients/typescript/src/client/model/shapes.ts
- clients/typescript/src/client/model/table.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/client/model/shapes.test.ts
- clients/typescript/test/satellite/process.test.ts
- e2e/satellite_client/src/client.ts
Renames `dataReceived` to `synced` and `Sub` to `ShapeSubscription`.
I did not rename `Sub` to `Shape` because there is already a `Shape` type.
So i think it makes more sense that the client passes a `Shape` to sync and that they get back a `ShapeSubscription`.
```typescript
sync(shape: Shape): Promise<ShapeSubscription>
```
> feat(Satellite, DAL): rename `dataReceived` and `Sub`

- components/electric/config/dev.exs
- components/electric/config/runtime.exs
- components/electric/test/electric/replication/postgres/migration_consumer_test.exs
- components/electric/test/support/postgres_test_connection.ex
These options have been retired since d3095ca42285380ac4b001d57a3795889fe96a9f.
This needs to wait for https://github.com/electric-sql/electric/pull/222 to get merged because that PR moves some replication config around.
> chore(electric): Remove unused replication config options

- components/electric/lib/electric/application.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/subscription_manager.ex
- components/electric/lib/satellite/satellite_ws_client.ex
- components/electric/test/electric/satellite/subscriptions_test.exs
- e2e/tests/2.6_subscriptions_can_be_resumed_on_reconnect.lux
- e2e/tests/_shared.luxinc
Allow subscription resume on reconnect by accepting a list of subscriptions the client wants to continue. The subscriptions are stored **in memory** for now, which aligns with how we allow subscriptions to resume -- only if still within the cached WAL window. WAL cache is in memory, so storing subscriptions with a "longer" lifetime makes little sense for now. If the client ever tries to connect outside the window, we immediately consider them fallen behind and remove saved subscriptions.
> feat(electric): allow subscription resume on reconnect

- clients/typescript/test/satellite/process.test.ts
This has been mentioned in #132 , but since most of those have already been fixed, I include this PR to isolate it and leave it for discussion.
The `t.is(lsn2, '2')` is never executed in the original code, and the test passes, but the assert actually fails.
> Modify test to un-silence wrong expectation

- clients/typescript/src/satellite/process.ts
> chore: remove `|SatelliteError` from types and one unused property

- clients/typescript/src/_generated/protocol/satellite.ts
- clients/typescript/src/migrators/bundle.ts
- clients/typescript/src/migrators/index.ts
- clients/typescript/src/migrators/mock.ts
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/client.test.ts
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/schema_cache.ex
- components/electric/lib/electric/postgres/extension/schema_loader.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/satellite/protobuf_messages.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/replication/shapes_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/support/schema_loader.ex
- components/electric/test/support/setup_helpers.ex
- e2e/tests/3.1_node_satellite_loads_local_migrations.lux
- protocol/satellite.proto
Closes VAX-733.
These changes are based on https://github.com/electric-sql/electric/pull/218 so that PR needs to be merged first.
This PR updates the client to include its local `schemaVersion` in the `SatInStartReplicationReq` message which the server then uses to only fetch migrations that the client is missing.
Remaining work:
* ~[ ] Write an e2e test that verifies the server only sends migrations that the client doesn't already have.~ It seemed like a good idea initially, but after struggling with implementing proper setup for discarding client's local state, I've abandoned it. Currently, this functionality is covered with TypeScript tests on the client and Elixir tests on the server.
> feat(satellite,electric): Rely on client-supplied schema version to push only missing transactions to the client

- clients/typescript/src/_generated/protocol/satellite.ts
- components/electric/lib/electric/satellite/protobuf_messages.ex
- protocol/satellite.proto
While technically a breaking change, we haven't been using this enum value. So I don't see the need in bumping the protocol version or reserving the value 2 in SatAuthHeader to prevent its reuse in the future simply because nothing running in the wild is depending on it.
> chore(protocol): Remove unused SCHEMA_VERSION enum value from Satellite protocol

- clients/typescript/src/_generated/protocol/satellite.ts
- clients/typescript/src/util/proto.ts
- clients/typescript/src/util/types.ts
- components/electric/lib/electric/replication/shapes.ex
- components/electric/lib/electric/satellite/protobuf_messages.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/test/electric/replication/shapes_test.exs
- protocol/satellite.proto
I thought I had made this changes in my previous PR that touched the protocol. But noticed today there were still instances of `CODE_UNSPECIFIED` in the code. Thank god for `git reflog`.
> feature(protocol): Add missing error codes to the protocol definition

- .changeset/old-ways-bow.md
- clients/typescript/.eslintrc.cjs
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/src/util/common.ts
- clients/typescript/src/util/types.ts
We've checked if the replication is already established in the `subscribe` call, but we actually don't wait (or even expose a way to know) if the replication has been established. This addresses one part of it: the `subscribe` call will wait until `startReplication()` call resolves after `connect()`. That way we can reliably send the subscription request only after the replication is started, even if `.sync()` call is made immediately after `await electrify(...)`. Any fails in `connect()` or `authenticate()` will abort the `.sync()` call with the same error, since at that point we cannot do any online calls.
We may still want to the result of `startReplication()` on `electrify` call, but that's for another PR.
> fix: make sure the subscribe call is held off until the replication is established

- .changeset/odd-timers-tickle.md
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
Shapes don't use fully qualified table names, but the functions disabling the triggers expect FQ names. So we didn't disable the triggers before. Ideally FQ names should be represented by a different type (e.g. a tuple), but that's for another day
> fix: correctly disable triggers on shape GC

- clients/typescript/package.json
- clients/typescript/src/_generated/protocol/satellite.ts
- clients/typescript/src/satellite/client.ts
- clients/typescript/test/satellite/client.test.ts
- components/electric/lib/electric/postgres/cached_wal/producer.ex
- components/electric/lib/electric/satellite/protobuf_messages.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/lib/satellite/satellite_ws_client.ex
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/electric/satellite/ws_pg_to_satellite_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- e2e/tests/3.10_node_satellite_can_resume_replication_on_reconnect.lux
- e2e/tests/3.9_fresh_node_satellite_receives_only_missing_migrations_during_initial_sync.lux
- e2e/tests/_shared.luxinc
- protocol/satellite.proto
> chore(protocol): Remove FIRST_LSN, LAST_LSN, and LAST_ACKNOWLEDGED from the protocol

- .changeset/pretty-melons-ring.md
- clients/typescript/src/drivers/wa-sqlite/index.ts
I noticed my web application's web socket came from a file called `react-native.js`, which I assume is a bug.
Unless the `ReactNativeSocketFactory` is meant to be a general one and should perhaps be renamed?
> drivers: use web socket in wa-sqlite driver.

- .changeset/shiny-pears-accept.md
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
Continuation of #278, adding the test and covering additional behaviour
> fix: make sure the subscription request is saved early

- .changeset/stale-zoos-poke.md
- clients/typescript/package.json
- clients/typescript/src/declarations.d.ts
- clients/typescript/src/satellite/process.ts
- pnpm-lock.yaml
This small change now guarantees the result type from `_getMeta` depending on the entry key:
To ensure this result, `_setMeta` also checks its inputs:
Here, we read `Argument of type '"nonsense"' is not assignable to parameter of type '"" | `${string}-${string}-${string}-${string}-${string}`'.`, _i.e._, it is not a valid `Uuid`.
While editing the `Uuid` type, I also noticed that the module was declared empty in `declarations.d.ts`. I put the official typings instead.
Closes #259.
> Add precise typings for _getMeta

- .changeset/lucky-lies-mate.md
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
Fixed the race condition by:
- putting a mutex in the throttled wrapper for perform snapshot
- added an assertion on the perform snapshot to raise when we violate the assumption
- added regression tests to show the race condition
Refactored the perform snapshot function to accumulate statements instead of calling multiple promises
Closes #258
> fix: resolved race condition in `_performSnapshot`

- clients/typescript/test/satellite/client.test.ts
It looks like this was missed in a recent commit.
> Remove .only in client tests

- .changeset/tasty-buckets-smoke.md
- clients/typescript/src/config/index.ts
Fixing a problem of my own making because I 💯 asked @kevin-dp to implement as is but now having used it a bit ...
This changes the `config.url` parsing when instantiating the client. The current implement uses an `electric://` protocol and doesn't support SSL.
This change updates to support `http[s]://` and `ws[s]://`protocols and an `ssl=true` parameter and uses `new URL(s)` to do the parsing, rather than a regex.
This allows us to use SSL by default when the user provides a url with a secure protocol and also defaults the port to 443 for secure and 80 for insecure. This allows URLs like `wss://my-electric-service.example.com` to default to 443 rather than `5133`, which is more realistic in production.
> client config: improve URL parsing.

- clients/typescript/src/satellite/process.ts
This is a minor lint fix. throttledSnapshot is created in the constructor and there are checks for it possibly being undefined.
Is that correct?
> chore(client): throttledSnapshot cannot be undefined

- .changeset/lemon-seals-mix.md
- clients/typescript/src/cli/migrations/migrate.ts
Modify the generate command in the CLI to output the migrations in a .ts file instead of a .js file.
> fix(CLI): Generate ts file of migrations instead of js file

- .changeset/moody-comics-pretend.md
- clients/typescript/src/migrators/schema.ts
- clients/typescript/src/migrators/triggers.ts
- clients/typescript/src/satellite/oplog.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/util/sets.ts
- clients/typescript/src/util/statements.ts
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/process.migration.test.ts
- clients/typescript/test/satellite/process.tags.test.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/support/satellite-helpers.ts
- clients/typescript/test/util/statements.test.ts
- e2e/common.mk
Previous implementation executed 3N+2 queries for N oplog entries (`UPDATE` timestamps, `SELECT` updated, then, per oplog entry, `SELECT` shadow row, `UPDATE` oplog entry, `UPDATE` or `DELETE` shadow row).
This implementation always executes exactly 4 queries to achieve the same. This lowers the amount of times we're traversing C or WASM boundary and offloads more work to SQLite.
This shouldn't affect the performance of current "lightweight" apps, but is likely to show significant improvements over 100+ oplog entries
> chore: rewritten `_performSnapshot` function

- .changeset/flat-rabbits-scream.md
- clients/typescript/src/client/model/client.ts
- clients/typescript/src/electric/index.ts
- clients/typescript/src/electric/namespace.ts
- clients/typescript/src/frameworks/react/hooks/useConnectivityState.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/client/model/shapes.test.ts
- clients/typescript/test/frameworks/react.test.tsx
The problem was that existing satellite processes were not reporting their existing connectivity status to the connectivity hook. This was confusing the hook into always starting in a disconnected state, despite the connection being connected.
I've left one note in the code about a future refactor. I'm not convinced by the current code structure and connectivity state machine. But suggesting we merge this as we need the fix urgently.
> client: fix buggy connectivity hook.

- .changeset/bright-doors-cheer.md
- components/electric/lib/electric/replication/changes.ex
- components/electric/lib/electric/replication/changes/ownership.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/replication/shapes/shape_request.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/test/electric/replication/changes/ownership_test.exs
- components/electric/test/electric/replication/shapes/shape_request_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/support/postgres_test_connection.ex
This is a somewhat temporary fix to allow for partial replication based on user id. This assumes user id is kinda immutable per device for the on-device database lifetime (as does a lot of our code), so no effort has been made to ensure row deduplication. Should tide us over until proper DDLX
> fix: respect `electric_user_id` filtering on initial sync

- clients/typescript/src/client/model/table.ts
- clients/typescript/src/drivers/react-native-sqlite-storage/mock.ts
- clients/typescript/src/frameworks/react/hooks/useLiveQuery.ts
- clients/typescript/test/client/model/builder.test.ts
- clients/typescript/test/client/model/table.test.ts
- clients/typescript/test/frameworks/react.test.tsx
Small changes to make the argument of `liveMany` optional such that we can write `db.items.liveMany()` instead of `db.items.liveMany({})`.
Also introduces some additional unit tests for the query builder to test functionality of the DAL.
> feat(DAL): made argument of liveMany optional

- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/trigger_function_installers.sql
As explained in the official docs[1]:
> SECURITY INVOKER indicates that the function is to be executed
> with the privileges of the user that calls it. That is the default.
> SECURITY DEFINER specifies that the function is to be executed
> with the privileges of the user that owns it.
[1]: https://www.postgresql.org/docs/current/sql-createfunction.html
While testing the scenario described in VAX-806, I was hitting multiple permission denials, such as
ERROR:  permission denied for schema electric
LINE 3:             __current_tag electric.tag;
and, after granting the demo user access to the "electric" schema,
ERROR:  permission denied for table shadow__public__sliders
CONTEXT:  SQL statement "INSERT INTO electric.shadow__public__sliders (_last_modified, _tag, _tags, _resolved,
id, …
> fix(electric): Adorn electric-generated trigger functions with SECURITY DEFINER

- .github/workflows/e2e.yml
This reverts commit 1d78f9fa49a99a18284adbe17d26368ee3cde5b3.
This permission is no longer needed since we have removed the "docker push to ghcr.io" step from the workflow in 1a3393830ca47d494c20b8b5f74b912c8a52c56e.
> chore(ci): Revert "add package write permission to the e2e workflow (#156)"

- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/postgres/extension/electrify_test.exs
- components/electric/test/electric/postgres/extension/schema_cache_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- components/electric/test/support/postgres_test_connection.ex
- e2e/init.sql
- e2e/tests/02.02_migrations_get_streamed_to_satellite.lux
- e2e/tests/03.05_fresh_node_satellite_receives_all_migrations_during_initial_sync.lux
- e2e/tests/04.01_electric_api_returns_migrations.lux
- e2e/tests/_shared.luxinc
Even though we support this type on the server, our generator (and maybe DAL also) cannot handle it properly yet. So letting users electrify tables that have the UUID type would lead to runtime errors at the booting time of their web app.
> chore(electric): Disallow UUID columns in electrify()

- clients/typescript/src/satellite/client.ts
- clients/typescript/src/util/bitmaskHelpers.ts
- clients/typescript/src/util/proto.ts
- e2e/tests/03.03_node_satellite_sends_and_recieves_data.lux
- e2e/tests/03.04_node_satellite_correctly_updates_serialization_caches.lux
- e2e/tests/03.05_fresh_node_satellite_receives_all_migrations_during_initial_sync.lux
- e2e/tests/03.06_node_satellite_does_sync_on_subscribe.lux
- e2e/tests/03.07_node_satellite_can_delete_freshly_synced_rows.lux
- e2e/tests/03.08_node_satellite_can_resume_subscriptions_on_reconnect.lux
- e2e/tests/03.09_fresh_node_satellite_receives_only_missing_migrations_during_initial_sync.lux
- e2e/tests/03.10_node_satellite_can_resume_replication_on_reconnect.lux
Before we JSON-logged messages that are sent/received, which made inspecting the contents quite complex, since text contents weren't decoded. This makes the logging mildly more palatable.
Before:
```
Received message {"$type":"Electric.Satellite.v1_4.SatOpLog","ops":[{"$type":"Electric.Satellite.v1_4.SatTransOp","begin":{"$type":"Electric.Satellite.v1_4.SatOpBegin","commitTimestamp":{"low":-38279406,"high":393,"unsigned":true},"transId":"","lsn":{"type":"Buffer","data":[50,53,53,53,54,50,50,52]},"origin":"c0cbe095-4a2c-4236-8d67-a8a8f6d3edfc","isMigration":false}},{"$type":"Electric.Satellite.v1_4.SatTransOp","insert":{"$type":"Electric.Satellite.v1_4.SatOpInsert","relationId":16632,"rowData":{"$type":"Electric.Satellite.v1_4.SatOpRow","nullsBitmask":{"type":"Buffer","data":[40]},"values": …
```
> chore: add better logging to client proto requests/responses

- .changeset/healthy-dingos-destroy.md
- components/electric/lib/electric/replication/shapes/shape_request.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/test/electric/replication/shapes/shape_request_test.exs
- components/electric/test/electric/satellite/subscriptions_test.exs
This is a very simplified enabling implementation so that we remove a foot-gun of intersecting shapes while we only support unfiltered full-table sync (with one immutable filter of user id).
> fix: don't send rows to clients that have already seen this particular table

- .changeset/five-fishes-sparkle.md
- clients/typescript/package.json
- clients/typescript/src/cli/migrations/migrate.ts
- examples/starter/package.json
- examples/starter/src/index.ts
- examples/starter/template/README.md
- examples/starter/template/db/connect.js
- examples/starter/template/db/migrate.js
- examples/starter/template/db/migrations/create_items_table.sql
- examples/starter/template/db/util.js
- examples/starter/template/dot_gitignore
- examples/starter/template/package.json
- examples/starter/template/src/Example.tsx
- pnpm-lock.yaml
This PR hides output from the underlying processes when running `npx create-electric-app my-app` as well as in the output of the yarn commands. Also introduces a new command `db:connect` that connects to the PG database using the `DATABASE_URL` env variable. If that variable is not defined it assumes that we're running the entire stack and it will connect to the PG that is running in Docker.
> chore(starter): improved output and commands

- .changeset/young-cougars-marry.md
- clients/typescript/src/migrators/bundle.ts
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/config.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/sockets/node.ts
- clients/typescript/src/sockets/react-native.ts
- clients/typescript/src/sockets/web.ts
- clients/typescript/src/util/types.ts
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/process.test.ts
After server is gone, it loses information about clients. Right now it is throwing a BEHIND_WINDOW error when a client tries to reconnect and server doesn't find any info regarding that client. It's arguable if this is the appropriate error to throw, but it highlighted a problem with failures to reconnect on error.
1. the client would not trigger subscriptions cleanup because of improper configuration
2. it would send unsubscribe requests to the server without first starting replication, which would result in an error
3. there was de-referencing error to a variable that was out of scope
After fixing all that, application was connecting but not catching up with the server yet. The problem was that we had cleared subscriptions and did not request them again. There is a question here: is …
> fix(satellite): vax-807 cannot catch up to the servers current state

- examples/introduction/src/components/commands/PSQLCommand.tsx
Before:
```
psql "postgresql://generated_user:generated_passwd@core_user:core_password@postgres:54321/electric"
```
After:
```
psql "postgresql://generated_user:generated_passwd@postgres:54321/electric"
```
> fix: malformed psql command in docs

- clients/typescript/src/satellite/client.ts
Now `toMessage` no longer returns an union type, it throws, so the `messageOrError instanceof SatelliteError` logic would not be properly checked.
The Log.debug condition can be moved to the try/catch so that both success and errors can be handled correctly.
> fix(client): toMessage call incorrectly used as union

- clients/typescript/src/client/model/builder.ts
- clients/typescript/test/client/model/shapes.test.ts
It's a perfectly valid pattern to bind a liveQuery to an unsynced table.
Plus a warning really messes with the React Native DX.
> client: reduce severity of unsynced table warning.

- .changeset/tough-actors-divide.md
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/lib/electric/replication/satellite_collector_producer.ex
- components/electric/test/electric/replication/postgres/slot_server_test.exs
- components/electric/test/electric/replication/satellite_collector_producer_test.exs
Original issue is that when PG cuts the TCP connection that is sourcing the replication from Electric, the process structure wasn't implemented in a way that allowed correct continuation of the replication stream to PG without losing operations by the clients.
1. I've moved in `OffsetStorage.save_pg_position` into the loop because the loop crashes on a closed connection when trying to call the `send()` function that matches on `:ok`
2. When PG reconnects, it will tell us the latest LSN it persisted - we use the saved mapping to restore that position in the cache and now we can continue from there.
3. If all `send()` calls have succeeded we notify our producer that the Satellite-sent txs can be garbage collected
There are still two issues after this PR:
1. We're calling `ack` on the …
> fix: make sure that if slot server dies, it can continue from a known point

- .changeset/dry-walls-decide.md
- components/electric/lib/electric/replication/satellite_collector_producer.ex
- components/electric/test/electric/replication/satellite_collector_producer_test.exs
Issue here was that we're storing PG's position in Electric's source stream in dets, which means it gets correctly restored on Electric restart, but upon the Electric restart, Electric's source stream itself is lost, so position now makes no sense.
A larger scope fix we've discussed also will include not storing PG's position at all in a persistent way, as it makes little sense across restarts
> fix: make sure that PG continues to be fed after restart

- clients/typescript/src/_generated/protocol/satellite.ts
- components/electric/lib/electric/satellite/protobuf_messages.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- protocol/satellite.proto
We have no logic on the client handling it. There is a bit of server-side code that checked for the presence of SYNC_MODE but since that option is never used, we can simplify the code by removing the conditional branches.
> chore(electric): Remove unused SYNC_MODE option from SatInStartReplicationReq

- .changeset/afraid-suns-wink.md
- clients/typescript/src/satellite/oplog.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/migrators/builder.test.ts
- clients/typescript/test/satellite/process.migration.test.ts
- clients/typescript/test/satellite/process.test.ts
Problem was that GC was called after the application, so when a transaction did a round-trip to the server and back, it would then be included in the conflict resolution against itself, which is a big problem if the tx was altered on the server-side conflict resolution process. Removing these transactions first ensures we don't have this problem.
> fix: run GC before applying the incoming txn

- clients/typescript/src/electric/adapter.ts
- clients/typescript/src/migrators/schema.ts
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/util/types.ts
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/common.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/satellite/process.timing.test.ts
- components/electric/lib/electric/replication/satellite_collector_producer.ex
- e2e/tests/03.12_server_correctly_continues_the_replication.lux
This PR simplifies the client by removing `_lastAck` and `_lastSent` from the process, and `ack_lsn` from the outbound replication state in the client.
There are three parts to validity of these changes:
1. `this.outbound.ack_lsn` in the client was just unused. It was assigned in a bunch of places, but read only in one function (`getOutboundLogPositions`), where the only calling place (`SatelliteProcess#_performSnapshot`) didn't use that part of the return value.
This PR removes this field, and simplifies function signatures appropriately.
2. `_lastSentRowId` in the client was set in a lot of places as well, but only usage place was to fill `client.outbound.enqueued_lsn`. This allowed the client to continue streaming to the server from the LSN it didn't sent before, however that logic is …
> chore: remove ack logic from the client as unused

- examples/expo/package.json
- examples/expo/yarn.lock
Changes the version of the `@types/react-native` dev dependency to a valid version in the expo example app.
> chore(examples): fix @types/react-native dev dependency

- .changeset/warm-teachers-obey.md
- clients/typescript/src/electric/index.ts
- clients/typescript/src/satellite/process.ts
Closes VAX-880.
No need to also enable the compensations because they are already enabled by the base migration:
- defined here with compensations set to 1: https://github.com/electric-sql/electric/blob/main/clients/typescript/src/migrators/schema.ts#L20
- and applied here: https://github.com/electric-sql/electric/blob/main/clients/typescript/src/migrators/bundle.ts#L38
> chore(client): enable foreign_keys pragma on startup

- components/electric/lib/electric/satellite/ws_server.ex
- e2e/tests/03.09_fresh_node_satellite_receives_only_missing_migrations_during_initial_sync.lux
Utilize ws-level ping/pong frames for heartbeat. We technically stop using protocol level ping/pong messages here, but they were not used anyway, and are fully removed in the next PR
> chore: switch ping/pong to ws-level

- components/electric/lib/electric/plug/status.ex
- components/electric/lib/electric/postgres/postgres_manager.ex
- e2e/tests/01.01_simple_startup.lux
- examples/beer-stars/README.md
We should review the usage of connectors in the code base and refactor those bits of code now that we have a single connector. In this PR I'm only addressing the issue raised on Linear because it made sense to me to make the Status API return a human-readable explanation of the server's status.
> chore(electric): Clean up the response returned from the Status API

- e2e/tests/_shared.luxinc
This is an attempt to reduce the flakiness of the E2E tests.
Sometimes the following exception is thrown in the electric service
It happens when calling the macro migrate_pg sequentially, like in the test 03.10
My guess by looking at the macro and the "Unable to retrieve oid for table" message is that Electric is looking at the migration before it has been applied. The macro only waits for the message `Applying migration $version`, but we could match `Saved schema version $version` to know when it finished.
https://github.com/electric-sql/electric/blob/cf4ee7c2344b2391e65cb6aa4e63314728776656/e2e/tests/_shared.luxinc#L110
I'm not experienced at all with lux, but we've been using it for the Dart client as well and we learned a few things :sweat_smile: 
I hope this small change makes it …
> fix: Update migrate_pg lux macro to actually wait for migration to finish

- .changeset/moody-clouds-itch.md
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/postgres/extension/ddl_capture_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/satellite/ws_validations_test.exs
- docs/usage/data-modelling/types.md
Here I'm also removing `int8` from the list of types accepted by the `electrify()` function since it's not handled correctly on the client.
Closes VAX-1034.
> chore(electric, docs): Update docs to mention supported data types

- clients/typescript/src/satellite/process.ts
While developing the Dart client we were having some trouble debugging an unhandled exception while decoding the new supported types (bool and date) because it was not being logged anywhere.
This unhandled exception was silent because this branch of the code doesn't throw, it just swallows the exception and disconnects the client.
I would propose to at least log a warning/error when we reach here.
> feat(client): logs when encountering unhandled errors in Satellite

- .changeset/happy-buttons-end.md
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/functions.ex
- components/electric/lib/electric/postgres/extension/functions/validate_table_column_types.sql.eex
- components/electric/lib/electric/postgres/extension/migrations/20230605141256_electrify_function.ex
- components/electric/lib/electric/postgres/extension/migrations/20230605141256_electrify_function/electrify.sql.eex
- components/electric/lib/electric/satellite/serialization.ex
- docs/usage/data-modelling/types.md
> chore(electric): Define __validate_table_column_types() at startup to use the up-to-date list of supported types

- .changeset/gold-knives-dress.md
- components/electric/lib/electric/plug/satellite_websocket_plug.ex
- components/electric/lib/electric/replication/connectors.ex
This change allows running electric per db, since slots have to be instance-unique, not database-unique. This is not related to horizontally scaling Electrics against a single PG instance.
> feat: suffix slot name with db name

- examples/introduction/src/electric.ts
- examples/web-wa-sqlite/src/Example.tsx
This updates the web and intro examples to scope the local database name to the library version. The result is that users who previously had a local database with a previous library version will use a new database after the library is updated.
The intention is to prevent some local-db incompatibility bugs with users that return to the website.
Note that the implementation uses a json file import. Is there any potential compatibility issue with this?
> examples: add library version to scoped db names.

- .changeset/good-cooks-watch.md
- clients/typescript/src/migrators/bundle.ts
- components/electric/README.md
As reported in the [#bug-reports channel in Discord](https://discord.com/channels/933657521581858818/1079688869852753981/1153973432497750108), we have a [client-side validation](https://github.com/electric-sql/electric/blob/5f44c1a54b06b4e851d695478a284440c9900309/clients/typescript/src/migrators/bundle.ts#L21) that only allows numbers and the underscore to be used in migration versions.
Here I'm also implementing the relaxation of the migration version validation that was proposed along with the bug report.
> Fix migration version in the README

- generator/README.md
Link to https://www.prisma.io instead of https://github.com/electric-sql/electric/edit/main/generator/www.prisma.io.
> fix(docs): working prisma link

- docs/integrations/frontend/index.md
link in docs has a typo in it, breaking the link
> fix : broken link in frontend integrations

- components/electric/lib/electric/replication/postgres/migration_consumer.ex
This is a leftover from the work done on VAX-911 (GitHub PR #386). It should have been removed during a rebase of the PR, since pings and acks had already been removed from main by then, see
https://github.com/electric-sql/electric/pull/408/files#diff-b0cea52cb9ec25d24558bed7297b456f66bd57a5080ef259d568bc3bffc05093L144-L149.
> chore(electric): Remove the sending of the :lsn_ack message that nobody receives

- components/electric/lib/electric/postgres/extension/functions.ex
- components/electric/lib/electric/postgres/extension/functions/create_active_migration.sql.eex
- components/electric/lib/electric/postgres/extension/migrations/20230328113927_setup_extension.ex
- components/electric/lib/electric/postgres/extension/migrations/20230918115714_add_unique_constraint_ddl_commands.ex
At least I think it was an accidental change when the updated version of the `create_active_migration()` function was introduced in https://github.com/electric-sql/electric/pull/439/files#diff-578136eb5d1250bc92bc4ccdde42fdeea6bed399bb1f22f4d621074813070932R35.
> chore(electric): Move the definition of create_active_migration() out of migrations

- .changeset/funny-terms-knock.md
- clients/typescript/src/migrators/builder.ts
- clients/typescript/test/migrators/builder.test.ts
This PR solves the index bug described in #457.
The bug was caused by the client migration code which tried to build table triggers even if the table information is missing. The code was modified not to build any triggers if the table information is missing. The table information may be missing e.g. when only creating an index.
> fix (client): solve migration bug with indexes

- .changeset/chilled-planes-attack.md
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/test/cli/migrations/migrate.test.ts
This PR fixes the bug for a table named "model", described by a user on [Discord](https://discord.com/channels/933657521581858818/933657523049885698/1156342498453639260).
We were parsing the Prisma schema in order to capitalise model names but if the model name itself was "model" we would capitalise the "model" keyword instead of the model name "model". This is fixed by replacing the exact match in the string instead of replacing the first occurrence of the table name.
Also extended the unit test to check this case.
> fix (generator): correctly capitalise table named model

- .changeset/beige-yaks-draw.md
Forgot to add one in https://github.com/electric-sql/electric/pull/508.
> chore: Add a changelog entry for the floating point syncing fix

- components/electric/lib/electric/plug/satellite_websocket_plug.ex
This should provide more useful debug logs than the current
[info] Get /ws
[info] Sent 400 in 153 us
> chore(electric): Log failure reason when client fails to establish a WebSocket connection

- components/electric/lib/electric/postgres/extension/schema_cache.ex
- e2e/tests/04.01_electric_api_returns_migrations.lux
At least with this change in place, I can no longer reproduce the error. Whereas before it would take me 2-3 runs to see it happen.
FIxes VAX-980.
> fix(electric): Fix the {:error, :relation_missing} error that regularly causes E2E tests to fail on CI

- .changeset/brave-ways-hide.md
- examples/starter/template/backend/startCompose.js
- examples/starter/template/db/connect.js
- examples/starter/template/db/util.js
- examples/starter/template/util/util.js
I've defined a utility function to run `docker compose` without shelljs, and used that for both `backend/startCompose.js` and `db/connect.js`.
The benefit is that we get output coloring back.
The drawback is inability to capture the output and inspect it for error messages. But the current code that's supposed to find the port reuse error in the output already does not work as expected on Linux because the error message printed there is `address already in use`.
> fix(starter): [VAX-1187] Modify db:psql to connect to PG via Docker container

- .changeset/famous-cars-agree.md
- clients/typescript/src/config/index.ts
- clients/typescript/src/satellite/config.ts
- clients/typescript/src/satellite/error.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/src/util/types.ts
- clients/typescript/test/satellite/process.test.ts
Some errors would trigger a reconnect loop on the server. This patch modifies error handling for preventing the client from reconnecting in a loop on FATAL errors.
Initially, we thought about DROPping the database when FATAL errors occur, but I've decided not to do that as part of this patch. The main reason is that FATAL errors should not occur in production if not because of a bug or re-deploying the backend database without refreshing the client code. In both cases, using some recovery tool is a more sensible way of addressing any potential issues -- which we're currently working on.
Meanwhile, we point the user to the logs for learning how to address the issue and raise that a recovery tool is underway.
This patch additionally exposes the backoff configuration to the application …
> fix(satellite): clients overload the server on fatal errors 

- .changeset/ninety-lions-kick.md
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/functions/electrify.sql.eex
- components/electric/lib/electric/postgres/extension/functions/validate_table_column_defaults.sql.eex
- components/electric/lib/electric/postgres/extension/functions/validate_table_column_types.sql.eex
- components/electric/lib/electric/postgres/extension/migrations/20231016141000_convert_function_to_procedure.ex
- components/electric/test/electric/postgres/extension/electrify_test.exs
- components/electric/test/electric/postgres/extension_test.exs
- components/electric/test/electric/replication/shapes/shape_request_test.exs
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/support/extension_case.ex
- components/electric/test/support/postgres_test_connection.ex
- e2e/init.sql
- e2e/tests/03.04_node_satellite_correctly_updates_serialization_caches.lux
- e2e/tests/03.05_fresh_node_satellite_receives_all_migrations_during_initial_sync.lux
- e2e/tests/03.11_node_satellite_compensations_work.lux
- e2e/tests/03.13_node_satellite_can_sync_timestamps.lux
- e2e/tests/03.14_node_satellite_can_sync_dates_and_times.lux
- e2e/tests/03.15_node_satellite_can_sync_booleans.lux
- e2e/tests/_shared.luxinc
> chore(electric): Reject tables that have columns with DEFAULT expressions

- .changeset/popular-years-live.md
- clients/typescript/package.json
- pnpm-lock.yaml
There was a bug in capacitor-community/sqlite that prevented our driver working on Android, this is fixed in the latest version. This sets the min version to that current published version.
> chore(DAL): Bump capacitor-community/sqlite version to enable Android support

- .changeset/funny-pianos-hang.md
- components/electric/lib/electric/postgres/extension/migrations/20230921161418_proxy_compatibility.ex
Hard to test without using docker images and the reproduction strategy in VAX-1245, have created an issue to track the need for a test of this migration path: https://linear.app/electric-sql/issue/VAX-1248/e2e-test-to-validate-upgrade-path-from-release-to-release
> fix(electric): New extension migrations fail to apply on top of Electric v0.6.4 schema

- .changeset/chilled-cameras-swim.md
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
`_performSnapshot()` must be executed serially. All calls to are protected with a mutex and we have an assertion on the function to ensure we enforce serial execution. However, sometimes we'd still see the assertion fail.
We are not setting properly the `performingSnapshot` variable when exceptions occur in `_performSnapshot()`. Although this probably constitutes a bug, it happens. The exceptions being thrown might also be swallowed sometimes, which made more difficult to track the error (and potentially still hiding other error).
> bug(satellite): potential race condition in _performSnapshot()

- clients/typescript/src/satellite/process.ts
- clients/typescript/src/util/relations.ts
- clients/typescript/test/satellite/common.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/satellite/serialization.test.ts
This tests the behavior of the `getColumnType` function which uses the DbSchema Postgres types and fallbacks to the type name in the Relation.
Bools are inferred as INTEGER from SQLite, but Satellite encodes them in a special way, not like integers.
There is also a small bugfix in the tests dbDescription, which doesn't affect the test suite nor the new test.
> Add test to verify pg types are used correctly when serializing

- .changeset/shiny-steaks-raise.md
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/test/satellite/registry.test.ts
When the satellite process fails (local state is invalid or out of date, invalid migrations, etc...), if the app cleans up the state and retries again (without a browser refresh), it currently will keep failing, because the `startingPromise` is being cached and not released when the promise rejects.
> bug(satellite): Cleanup startingPromise in registry when the Satellite process fails to start

- components/electric/Makefile
This is an idiom in the Docker community that allows consumers of the image to follow all versions of an image up until the next major release.
> chore(electric): Tag Electric's Docker images with a minor version

- examples/expo/backend/compose/.envrc
- examples/expo/backend/compose/docker-compose.yaml
- examples/expo/backend/startCompose.js
- examples/expo/backend/startElectric.js
- examples/expo/builder.js
- examples/expo/change-ports.js
- examples/expo/check-electric-is-running.js
- examples/expo/db/connect.js
- examples/expo/db/migrate.js
- examples/expo/db/migrations/01-create_items_table.sql
- examples/expo/db/util.js
- examples/expo/package.json
- examples/expo/util/util.js
- examples/expo/yarn.lock
I have verified that the basic instructions from README work. I couldn't verify whether any of the `yarn start`, `yarn start:android` or `yarn start:ios` still work.
@samwillis @thruflo can any one of you verify that the those commands still work?
Testing notes:
* git checkout the `examples/expo` branch
* modify `ELECTRIC_IMAGE` in `examples/expo/backend/compose/.envrc` to use `electric:local-build`
* `cd` to the project root
* `pnpm install`
* `cd clients/typescript; pnpm build; yalc publish`
* `cd ../../generator; pnpm build; yalc publish`
* `cd ../components/electric; make docker-build`
* `cd ../../examples/expo`
* `yalc add electric-sql @electric-sql/prisma-generator`
* `yarn`
* proceed with the instructions from README
> chore(examples): Update examples/expo with the new starter template

- .changeset/curvy-bobcats-walk.md
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/src/util/types.ts
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/common.ts
- clients/typescript/test/satellite/process.test.ts
Type check events emitted by the client. The consequence is that client no longer extends the eventEmitter, which shouldn't from the start.
Additionally, I added a shutdown mode to satellite.stop that clears event handlers assigned to the client. Not that it was a great harm because the client is scoped to the satellite instance. This allows to tick one more checkbox in #243
> chore(satellite): VAX-1208: improve client events type safety

- .changeset/neat-pens-raise.md
- clients/typescript/src/client/conversions/input.ts
- clients/typescript/src/client/conversions/sqlite.ts
- clients/typescript/test/client/conversions/input.test.ts
This PR fixes the bug reported by Kyle Mathews on Discord: https://discord.com/channels/933657521581858818/1079688869852753981/1169710877201674300
> Possible bug in 0.7. Upgraded and changed column type to boolean now my node.js liveMany query is failing with SQLite error that it can't bind to the type past in. In the better-sqlite adapter, if I log out queries and args passed to the query function then I see a "true" is being passed in which presumably should be 1. If I try to change the query back to use 1, I get a zod error (as I'd expect).
The problem came from the fact that we were only transforming date objects to SQLite strings but not the other values that were added later (booleans, floats, etc.).
> fix (DAL): transform all data types in input structures

- clients/typescript/src/config/index.ts
- clients/typescript/src/satellite/config.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/test/config/config.test.ts
This PR adds an option to electrify to configure the timeout for subscriptions as requested in https://github.com/electric-sql/electric/issues/605
> feat (client): configurable subscription timeout

- .changeset/witty-bears-shake.md
- clients/typescript/src/migrators/triggers.ts
- clients/typescript/test/migrators/triggers.test.ts
This PR modifies the trigger generation code to quote namespaces, table names, and column names.
This is needed because a namespace, table, or column could be named after a reserved keyword which leads to errors.
> fix (client): quote namespaces, table names, and column names in triggers

- components/electric/Makefile
- components/electric/dev/compose.yaml
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/schema_loader/epgsql.ex
- components/electric/lib/electric/replication/connectors.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/postgres_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/replication/postgres/logical_replication_producer_test.exs
- components/electric/test/support/extension_case.ex
Among a bunch of minor cleanups this change also removes the operator class for the `electric.tag` type. See the commit messsage for more info.
> chore(electric): Cleanups in code that deals with Postgres connections

- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/electric_tag_type_and_operators.sql
_Note: I've extracted this commit from https://github.com/electric-sql/electric/pull/626 to preserve the explanation below in the commit history._
Only a superuser can create an operator class but we're moving away from the superuser requirement for Electric.
An operator class is used in the following situations:
* an index is created on a column that has a user-defined type with custom operators defined for it
* values of the user-defined type appear in the ORDER BY clause
* values of the user-defined type are used in DISTINCT or GROUP BY clauses
I haven't been able to conduct an exhaustive audit of the code to confirm that we don't use the electric.tag type in those contexts. So I'm proposing we merge this change into main and see if that causes any issues in how Electric works.
> chore(electric): Remove the operator class for the `electric.tag` type

- clients/typescript/src/satellite/config.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/registry.ts
Log the SQLite version that is running on the client.
I feel it could end up being useful, given how there could be features/bugs on different versions of SQLite that run on the multiple supported adapters.
> client: Log SQLite version when starting

- components/electric/lib/electric/postgres/proxy/query_analyser.ex
- components/electric/test/electric/postgres/proxy/injector_test.exs
- components/electric/test/electric/postgres/proxy/query_analyser_test.exs
and other sundry table maintainance actions that don't affect table structure
fixes #652
> fix(electric): Allow creation of triggers on electrified tables

- docs/reference/roadmap.md
Update the docs to document the limitation that shapes must include all tables that can be reached by following FKs transitively.
> chore (docs): document FK limitation on shapes

- .changeset/quiet-otters-film.md
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/test/cli/migrations/migrate.test.ts
This PR modifies the generator to capitalise the first letter of model names in the generated Prisma schema.
We no longer turn snake_cased model names into PascalCase because this may lead to additional name clashes.
We also let Prisma turn PG table names such as `_foo` into valid model names like `foo`.
> fix (generator): capitalise model names

- .changeset/fluffy-hotels-push.md
- clients/typescript/package.json
- examples/beer-stars/package.json
- examples/beer-stars/yarn.lock
- examples/ionic-demo/package-lock.json
- examples/ionic-demo/package.json
- examples/linearlite/package-lock.json
- examples/linearlite/package.json
- examples/starter/template/package.json
- examples/web-wa-sqlite/package.json
- examples/web-wa-sqlite/yarn.lock
- pnpm-lock.yaml
Upgrades the ts-client, the starter, and the examples to use wa-sqlite version ^0.9.8 in order to include a critical bug fix released in v0.9.8.
> chore (client): upgrade version of wa-sqlite

- clients/typescript/src/cli/migrations/migrate.ts
This PR introduces the escapePathForString function to ensure correct path handling on Windows in our Prisma schema setup. Paths for provider and output are now escaped appropriately, resolving potential issues with backslashes on Windows systems.
Fixes #535
> fix: Update npx electric-sql generate to support Windows path format

- components/electric/lib/electric/postgres/schema/update.ex
This looks more like leftover debug info. Definitely shouldn't be an info-level log.
> chore(electric): Remove misleading log entry

- .changeset/brave-rules-walk.md
- clients/typescript/src/drivers/wa-sqlite/database.ts
This PR extends the critical section of our `exec` method for wa-sqlite which fixes #682.
The mutex now wraps all wa-sqlite calls to avoid any bad interleavings.
> fix (client): extend wa-sqlite's critical section to avoid bad interleavings

- .changeset/itchy-carrots-invite.md
- clients/typescript/src/_generated/protocol/satellite.ts
- clients/typescript/src/migrators/triggers.ts
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/util/types.ts
- components/electric/lib/electric/postgres/shadow_table_transformation.ex
- components/electric/lib/electric/replication/changes.ex
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/lib/electric/satellite/protobuf.ex
- components/electric/lib/electric/satellite/protobuf_messages.ex
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/lib/satellite/protocol_helpers.ex
- e2e/tests/05.05_compensations_within_same_tx_are_fine.lux
- protocol/satellite.proto
For permissions etc we need to always have the `OLD` values available, so for clarity don't send out SatOpUpdate with no old_data values
> chore(electric,client): Create new protocol op to represent a compensation

- components/electric/lib/electric/postgres/extension/schema_cache.ex
As a reminder, we have to have this internal schema in order for Electric to be able to send writes to `electric.acknowledged_client_lsn` over the Electric->PG logical replication connection.
> fix(electric): Preload internal schema in SchemaCache before looking up an internal relation

- .changeset/few-apples-buy.md
- clients/typescript/src/drivers/expo-sqlite/adapter.ts
- clients/typescript/src/drivers/generic/adapter.ts
- clients/typescript/src/drivers/generic/index.ts
- clients/typescript/src/drivers/wa-sqlite/adapter.ts
- clients/typescript/src/util/statements.ts
This PR splits the generic database adapter into two separate ones, one for serial execution of SQL queries and one for batched execution of SQL queries.
> chore (client): provide generic DB adapters for serial and batch execution of SQL

- clients/typescript/src/satellite/oplog.ts
- clients/typescript/test/migrators/triggers.test.ts
- clients/typescript/test/satellite/common.ts
- clients/typescript/test/satellite/merge.test.ts
In addition to the tests, the following logic is removed because at the oplog level, the Record values cannot be BigInt, as the oplog trigger serializes those values as string. Is the `deserialize` who checks the postgres type to turn it into the correct JS object.
Leaving the type check there might cause confusion in the future.
```js
if (typeof value === 'bigint') {
return value.toString()
}
```
> tests(client): Include tests for bigint support in the oplog triggers and the merge logic 

- .changeset/moody-carpets-allow.md
- clients/typescript/src/satellite/client.ts
- clients/typescript/test/satellite/serialization.test.ts
- e2e/tests/03.19_node_satellite_can_sync_enums.lux
- generator/src/functions/tableDescriptionWriters/writeTableSchemas.ts
This PR adds support for enumerations by:
- modifying the generator to store enumeration types as "TEXT" type in the generated client
- modifying satellite to serialise/deserialise enumerations as text
- since enumeration types are unknown to Satellite it serialises/deserialises them as text
> feat (DAL): support for enumerations

- .changeset/nine-boats-burn.md
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
This PR fixes the race condition described in #426.
The problem was that `process.subscribe` was creating a promise, storing it, making an async call, fetching the promise and returning it. But, depending on the order in which messages are received from Electric, the async call may resolve after the subscription was already delivered and hence the promise had already been deleted. The fix consists of storing the promise in a local variable inside `process.subscribe` such that it doesn't need to fetch the promise after the async call.
> fix (client): fix race condition in process.subscribe that made the client crash

- .changeset/brave-colts-change.md
- clients/typescript/src/client/model/client.ts
- clients/typescript/src/electric/index.ts
- clients/typescript/src/electric/namespace.ts
- clients/typescript/src/notifiers/event.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/test/client/model/shapes.test.ts
- clients/typescript/test/client/notifications.test.ts
- clients/typescript/test/frameworks/react.test.tsx
- clients/typescript/test/satellite/common.ts
This PR addresses the first task of #243.
As suggested, the `ElectricNamespace` (and thus also the `ElectricClient` as it extends the namespace) now exposes a `close` method that can be called by the user to dispose all resources used by the Electric client. This `close` method calls the `stop` on the global registry such that it also stops the client's satellite process.
> chore (client): expose a close method on the ElectricNamespace to dispose its resources

- .changeset/tasty-lizards-boil.md
- generator/src/functions/writeSingleFileImportStatements.ts
This PR fixes #707 by explicitly importing types using `import type` instead of just `import`.
> fix (generator): let generated client import types using TypeScript's import type

- .changeset/twelve-pigs-give.md
- clients/typescript/src/electric/namespace.ts
- clients/typescript/src/frameworks/react/hooks/useConnectivityState.ts
- clients/typescript/src/frameworks/react/hooks/useLiveQuery.ts
- clients/typescript/src/notifiers/event.ts
- clients/typescript/src/notifiers/index.ts
- clients/typescript/src/notifiers/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/client/notifications.test.ts
- clients/typescript/test/notifiers/event.test.ts
- clients/typescript/test/satellite/common.ts
This PR refactors the various subscribe methods provided by the event notifier. For every listener that was being subscribed, the event notifier would generate a random key, store the listener under that key, and return that key. To unsubscribe, the user had to pass that key to the corresponding unsubscribe method which would lookup the listener and then unsubscribe it from the underlying event emitter. Storing the listener under a key is not needed and is a bit redundant as the underlying event emitter already stores them.
This PR modified the event notifier such that it does not keep track of registered callbacks but instead returns an unsubscribe function from the subscribe methods. The unsubscribe function closes over the callback that needs to be unregistered from the underlying …
> chore (client): refactoring subscribe methods of the event notifier

- .changeset/cool-bugs-clean.md
- clients/typescript/src/cli/migrations/migrate.ts
This PR escapes also the output path for the Prisma client generator in the intermediate Prisma schema when running on Windows.
> fix (generator): escape client generator path on Windows

- .changeset/violet-ladybugs-sip.md
- components/electric/lib/electric/plug/status.ex
- components/electric/lib/electric/replication/postgres_manager.ex
- components/electric/test/support/postgres_test_connection.ex
- e2e/tests/_shared.luxinc
```
14:57:31.823 pid=<0.721.0> [info] Starting replication from postgres_1
14:57:31.823 pid=<0.721.0> [info] Connection settings: %{database: ~c"electric", host: ~c"localhost", password: ~c"******", port: 54321, replication: ~c"database", ssl: false, username: ~c"postgres"}
14:57:31.842 pid=<0.721.0> [debug] Elixir.Electric.Replication.Postgres.Client: CREATE_REPLICATION_SLOT "electric_replication_out_electric" LOGICAL pgoutput NOEXPORT_SNAPSHOT
14:57:31.846 pid=<0.719.0> [debug] Starting SchemaLoader pg connection: [write_to_pg_mode: :direct_writes, origin: "postgres_1", producer: Electric.Replication.Postgres.LogicalReplicationProducer, connection: [host: ~c"localhost", port: 54321, database: ~c"electric", username: ~c"postgres", password: ~c"password", replication: ~c"database", ssl: …
```
> chore(electric): Improve error handling of the case when another Electric is already connected to the same DB

- .changeset/weak-years-explode.md
- generator/src/functions/contentWriters/writeOutputObjectType.ts
- generator/src/functions/writeSingleFileArgTypeStatements.ts
This PR fixes the problem where the generated client may contain type errors for models containing relations.
This is a known problem with Zod and Prisma and is described here: https://github.com/chrishoermann/zod-prisma-types/issues/98. That issue also proposes a solution with a dirty type cast: https://github.com/chrishoermann/zod-prisma-types/issues/98#issuecomment-1800112669 which is implemented in this PR.
This PR removes the need for pinning the version of Zod (https://github.com/electric-sql/electric/pull/700).
To test this fix, you will need a schema containing at least one FK relation and make sure to modify the dependency to your generator to point to the modified generator (e.g. `npm pack` the generator and use a dependency to the packed file).
> fix (generator): fix type issue on schemas containing relations

- .buildkite/docker-image.yml
- .changeset/gorgeous-knives-drum.md
- .changeset/real-walls-perform.md
- components/electric/Makefile
- components/electric/lib/electric/application.ex
I've added a log entry that output the server version and the configured write mode, like so:
```
$ docker run --rm -t -e AUTH_MODE=insecure -e DATABASE_URL=postgres://postgres:password@postgres/electric -e ELECTRIC_WRITE_TO_PG_MODE=direct_writes -e PG_PROXY_PASSWORD=password electric:local-build
10:50:11.035 pid=<0.2308.0> [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
10:50:11.036 pid=<0.2451.0> [info] Starting ElectricSQL 0.8.0-10-g7e1a0e0 in direct_writes mode.
```
This will make it easier for people to identify the commit which their local `canary` image was built from.
> chore(electric): Publish canary images to Docker Hub on every push to main

- .changeset/rare-avocados-train.md
- clients/typescript/src/cli/migrations/migrate.ts
- examples/starter/template/db/migrate.js
- examples/starter/template/db/util.js
- examples/starter/template/package.json
- examples/web-wa-sqlite/db/migrate.js
- examples/web-wa-sqlite/db/util.js
- examples/web-wa-sqlite/package.json
- examples/web-wa-sqlite/yarn.lock
Included fixes:
- Prefix zod type generator provider with node for exe on windows so that its run with node
- Conditionally escape quotes in docker command on windows, this has to be conditional as it breaks Posix
- Execute the pg-migrations command with npx not yarn
The fixes to the starter are also applied to the web-wa-sqlite example.
---
```sh
git clone git@github.com:electric-sql/electric.git && cd electric
git checkout samwillis/windows-fix
pnpm install
cd clients/typescript
pnpm build && pnpm pack
cd ../../examples/web-wa-sqlite/
npm uninstall electric-sql
npm uninstall @prisma/client @electric-sql/prisma-generator prisma  # These are no longer required but we haven't updated the example yet 
npm install ../../clients/typescript/electric-sql-0.8.1.tgz
npm backend:up
npm db:migrate …
```
> fix(client) Various fixes to run generator and starter scripts on windows

- .changeset/hip-ducks-behave.md
- clients/typescript/src/cli/index.ts
- clients/typescript/src/cli/tunnel/handler.ts
- clients/typescript/src/cli/tunnel/index.ts
- clients/typescript/src/cli/tunnel/tunnel.ts
@alco this builds on your WIP [alco/pg-proxy-over-websocket](https://github.com/electric-sql/electric/tree/alco/pg-proxy-over-websocket) branch 
To connect to the service, and create a local proxy tunnel:
```sh
npx electric-sql proxy-tunnel --service http://something --local-port 65431
```
then to run migrations:
```sh
yarn run -s pg-migrations apply --database postgres://postgres:proxy_password@localhost:65431 --directory ./db/migrations
```
and the generator:
```sh
npx electric-sql generate --service http://localhost:5133 --proxy postgresql://prisma:proxy_password@localhost:65431/electric
```
> feat(client): New "npx electric-sql proxy-tunnel" command

- .changeset/thirty-pots-wash.md
- generator/src/functions/writeSingleFileImportStatements.ts
When you have `"moduleResolution": "nodenext"` in `tsconfig.json` all imports need to have the full path including a `.js` extension, even if to a `.ts` file.
This is backwards compatibly with all typescript settings, its always possible to import a `.ts` or `.d.ts` when the import has a `.js` extension.
> chore(generator) Change generator to add .js extention to imports for nodenext compatibility

- .changeset/quick-rats-end.md
- clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
- clients/typescript/src/drivers/capacitor-sqlite/database.ts
- clients/typescript/src/drivers/capacitor-sqlite/mock.ts
- clients/typescript/src/drivers/capacitor-sqlite/test.ts
- clients/typescript/test/drivers/capacitor-sqlite.test.ts
[EDIT] Following @kevin-dp 's work on generic adapters, this PR has been repurposed. The concurrency issue is now taken care of by implementing BatchDatabaseAdapter.
This PR fixes a concurrency issue with the capacitor-sqlite database adapter. The mutex was previously only acquired in the `transaction` method, causing concurrency conflicts when calling `runInTransaction`.
Comments have been added to other public methods of the adapter in order to clarify the intended behaviour of each method. In effect, `run`, `execute` and `query` have ambiguous meanings depending on the layer (electric driver -> capacitor-sqlite -> native SQLite). It is therefore important to make sure that the methods as implemented correspond to what is expected of `electric`'s API.
> capacitor-sqlite runInTransaction now takes the lock.

- clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
- clients/typescript/src/drivers/capacitor-sqlite/mock.ts
* Removed todo comment RE return type of cap-sqlite `query`, the result type is an array of objects as expected.
* Adapted `mock.ts` to the new requirements
My tests pass, but am getting 2 other failed tests which are probably tied to env/update issues?
`Error: Cannot find module '/Users/gregoriozanon/Documents/Dev/electric/clients/typescript/node_modules/@electric-sql/prisma-generator/dist/generator.js'. Please verify that the package.json has a valid "main" entry`
Makes those tests fail:
```
✖ test/cli/migrations/handler.test.ts exited with a non-zero exit code: 1
✖ test/cli/migrations/migrate.test.ts exited with a non-zero exit code: 1
```
> Adapt cap-sqlite mock.ts to new generic adapter

- .buildkite/docker-image.yml
This is a temporary change that needs to be in main to enable testing of Buildkite's tag-triggered build behaviour.
> (tmp) Do not publish to Docker Hub from Buildkite. Only echo the versions

- .changeset/light-pants-greet.md
- clients/typescript/src/migrators/triggers.ts
- clients/typescript/test/migrators/builder.test.ts
This PR solves an issue that was introduced when adding type support.
We were reading the column types from the wrong table when generating compensation triggers for foreign keys.
> fix(client): fix generation of compensation triggers

- e2e/README.md
- e2e/common.mk
- e2e/tests/04.02_prisma_introspection_generates_correct_schema.lux
I noticed that both locally on a fresh run and on CI, the ```04.02_prisma_introspection_generates_correct_schema.lux``` test was occasionally either throwing a warning about the timeout being close to max or timing out.
It seems to be the only test flaking consistently so I figured it makes sense to increase the timeout slightly to make the e2e results more reliable.
I've also updated the README with some info I needed as I set it up to run the e2e locally.
> fix(e2e): Fix flaky prisma E2E that times out every few runs

- e2e/common.mk
- e2e/tests/04.02_prisma_introspection_generates_correct_schema.lux
- e2e/tests/04.03_prisma_migration_version_captured.lux
- e2e/tests/_satellite_macros.luxinc
- e2e/tests/_shared.luxinc
I've noticed the e2e running satellite is a bit flaky because the docker startup occasionally times out.
We have explicitly specified a larger timeout for most docker startup commands so this should be more consistent and reduce flakiness.
Example of flake logs for reference:
```
2024-01-08T09:28:00.4851831Z test case         : tests/03.01_node_satellite_loads_local_migrations.lux
2024-01-08T09:28:11.5151352Z progress          : (()..:...:.)()((...:...:..):...:.:.:.26????26)23C..:...:.(stop development environment..:.(.:.:.:.:.:.:.:.:.:.:.:.:...:.:...))
2024-01-08T09:28:11.5167772Z result            : FAIL at line 23:26 in shell satellite_1
2024-01-08T09:28:11.5168696Z expected=
2024-01-08T09:28:11.5169046Z 	>
2024-01-08T09:28:11.5177569Z actual match_timeout
2024-01-08T09:28:11.5178463Z …
```
> fix(e2e): increase base timeout multiplier on CI to reduce flakiness

- components/electric/lib/electric/satellite/serialization.ex
- components/electric/lib/electric/utils.ex
- components/electric/test/electric/satellite/ws_validations_test.exs
The idea behind this change is to make sure every pattern-matching failure logs the offending value.
Previously, we could get an error looking like this
** (MatchError) Patter match failed: true = false
> chore(electric): Improve error logging in column value validation

- docs/integrations/frontend/react.md
Fixed a typographical error in the 'Query dependencies' section of the react.md file.
> docs: correct typo in react.md

- .changeset/slow-lies-boil.md
- clients/typescript/src/auth/secure/index.ts
- components/electric/config/runtime.exs
- components/electric/lib/electric.ex
- components/electric/lib/electric/satellite/auth/insecure.ex
- components/electric/lib/electric/satellite/auth/jwt_util.ex
- components/electric/lib/electric/satellite/auth/secure.ex
- components/electric/test/electric/satellite/auth/secure_test.exs
> chore(electric): Relax JWT timestamp validation by introducing the idea of "clock drift"

- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/extension/migrations/20240110110200_drop_unused_functions.ex
- components/electric/priv/sql_function_templates/__constraint_validation_enabled.sql.eex
- components/electric/priv/sql_function_templates/electrify.sql.eex
- components/electric/priv/sql_function_templates/electrify/__validate_table_column_defaults.sql.eex
- components/electric/priv/sql_function_templates/electrify/__validate_table_column_types.sql.eex
- components/electric/priv/sql_function_templates/electrify/__validate_table_constraints.sql.eex
- components/electric/test/electric/postgres/extension_test.exs
- e2e/tests/01.03_postgres_writes_propagate_to_electric.lux
- e2e/tests/04.02_prisma_introspection_generates_correct_schema.lux
> chore(electric): Reject electrification of tables that have no PRIMARY KEY or have unsupported constraints

- .changeset/modern-shrimps-retire.md
- generator/src/functions/writeSingleFileImportStatements.ts
Revert "chore(generator) Change generator to add .js extention to imports for nodenext compatibility (#753)"
This reverts commit 22652fb3e7616bc5d48f445cdad2d77a0c99c9a8.
> fix(generator) Revert #753 as it breaks for some bundlers - will fix this bug in the CLI

- .changeset/silent-pillows-jog.md
- clients/typescript/src/client/model/client.ts
- clients/typescript/src/client/model/table.ts
- clients/typescript/test/client/conversions/sqlite.test.ts
- clients/typescript/test/client/model/table.errors.test.ts
- clients/typescript/test/client/model/table.test.ts
- clients/typescript/test/frameworks/react.test.tsx
- clients/typescript/test/migrators/builder.test.ts
- docs/api/clients/typescript.md
- docs/integrations/drivers/other/generic.md
- docs/integrations/frontend/react.md
- docs/quickstart/index.md
- docs/usage/data-access/queries.md
- e2e/satellite_client/src/client.ts
Having split the raw APIs to read-only safe ones and an unsafe one, I've also renamed them:
- `raw` with read-only checks to `rawQuery`
- `liveRaw` to `liveRawQuery`
- `raw` without checks to `unsafeExec`
I've updated all relevant docs I could find as well.
Some exampels (beer-stars, introduction, and linearlite) will be using the old versions of the API as they have their electric-sql version fixed to 0.7.0, so when it's updated those PRs should take care of also fixing the deprecated APIs.
> feat(client): Add new names for safe and unsafe raw APIs and deprecate old ones

- .changeset/nasty-rockets-lick.md
- clients/typescript/src/drivers/wa-sqlite/database.ts
Currently `ElectricDatabase.init` requires a second argument that is the path to the directory where the wa-sqlite wasm file is located. This makes it impossible to have a bundler automatically find and include the wasm in your built apps bundle with a cache busting filename.
Internally wa-sqlite uses the `new URL('wa-sqlite-async.wasm', import.meta.url)` pattern described here https://vitejs.dev/guide/assets#new-url-url-import-meta-url that is supported by (all?) bundlers. This is the default if you do not pass a `locateFile` function to `SQLiteAsyncESMFactory`.
This PR makes our second argument optional allowing the default behaviour of wa-sqlite. Additionally, it allows parsing a function - rather than a string - to the second argument, which is passed through to wa-sqlite.
This …
> chore(client): Make the `sqliteDistPath ` argument to `ElectricDatabase.init` optional, enabling wasm bundling

- clients/typescript/src/cli/config.ts
There is a small bug in the CLI options generation. The argName is not turned into lowercase when the option starts with ELECTRIC_
` npx electric-sql start --help`
@samwillis Related to the new CLI, when looking into adding support for it in `electric_dart` we had some questions.
Should there be a `docker compose pull <image>` before starting the docker? The CLI already uses the correct docker image, but it might be important to pull in case the user was using image tag `0.x` (`0.x.0` under the hood) and later there is a patch in the service, so the user might not pull `0.x.1`
The generate command runs the start command when fetching migrations, but when stopping the service, it uses the flag `remove: true`. Why is that? Wouldn't that cause data loss to the user? It would be deleting the …
> fix(client_cli) Fix argName when option starts with ELECTRIC_

- clients/typescript/src/cli/config-options.ts
- clients/typescript/src/cli/config.ts
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/src/cli/utils.ts
A couple of minor issues I found:
1. ~~Use the prisma user in the db proxy url, otherwise non elecrified tables are generated.~~ Bad call, the prisma user is correctly being used for the introspection. The proxy url doesn't always need to use the prisma user. We can however log the correct proxy url used when generating the client, because the one in the config differs the one used for the introspection.
https://github.com/electric-sql/electric/blob/7fbf292ef1bcb07a71fd4e2a528d2cda965ac5ce/clients/typescript/src/cli/migrations/migrate.ts#L73
https://github.com/electric-sql/electric/blob/7fbf292ef1bcb07a71fd4e2a528d2cda965ac5ce/clients/typescript/src/cli/migrations/migrate.ts#L303-L309
2. Handle ssl mode when building the db url, so that when running locally, the db and proxy urls are …
> fix(client_cli): Proxy fixes 

- docs/integrations/frontend/flutter.md
Hello! We just noticed the new docs for the Flutter integration. Thanks for the shout-out!
This PR fixes the http link to the repo and adds the link to the package in the NPM equivalent for Dart/Flutter, https://pub.dev
> Update flutter integration docs

- clients/typescript/package.json
- clients/typescript/src/cli/config-options.ts
- clients/typescript/src/cli/config.ts
- clients/typescript/src/cli/docker-commands/command-psql.ts
- clients/typescript/src/cli/docker-commands/command-start.ts
- clients/typescript/src/cli/docker-commands/command-stop.ts
- clients/typescript/src/cli/docker-commands/docker-utils.ts
- clients/typescript/src/cli/docker-commands/docker/compose-base.yaml
- clients/typescript/src/cli/docker-commands/docker/compose.yaml
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/src/cli/utils.ts
- clients/typescript/test/cli/migrations/migrate.test.ts
- pnpm-lock.yaml
Fixes:
- `generate --with-migrations` now runs in a ephemeral container on random ports and random container name
- #825 Correctly handles ssl for db urls
- Allow the pg proxy to be on an alternative host to the sync service (required for the proxy tunnel)
- configurable container name
- correctly handles `PG_PROXY_PORT` with `http` or `http:123` value
> fix(client) Fix bugs in the CLI

- .changeset/happy-emus-push.md
- clients/typescript/src/drivers/capacitor-sqlite/index.ts
This PR fixes the default socket that is used by the capacitor driver to be the `WebSocketWeb` socket.
Note that the cordova driver is still using `MockSocket` as the default.
Not sure what should be the default for the Cordova driver? And whether it's worth spending any time in this since it is not used.
> fix (client): use WebSocketWeb as the default socket for capacitor

- .changeset/rare-guests-kick.md
- clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
- clients/typescript/src/drivers/capacitor-sqlite/database.ts
- clients/typescript/src/drivers/capacitor-sqlite/mock.ts
- clients/typescript/src/drivers/expo-sqlite/adapter.ts
- clients/typescript/src/drivers/generic/adapter.ts
- clients/typescript/src/drivers/wa-sqlite/adapter.ts
This PR improves the generic database adapter to require `_query` and `_run` methods instead of an `exec` method.
> chore (client): improved interface for the generic adapter

- .changeset/five-beds-taste.md
- clients/typescript/src/cli/docker-commands/command-status.ts
This ensures the status command correctly shows the containers for the current project.
> fix(client) Correctly pass the CONTAINER_NAME to the cli "status" command

- .changeset/weak-turtles-check.md
- clients/typescript/src/frameworks/react/hooks/useLiveQuery.ts
- clients/typescript/test/frameworks/react.test.tsx
The `useLiveQuery` React implementation had redundant calls to the adapter and some other redundant calls to subscribe/unsubscribe from changes.
I removed any unnecessary state and references to simplify the binding, and enhanced a couple of tests to ensure there are no redundant query calls.
> fix(client): Fix redundant query calls in React live query hook

- .changeset/gold-horses-crash.md
- clients/typescript/src/cli/config-options.ts
- clients/typescript/src/cli/config.ts
- clients/typescript/src/cli/utils.ts
This splits inferring config values from defaults.
This fixes VAX-1569 (#871), the bug was due to the proxy url being constructed from it's parts, but the parts were not inferred from command line args, only env vars.
> fix(cli) Split inferred values from default values - Fixes VAX-1569

- .changeset/stale-taxis-protect.md
- clients/typescript/src/cli/main.ts
> fix(cli) Silent dot-env warning when there are no .env files

- clients/typescript/src/cli/docker-commands/docker/compose-base.yaml
- clients/typescript/src/cli/docker-commands/docker/compose.yaml
Fixes VAX-1557.
Trying to run the `start` command was failing with an error from Docker Compose on my machine:
```
$ npx electric-sql start --with-postgres
Starting ElectricSQL sync service with PostgreSQL
Docker compose config: {
[...]
}
service ports services.electric.ports.[0] is missing a target port
```
I traced it to a bug in the latest version of Docker Compose which I had installed - https://github.com/docker/compose/issues/11378.
Now, the upstream issue is slated to be resolved in the next release. But to avoid relying on an upstream fix getting applied to people's installations of Docker Compose and to ensure a smooth onboarding experience for our users, I've created this workaround that moves all service-level definitions that include environment variable interpolation from …
> fix(cli): Move most of the electric service definition into compose.yaml

- examples/expo/package.json
This PR updates the `expo-sqlite` dependency in the expo example app to be `>= 11.7.0` which is the minimal version that is needed in order for `RETURNING` clauses to work on Android.
> chore (examples): update expo-sqlite dependency in expo example app

- .changeset/blue-snakes-jog.md
- components/electric/lib/electric/errors.ex
- components/electric/lib/electric/postgres/proxy/upstream_connection.ex
- components/electric/test/electric/postgres/proxy_test.exs
Fixes VAX-1553.
@magnetised I would appreciate any guidance on how to best test support for specific upstream messages in the proxy. Maybe we should also unit-test the SSL upgrade that I recently implemented there.
> fix(electric): Implement support for AuthenticationMD5Password upstream auth method

- examples/introduction/src/demos/local-first/instant.jsx
I think you meant to write "cloud-first" since this is the local- vs cloud-first intro.
> fix typo: "cloud-first" instead of "client-first"

- components/electric/lib/electric/replication/postgres_manager.ex
- components/electric/lib/electric/utils.ex
> fix(electric): Include Server Name Indication in database connection SSL options

- clients/typescript/src/cli/docker-commands/docker/compose-base.yaml
- components/electric/dev/compose.yaml
- e2e/services_templates.yaml
This PR makes two changes:
* remove `privileged: true` from services defined in several `compose.yaml` files
* use `SIGINT` as the default stop signal for the Electric service. This results in faster shutdown after pressing Ctrl-C or stopping all services with `docker compose stop/down`.
> chore(electric): Docker-related cleanups

- .changeset/shaggy-planes-bake.md
- components/electric/lib/electric/satellite/auth/jwt_util.ex
- components/electric/test/electric/satellite/auth/insecure_test.exs
> fix(electric): Support JWTs without a trailing dot in Insecure mode

- docs/usage/data-modelling/constraints.md
@balegas & @thruflo : This is my attempt at clarifying the limitations of adding not-null constrained columns, as per the Discord discussion.
I tried my best to make the text as short as possible without loosing out on details _why_ it isn't really supported.
> Clarify actual limitations on adding not-null constraints

- .changeset/hot-phones-wash.md
- clients/typescript/src/satellite/shapes/index.ts
- clients/typescript/src/satellite/shapes/manager.ts
- clients/typescript/test/satellite/process.test.ts
When a client reconnects to Electric and can't resume it resets its local state (i.e. unsubscribes all subscriptions) and starts from scratch. Currently, we unsubscribe subscription per subscription. For each subscription, we delete the contents of the shapes from the DB. However, this can lead to FK violations. e.g.:
- Table User
- Table Post has a FK to user
- Subscription 1 subscribes to user table
- Subscription 2 subscribes to post and user table
When clearing all subscriptions, if we first unsubscribe from subscription 1, we are deleting the contents of the user table and thereby violating any FKs that are in the post table.
This PR avoids this problem by clearing all subscriptions within a single database transaction that defers the foreign keys until the end of the transaction. …
> fix (client): clear all subscriptions from the DB in 1 transaction

- docs/integrations/drivers/other/generic.md
This PR updates the explanation on how to integrate new DB drivers in Electric.
While the old explanation is still valid, i extended this section to explain that the simplest option is to extend one of the two generic database adapters.
> chore (docs): update explanation on how to integrate new DB drivers

- .changeset/afraid-keys-begin.md
- clients/typescript/package.json
- clients/typescript/src/cli/migrations/migrate.ts
- pnpm-lock.yaml
This PR fixes an issue with the CLI's generate command and fixes missing schemas in the generated client (fixes VAX-1580).
Our typescript client uses Prisma v4 to introspect the Postgres DB and to generate the Prisma and Electric clients.
However, if a user project includes Prisma v5 (e.g. to manage migrations using Prisma), then the generator crashed with the following error:
```
Error: Command failed: node /home/alco/code/electric-sql/electric/examples/nextjs-electric/node_modules/electric-sql/node_modules/prisma/build/index.js generate --schema=".electric_migrations_tmp_oM5W7E/prisma/schema.prisma"
Error: (query-engine-node-api library)
Details: NodeAPIQueryEngineLibrary.dmmf is not a function
[Context: getDmmf]
Prisma CLI Version : 4.8.1
at ChildProcess.exithandler …
```
> fix (CLI): fix generator engine library issue

- components/electric/priv/sql_function_templates/electrify/__validate_table_constraints.sql.eex
The old implementation kept producing different orderings between runs:
1) test table electrification rejects columns with CHECK, UNIQUE or EXCLUDE constraints (Electric.Postgres.ExtensionTest)
test/electric/postgres/extension_test.exs:519
Assertion with == failed
left:  "Cannot electrify t1 [...]:\n  t1\n  \"Ts\"\n  uu"
right: "Cannot electrify t1 [...]:\n  \"Ts\"\n  t1\n  uu"
> fix(electric): Rewrite __validate_table_constraints() without array_agg()

- .changeset/chatty-lies-impress.md
- clients/typescript/src/cli/migrations/command-generate.ts
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/test/cli/migrations/migrate.test.ts
- docs/api/cli.md
As @alco pointed out, the expected behaviour of the `--debug` flag would be to always retain the temporary migrations folder for inspection and debugging regardless of whether the generation succeeds or not.
I've added a few more tests to cover this behaviour for all 4 paths (with/without debug, failure/success).
I've also added the flag to the documentation for the CLI `generate` command and added more info on what the flag does in the CLI help text.
> fix(cli): Make `--debug` flag for CLI `generate` command always maintain migrations folders

- .changeset/breezy-trees-own.md
- examples/starter/make-templates.js
- examples/starter/src/index.ts
It was unintentionally removed in https://github.com/electric-sql/electric/pull/676.
Fixes VAX-1591.
> fix(starter): Bring back the .gitignore template file

- .changeset/brave-dolls-count.md
- clients/typescript/package.json
- clients/typescript/src/drivers/expo-sqlite-next/adapter.ts
- clients/typescript/src/drivers/expo-sqlite-next/database.ts
- clients/typescript/src/drivers/expo-sqlite-next/index.ts
- clients/typescript/src/drivers/expo-sqlite-next/mock.ts
- clients/typescript/src/drivers/expo-sqlite-next/test.ts
- clients/typescript/src/drivers/index.ts
- clients/typescript/test/drivers/expo-next.test.ts
- docs/integrations/drivers/mobile/expo.md
- pnpm-lock.yaml
Adds the [expo-sqlite (next)](https://docs.expo.dev/versions/latest/sdk/sqlite-next/) driver on top of the regular one.
I can update the docs as well but I was unsure if we wanted it as a separate entry to the regular Expo one or if I should just add an additional section for using `next` instead of the regular one.
Also, is there a process/tooling in place for us to do a proper test for some of these drivers (e.g. spin up android/ios machines in CI and run basic e2e tests) to ensure they work?
> feat(client): Add expo-sqlite/next driver

- .changeset/funny-lions-provide.md
- components/electric/lib/electric/config.ex
- components/electric/lib/electric/satellite/auth.ex
- components/electric/lib/electric/satellite/auth/insecure.ex
- components/electric/lib/electric/satellite/auth/secure.ex
- components/electric/test/electric/config_test.exs
- components/electric/test/electric/satellite/auth/insecure_test.exs
Fixes VAX-1589.
I can configure Electric with AUTH_MODE=insecure and AUTH_JWT_ALG=RS256 and it'll run just fine. This is dangerous because 1) I forgot to configure the signing key, 2) it doesn't matter anyway because the token signatures won't be validated in the insecure mode.
This PR makes it so that if any secure auth settings are used together with AUTH_MODE=insecure, Electric will fail to start and will log an error.
> chore(electric): Make sure AUTH_MODE=secure when secure auth options are used

- .changeset/metal-bats-worry.md
- .changeset/tall-stingrays-change.md
- components/electric/lib/electric/satellite/auth/secure.ex
- components/electric/test/electric/satellite/auth/secure_test.exs
- components/electric/test/fixtures/keys/README.md
This PR adds validation for public keys and makes it possible to use base64-encoded symmetric keys.
Fixes VAX-1584:
Validating public keys at startup provides early feedback to the developer about misconfigured auth.
Fixes VAX-1583:
Pasting a key used for token signature verification verbatim into the AUTH_JWT_KEY configuration option is problematic for binary symmetric keys.
Online JWT tools, such as jwt.io and token.dev, take base64-encoded keys by default. So newcomers to Electric get confused when they try to use their base64-encoded key with it and see signature verification errors logged by Electric.
We can detect if the value configured for AUTH_JWT_KEY is base64-encoded since the encoding has a limited set of characters.
> feat(electric): Validate signing keys at startup

- .changeset/polite-insects-chew.md
- clients/typescript/src/notifiers/event.ts
- clients/typescript/src/notifiers/index.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/frameworks/react.test.tsx
- clients/typescript/test/frameworks/vuejs.test.ts
- clients/typescript/test/notifiers/event.test.ts
- clients/typescript/test/satellite/process.test.ts
- clients/typescript/test/util/subscribe.test.ts
Currently the event from `subscribeToDataChanges` only lists the table that has changed, along with the `rowid`s for oplog entries for local changes. This isn't sufficient to watch for a change of a specific row, and requires a full re-query in most cases.
This modifies the notifier to emit info about each row that has changes, along with where the change originated - local, remote, or "initial" for first sync of a shape.
@balegas could you take a look and see if this is a sensible way of doing this?
It is emiting the `record` and `type` ("inset", "update"...) for each row that's change, and I've also extracted the PK(s) for the row changed which makes it easy to then lookup the row.
Once we move to a multi tab/window/process model this could result in large amounts of data being pushed …
> feature(client) Modify client notifier to emit info about changed rows

- docs/deployment/supabase.md
Make the IPv4 notice more prominent on the Supabase page and mention the option of purchasing the IPv4 add-on.
Preview - https://deploy-preview-110--electric-sql-website.netlify.app/docs/deployment/supabase/
> chore(docs): Add more info to the Supabase IPv4 connectivity notice

- docs/integrations/drivers/mobile/react-native.md
- docs/integrations/drivers/server/node.md
- docs/integrations/drivers/web/wa-sqlite.md
In driver docs, some async query calls were not awaited - might look confusing.
> chore(docs): Update driver docs to use async call for `findMany` query

- docs/integrations/frontend/vue.md
Follow-up to https://github.com/electric-sql/electric/pull/961
Documentation follows similar pattern to the React bindings documentation. Subject to change as original PR will determine the defined API.
> chore(docs): Add documentation for the Vue bindings

- docs/api/cli.md
Follow-up to https://github.com/electric-sql/electric/pull/944.
> chore(docs): Document the updated behaviour of `generate --debug`

- .changeset/pink-books-obey.md
- examples/starter/package-lock.json
- examples/starter/package.json
The current version is broken (see https://github.com/electric-sql/electric/issues/982) because the template folders are not being included, this is a hotfix to make it work again.
Will see to adding some tests for this so it doesn't slip through.
> fix(starter): Include template folders in `create-electric-app` NPM package

- .changeset/brave-humans-own.md
- examples/starter/package.json
Turns out `pnpm pack` and `npm pack` read the `package.json` file inclusion globs differently.
This time tested with `npm publish --dry-run` and `npm pack` to ensure all relevant files are included.
> fix(starter): Actually include all template files in `create-electric-app` package

- docs/api/clients/typescript.md
- docs/integrations/frontend/react.md
- docs/usage/auth/token.md
Breaking change to the Auth APIs also removed the backwards compatibility for the token to have a `user_id` as claim instead of `sub.
https://github.com/electric-sql/electric/pull/828/files#diff-6f5e692c874649d2aee74958b2c1369a83d09ec9be84e60330f8eaf5ec4fc023R37-R43
```ts
export function decodeToken(token: string): JWTPayload & { sub: string } {
const decoded = decodeJwt(token)
if (typeof decoded.sub === 'undefined') {
throw new InvalidArgumentError('Token does not contain a sub claim')
}
return decoded as JWTPayload & { sub: string }
}
```
We also say "`sub` (formerly `user_id`)" everywhere in the docs - should we still keep that or remove it entirely and use just `sub` going forwards?
> chore(docs): Remove backwards compatibility claim for `user_id` in token claims

- docs/api/clients/typescript.md
- docs/deployment/concepts.md
- docs/deployment/supabase.md
- docs/integrations/drivers/web/wa-sqlite.md
- docs/integrations/frontend/react.md
- docs/integrations/frontend/vue.md
- docs/quickstart/index.md
- docs/usage/data-access/client.md
Doc examples still used an empty string as the wa-sqlite distribution path which is now optional with the new release.
Also added a small update to the Vue docs with the Auth API as I somehow missed that.
> chode(docs): Update docs to use optional wa-sqlite distribution path

- .github/workflows/components_electric_tests.yml
- .github/workflows/e2e.yml
- .github/workflows/satellite_proto.yml
Their usage makes it impossible to run actions for pull requests from forks.
> chore(ci): Drop the use of GitHub Actions variables

- .changeset/gorgeous-parents-flow.md
- components/electric/lib/electric/postgres/proxy/injector/shadow.ex
- components/electric/test/electric/postgres/proxy/injector/shadow_test.exs
- components/electric/test/support/injector_test/test_scenario.ex
A query with multiple statements expects multiple command complete messages with a single closing ReadyForQuery message. This fixes incorrect handling of that situation within the prisma shadow handler
Hopefully fixes #955 and #939
> fix(proxy): Correcly coalesce command complete messages

- examples/expo/README.md
We've started using npm for all our examples and including the package-lock.json as well, so doing this for consistency.
> chore(docs): Replace `yarn` with `npm` in the Expo demo README

- docs/integrations/frontend/vue.md
The [Vue docs](https://electric-sql.com/docs/integrations/frontend/vue) were using the `vue` syntax highlighting language, which is [not supported by Prism](https://prismjs.com/#supported-languages).
There's open issues to support SFC syntax (see https://github.com/PrismJS/prism/issues/1665) but until then using `html` syntax highlighting seems to do a relatively decent job as a workaround.
before and after pics:
> fix(docs): Fix Vue syntax highlighting in the Vue docs

- .changeset/stale-suns-worry.md
- clients/typescript/src/client/model/table.ts
- clients/typescript/test/client/model/table.test.ts
This PR fixes a bug in the DAL that caused rows to be included several times when including multiple relations.
The issue was reported on Discord: https://discord.com/channels/933657521581858818/1210387734234005614
> fix (client): avoid duplicate rows when including several relations

- clients/typescript/src/client/conversions/input.ts
- clients/typescript/src/client/model/table.ts
- clients/typescript/test/client/conversions/input.test.ts
Fixes https://github.com/electric-sql/electric/issues/938
The `upsert` operation validated _and transformed_ its inputs, but then subsequently called either `create` or `update` which re-transformed the already transformed inputs.
For most types its fine as the transform is idempotent, but for JSON we either need to check if the input is "deserializable" and assume it does not need to be re-serialized, or make sure we don't attempt to transform it more than once.
I might be wrong, but if we use the first approach there are cases where people might insert already serialized JSON values, leading to potential missed serialization (and then to an incorrect or failed deserialization).
Therefore I've made `upsert` only validate its inputs, and relegate the transformation to the `create` or …
> fix(client): Fix `upsert` transforming inputs twice

- examples/expo/metro.config.js
- examples/expo/package-lock.json
- examples/expo/package.json
Addresses https://github.com/electric-sql/electric/issues/981
We can use Metro's experimental feature that resolves NPM's `export` entry points to simplify electric's exports resolution.
See:
https://reactnative.dev/blog/2023/06/21/package-exports-support#enabling-package-exports-beta
https://metrobundler.dev/docs/package-exports/
(also took the opportunity to update some dependencies)
> chore(examples): Simplify Expo demo package resolution

- clients/typescript/package.json
- clients/typescript/src/cli/migrations/migrate.ts
- generator/package.json
- pnpm-lock.yaml
Revert to Prisma v4 for generating Prisma client because v5 introduced some breaking type changes.
Also pinned version of Zod to latest one before a bug got introduced.
> fix (generator): revert to Prisma v4 for generating Prisma client

- e2e/tests/03.11_node_satellite_compensations_work.lux
After the recent changes to the client connectiviy, we can use connect and disconnect. The status `available` doesn't exist anymore.
> fix(e2e): Use connect/disconnect instead of `connectivityStateChanged` in e2e test.

- e2e/satellite_client/Dockerfile
One thing we noted when building the satellite_client Dockerfile to run the E2E tests locally is that any slight change in the Electric client source code was invalidating most of the install and build work in Docker.
After some investigation we found out that latest PNPM version is much more performant in the docker build.
I also took the chance to add some comments to the Dockerfile to better understand the multiple steps.
Here is a comparison between the main branch and this PR. As you can see, the times are much faster, so when debugging E2E tests for the client the DX improves.
* Full docker build (--no-cache): 3m 24s
* After some edit in the Electric client: 2m 56s
* Full docker build (--no-cache): 1 min 3 s
* After some edit in the Electric client: 30s
> fix(e2e): Improve E2E Satellite client Dockerfile build performance

- clients/typescript/src/drivers/op-sqlite/index.ts
Self explanatory - op-sqlite needs to provide a `getRandomValues` impl like the other react-native drivers.
> fix(client): Provide crypto API implementation for op-sqlite driver

- .changeset/smooth-seals-design.md
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.tags.test.ts
This PR fixes a problem with `performSnapshot` which caused a deleted row to re-appear in the following scenario:
TX1: `insert row`
TX2 (causally after TX1): `update row; delete row`
After TX2 the deleted row would re-appear with the value of the update.
This occurs because `performSnapshot` would only set the clearTags on the first operation in each transaction which caused the `delete` not to override the `update`. As discussed with @icehaunter, the solution is to modify `performSnapshot` such that it sets the clearTags of all operations in a TX (except the first) to the tag of that transaction.
This PR applies the above fix and i can confirm that the anomaly is gone. I have added a unit test that checks this specific case. **However, another unit test**, called "origin tx (INSERT) …
> fix (client): fix snapshot query that sets the cleartags

- clients/typescript/src/satellite/client.ts
- clients/typescript/test/satellite/client.test.ts
Related to: https://github.com/electric-sql/electric/issues/426
When porting the latest changes from v0.9.3 to the Dart client we started experiencing a race condition when a new client subscribes to a shape. It looks like the RPC SatSubsResp message comes after SatSubsDataEnd, causing the error "Received subscribe response for unknown subscription (some_id)"
With the PR change this doesn't happen anymore and it's how it's done in startReplication to avoid race conditions
Without delayMessages:
With delayMessages:
cc @icehaunter 
Would this be the correct approach? Dart and JS have slight differences in the event loop, so sometimes a race condition is easier to catch in some language or in the other
> fix(client): Delay incoming messages when subscribing.

- components/electric/lib/electric/replication/changes.ex
This fixes a crash that was taking LogicalReplicationProducer down repeatedly, even after restarting Electric:
```
** (CaseClauseError) no case clause matching: Electric.Replication.Changes.TruncatedRelation
(electric 0.8.1) lib/electric/replication/changes.ex:64: anonymous fn/2 in Electric
.Replication.Changes.Transaction.count_operations/1
(elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
(electric 0.8.1) lib/electric/replication/postgres/logical_replication_producer.ex:
260: Electric.Replication.Postgres.LogicalReplicationProducer.process_message/2
(gen_stage 1.2.1) lib/gen_stage.ex:2206: GenStage.noreply_callback/3
(stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
(stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
(stdlib 4.3.1.2) …
```
> fix(electric): Handle Changes.TruncatedRelation in telemetry metrics

- .changeset/dry-pillows-confess.md
- components/electric/lib/electric/plug/proxy_websocket_plug.ex
- components/electric/lib/electric/plug/satellite_websocket_plug.ex
- components/electric/lib/electric/replication/postgres_manager.ex
Fixes VAX-1290.
This change also addresses the problem where a request sent to `/api/status` could time out if the Postgres Manager process was itself blocked on an IO call at the time.
> chore(electric): Limit client connections when the sync service's Postgres connection is down

- .changeset/early-schools-taste.md
- clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
- clients/typescript/src/drivers/capacitor-sqlite/database.ts
- clients/typescript/src/drivers/capacitor-sqlite/mock.ts
Using the `execute` API rather than the `run` one for when no bind values are provided as it has less pre-processing and solves a parsing issue that `run` has for statements like `BEGIN` and `ROLLBACK`.
Not strictly necessary but provides an immediate solution to a bug that is blocking the use of this driver on Android without requiring changes from the driver side.
See this issue: https://github.com/capacitor-community/sqlite/issues/526
> fix(client): Use `execute` Capacitor driver API to fix parsing issue

- .changeset/young-ads-wonder.md
- clients/typescript/package.json
- pnpm-lock.yaml
There was an issue with the driver's `executeSet` API not being able to run statements with comments (see https://github.com/capacitor-community/sqlite/issues/521) - that block even initializing electric as the migrations had comments on them.
I have removed the comments from the migrations so electric can be initiailzed with an earlier version of the driver but I believe that our APIs supporting statements with comments is important so bumping the minimum required version will save us some time from having to resolve issues where people can't run statements through our own API.
> chore(client): Bump Capacitor driver required version

- clients/typescript/src/electric/index.ts
Change to #1039 which is unreleased.
> chore(client) Export base adapter types to make creating external adapter possible.

- .changeset/green-lemons-rescue.md
- clients/typescript/package.json
- clients/typescript/src/drivers/expo-sqlite-next/index.ts
- clients/typescript/src/drivers/expo-sqlite/index.ts
- clients/typescript/src/drivers/op-sqlite/index.ts
- clients/typescript/src/util/random.ts
- pnpm-lock.yaml
Transitive depedencies don't install the corresponding pods in projects and thus the polyfill fails unless its included in the root project.
We will fire a warning and add docs explaining that this polyfill ensures better uniquness guarantees for UUID generation.
> fix(client): Remove `react-native-get-random` values dependency

- .changeset/thick-bottles-raise.md
- components/electric/lib/electric/postgres/dialect/postgresql.ex
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/writer.ex
- components/electric/lib/electric/replication/postgres_manager.ex
This helps fix the replication stream from Postgres to Electric if the publication got deleted by accident.
> chore(electric): Create publication on startup

- examples/recipes/backend/demo-server/src/app.ts
- examples/recipes/backend/demo-server/src/monitoring-metrics.ts
For the sake of deploying the backend to a VM, I'd rather not have artificial CPU loads inserted, natural fluctuations are enough to highlight the pattern.
> fix(recipes): Disable simulating high cpu load by default

- docs/api/cli.md
The `ELECTRIC_IMAGE` env var in the CLI docs was referring to the `ELECTRIC_PG_PROXY_PASSWORD` variable instead.
> fix(docs): Fix small typo in ELECTRIC_IMAGE CLI docs

- .changeset/rude-kids-smoke.md
- clients/typescript/src/drivers/op-sqlite/adapter.ts
- examples/react-native/src/Example.tsx
The op-sqlite driver returns HostObjects that do not behave the same way as regular JS objects and the parsing was failing somewhere in the field transformations where we use Object methods like `Object.entries`.
See https://ospfranco.notion.site/Gotchas-bedf4f3e9dc1444480fc687d8917751a
Also GH issue: https://github.com/OP-Engineering/op-sqlite/issues/65
The fix shallow clones the row fields into a JS object, probably losing some of the performance benefits gained from using these kinds of objects in the first place but we can revisit it in the future if it becomes significant.
> fix(client): Fix `op-sqlite` driver not returning results

- .changeset/quick-cooks-accept.md
- clients/typescript/src/client/execution/db.ts
- clients/typescript/src/client/execution/nonTransactionalDB.ts
- clients/typescript/src/client/execution/transactionalDB.ts
- clients/typescript/src/client/model/table.ts
- clients/typescript/test/client/generated/client/index.d.ts
- clients/typescript/test/client/generated/index.ts
- clients/typescript/test/client/model/table.errors.test.ts
- clients/typescript/test/client/model/table.test.ts
- clients/typescript/test/client/prisma/schema.prisma
Fixes https://github.com/electric-sql/electric/issues/1095
All operations must remain synchronous and use callbacks and continuations due to some driver limitations, which led to the passing around of `DB` instances that had field transformation and validation incorporated for a specific table.
This was not an issue for most cases as either related tables won't have shared column names, or if they do they are likely to also share the type and thus the field transformation worked.
In cases where a related table might have a column with the same name as the source table but a different type, the `DB` instance would try to validate/transform the related table column with the assumption that it is of the type of the source table column, leading to either 1) incorrect transformations (like …
> fix(client): Fix incorrect field transformation in queries including related tables

- components/electric/lib/electric/replication/changes.ex
Missed `truncated` in the function spec during a rebase.
> fix(electric): Fix wrong function spec

- .changeset/stupid-fishes-warn.md
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/test/electric/replication/electrification_test.exs
- components/electric/test/electric/replication/postgres/logical_replication_producer_test.exs
As explained in https://github.com/electric-sql/electric/issues/1083#issuecomment-2015354293, Electric cannot let Postgres know it can discard obsolete WAL records until it sees a write to an electrified table.
Here we issue such writes on a regular basis even if there are no user writes being performed by the clients or directly in the database.
Fixes #1083.
> fix(electric): Fix unbounded WAL size growth on disk

- clients/typescript/src/satellite/index.ts
- e2e/satellite_client/package.json
- e2e/satellite_client/src/client.ts
- pnpm-lock.yaml
Type declarations for the E2E client take 1.5 min to generate in the E2E Satellite client, which turns into a slow Docker image build for the E2E tests. Those declarations are not needed at runtime in the tests, and `tsmodule` can be configured to skip them during build. 
With these changes, the E2E Satellite client build is essentially instant.
The reason for the slow generation might be the complexity of the client model and zod types, but I'm not totally sure.
> chore(e2e_client): Don't create ts declarations in the E2E client build.

- clients/typescript/src/util/proto.ts
The debug satellite messages logger wasn't including the Compensation operation
> fix(client): Log compensation operation

- .changeset/warm-carrots-promise.md
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/replication/postgres/migration_consumer.ex
- components/electric/lib/electric/replication/postgres_manager.ex
- e2e/common.mk
- e2e/tests/01.05_electric_can_recreate_publication.lux
- e2e/tests/_shared.luxinc
This is a follow-up to https://github.com/electric-sql/electric/pull/1049 which was an incomplete solution for VAX-1465.
> fix(electric): Add all published tables to the Electric publication when it's recreated

- .changeset/real-snakes-drum.md
- components/electric/lib/electric/postgres/extension.ex
- components/electric/lib/electric/postgres/schema.ex
- components/electric/lib/electric/replication/shapes/querying.ex
- components/electric/priv/sql_function_templates/install_function__send_self.sql.eex
- components/electric/test/electric/postgres/extension/alter_shadow_tables_test.exs
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/support/postgres_test_connection.ex
- components/electric/test/support/satellite_helpers.ex
- components/electric/test/support/sql_generator.ex
- components/electric/test/support/sql_generator/column.ex
- components/electric/test/support/sql_generator/index.ex
- e2e/tests/01.06_replication_of_rows_that_predate_electrification.lux
When a table is electrified, its newly created shadow table is empty. If the user table had any rows prior to electrification, they would remain invisible to Electric due to the JOIN between the user table and its shadow table performed when querying for initial subscription data.
Fixes #1106, VAX-1750.
> fix(electric): Sync rows that were in the table prior to electrification

- clients/typescript/test/cli/migrations/migrate.generation.test.ts
There have been some instances of the CI for the client tests failing in the new migrate.generation.test.ts file.
https://github.com/electric-sql/electric/actions/runs/8630646197
https://github.com/electric-sql/electric/actions/runs/8615651764
I believe this is because there are multiple prisma generates running at the same time, which can cause issues: 
https://github.com/prisma/prisma/issues/19124#issuecomment-1753187096
This is a simple attempt to fix it, and easy to revert if it's not entirely the root of the problem.
cc @msfstef
> fix(client_tests): Run the migrate.generation test as serial

- clients/typescript/src/satellite/oplog.ts
The OpType sealed type was missing the COMPENSATION value.
The COMPENSATION value was implicitly being used when casting the op logs table rows to the OplogEntry type.
https://github.com/electric-sql/electric/blob/fd35035763c7e0193ce27700559dd72d3b1c3929/clients/typescript/src/satellite/oplog.ts#L28
By including the value we are also forced to handle it everywhere, like in the function `optypeToShadow`. I don't know what's expected to happen there, so I included an Error.
If this change is fine there might not be a need for the type `DataChangeType` https://github.com/electric-sql/electric/blob/fd35035763c7e0193ce27700559dd72d3b1c3929/clients/typescript/src/util/types.ts#L136
> fix(client): Add COMPENSATION to the OpType type

- docs/usage/data-modelling/types.md
Followup to https://github.com/electric-sql/electric/pull/1101
Adds `bytea` as a supported type (without caveats, at least for now :))
Also adds info block with table of driver support for byte arrays.
Deploy preview PR https://github.com/electric-sql/website/pull/119
Deploy preview: https://deploy-preview-119--electric-sql-website.netlify.app/docs/usage/data-modelling/types#supported-data-types
> chore(docs): Add BYTEA as supported type and note driver support

- docs/usage/data-modelling/types.md
After going down a rabbit-hole in SQLite-land, my conclusion is that even though inserting empty blobs as string literals works seamlessly, the issue of not being able to bind "empty blobs" (0-length byte arrays) is an issue with the SQLite C API itself and is not wrapper-specific.
SQLite wrappers can implement a "work around" the `sqlite3_bind_blob` C API to enable empty blob binding but because the fundamental issue is with the underlying API there will always be inconsistency between wrappers when it comes to binding empty blobs.
Ultimately being able to differentiate between a `NULL` and a 0-length byte-array is an edge case, even though the two are semantically different and the SQLite C API can already do that for blob literals, and given that this is not a wrapper issue as much as …
> chore(docs): Remove note about binding empty blobs

- .changeset/grumpy-ears-sort.md
- .changeset/rich-peaches-cover.md
- clients/typescript/src/cli/config-options.ts
- clients/typescript/src/cli/config.ts
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/test/cli/config-options.test.ts
- clients/typescript/test/cli/config.test.ts
Fixes https://github.com/electric-sql/electric/issues/911
As per the title, we fallback to the proxy URL to infer the database name if the database URL is not specified, and we print the proper proxy url as the proxy url rather than the Prisma introspection one to avoid confusing users.
> fix(cli): Fix CLI `PROXY` option to correctly infer DB name and not print introspection URL

- .changeset/grumpy-years-cheer.md
- clients/typescript/src/notifiers/event.ts
- clients/typescript/test/notifiers/event.test.ts
Addresses https://github.com/electric-sql/electric/issues/868
Initially I just removed the max listener limit as the way we use it any limit we set is going to be arbitrary and just an annoyance to real use cases (like Kyle's).
Afterwards I figured it would also be pretty simple to remove the global singleton emitter pattern altogether as it wasn't quite clear why it was there, since we only ever instantiate one `EventNotifier` when we electrify and that electric instance is meant to be shared across the application instance.
Unless we have a particular reason for using a singleton I think removing it is less likely to cause issues in the future (and help with the work on being able to completely "clean up" electric resources)
> fix(client): Remove global emitter for `EventNotifier` and remove max listener warning

- clients/typescript/src/notifiers/event.ts
- clients/typescript/src/satellite/process.ts
I think it would be convenient to log the origin of the changes now that the changed tables are logged too.
In the process we can also remove the INFO `notify changes` log, which was superfluous because an `actuallyChanged` call is always executed after it.
> feat(client): Log the origin of the notified changes

- .changeset/shaggy-keys-retire.md
- components/electric/config/runtime.exs
- components/electric/lib/electric/config.ex
- components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
- components/electric/lib/electric/postgres/logical_replication/decoder.ex
- components/electric/lib/electric/postgres/logical_replication/encoder.ex
- components/electric/lib/electric/postgres/lsn.ex
- components/electric/lib/electric/replication/changes.ex
- components/electric/lib/electric/replication/connectors.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/lib/electric/replication/postgres/migration_consumer.ex
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/lib/electric/replication/postgres_connector_sup.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/postgres/lsn_test.exs
- components/electric/test/electric/replication/electrification_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/replication/postgres/logical_replication_producer_test.exs
- components/electric/test/electric/replication/satellite_collector_producer_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/support/dummy_consumer.ex
- components/electric/test/support/postgres_test_connection.ex
- components/electric/test/support/satellite_helpers.ex
Continuing on from https://github.com/electric-sql/electric/pull/1099, this PR introduces the concept of a "persistent replication slot". Now, instead of having an auto-advancing replication slot, Electric can keep around WAL records that contain transactions it has already seen and acknowledged previously. As a result, when Electric restarts, it can repopulate its in-memory cache of transactions and be able to resume clients' replication streams.
New configuration options `ELECTRIC_TXN_CACHE_SIZE` and `ELECTRIC_RESUMABLE_WAL_WINDOW` have been added. The relevant docs are updated in https://github.com/electric-sql/electric/pull/1050.
> feat(electric): Use two replications slots to allow clients to resume replication after Electric restarts

- components/electric/lib/electric/postgres/cached_wal/api.ex
- components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
- components/electric/lib/electric/postgres/cached_wal/producer.ex
- components/electric/lib/electric/replication/postgres_connector_sup.ex
- components/electric/lib/electric/replication/satellite_connector.ex
- components/electric/lib/electric/satellite/client_manager.ex
- components/electric/lib/electric/satellite/client_reconnection_info.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/replication/electrification_test.exs
- components/electric/test/electric/replication/initial_sync_test.exs
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/support/postgres_test_connection.ex
- e2e/tests/01.03_postgres_writes_propagate_to_electric.lux
- e2e/tests/01.05_electric_can_recreate_publication.lux
- e2e/tests/02.04_satellite_write_gets_propagated_to_postgres.lux
- e2e/tests/05.03_postgres_wins_against_concurrent_transactions.lux
- e2e/tests/05.04_update_that_didnt_see_delete_resurrects.lux
- e2e/tests/05.05_compensations_within_same_tx_are_fine.lux
Follow-up to https://github.com/electric-sql/electric/pull/1043.
This PR makes the Elixir process run by `EtsBacked` scoped under the connector origin, similar to how other Postgres connector processes behave. It also updates telemetry metrics to use more precise names for what the `EtsBacked` cache actually stores: instead of "cache count" it's "transaction count".
> chore(electric): Refactor CachedWal.EtsBacked to use the new WAL config

- components/electric/mix.exs
This dependency is required for Observer to work at all. We're not including :wx as a dependency here because it's caused us problems in the past and it's not needed when connecting to a running Electric node from another Elixir shell. That other shell should itself have all of the dependencies needed to run Observer installed.
This is a new attempt to make Electric observer-enabled. The first (failed) attempt was https://github.com/electric-sql/electric/pull/467.
> fix(electric): Add :runtime_tools to enable the use of :observer running on a remote node

- .changeset/chilly-masks-prove.md
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
This race condition was discovered on https://github.com/SkillDevs/electric_dart/issues/21
A unit test is running, and it can happen that electric and the database connection are closed, while a `performSnapshot` call is scheduled/already running. An error is thrown when the snapshot tries to operate with the closed database.
The easy fix would be to "wait" for the snapshot mutix after cancelling the throttle, to ensure that it has ended to gracefully stop.
Another thing discovered is that `stop` was not returning a Promise, just calling `_stop` under the hood.
> fix(client): Don't leave a snapshot running when stopping the Satellite process

- components/electric/config/runtime.exs
- components/electric/lib/electric/config.ex
- components/electric/lib/electric/satellite/auth/secure.ex
- components/electric/test/electric/config_test.exs
- components/electric/test/electric/satellite/auth/secure_test.exs
This reverts [the change](https://github.com/electric-sql/electric/commit/0deba4d79de61a31aa19515d055a2a977a8e1b4e#diff-20b7a1cb738afa77ff1e885426e33a8c92faa3cc84aa9f62fd2f67b217e6f020R102-R113) introduced in the 0.9.3 release where the configured signing key would get automatically decoded if it looked like a valid base64-encoded string. That change has caused unintended problems to arise for users of Supabase Auth since its secret keys are base64-encoded but are meant to be used as is.
This PR introduces a separate configuration option `AUTH_JWT_KEY_IS_BASE64_ENCODED`. Corresponding doc update - https://github.com/electric-sql/electric/pull/1169.
> feat(electric): Try decoding the JWT key using base64 only when the config option is set

- .changeset/spicy-shirts-smoke.md
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
This PR modifies the Satellite process' `start` method in order not to delay the initial snapshot to the next tick because that could cause the snapshot to be ran after the process was closed, e.g. if someone starts the process and immediately closes it. I also added a corresponding unit test for this.
> fix (client): don't delay initial snapshot to next tick

- .changeset/tender-garlics-fetch.md
- components/electric/lib/electric/postgres.ex
- components/electric/lib/electric/postgres/repo.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/test/electric/replication/postgres/logical_replication_producer_test.exs
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/support/postgres_test_connection.ex
We already set display settings for the logical replication connection that Electric opens to Postgres, in order to ensure deterministic date-time, bytea, and float formatting. However, we don't do that for ad-hoc or pooled connections which are opened when needed, such as during the initial shape sync and when fetching additional shape data. As a result, trying to serialize initial or additional data that contains timestamps or bytea values formatted using configuration Electric doesn't expect leads to errors.
In this PR, we ensure that the same display settings get set for all DB connections Electric opens.
> fix(electric): Override display settings for any new DB connections

- docs/usage/auth/insecure.md
- docs/usage/auth/secure.md
The instructions in the docs under auth for running in docker incorrectly use the image name `electric-sql/electric` rather than the actual image name `electricsql/electric`. This PR fixes this.
> Fix docker instructions in auth docs

- .changeset/silly-seals-crash.md
- components/electric/lib/electric/postgres/extension/migrations/20230512000000_conflict_resolution_triggers/shadow_table_creation_and_update.sql
- components/electric/lib/electric/postgres/extension/migrations/20240205141200_reinstall_trigger_function__write_correct_max_tag.ex
- components/electric/priv/sql_function_templates/alter_shadow_table.sql.eex
- components/electric/priv/sql_function_templates/lookup_columns.sql.eex
- components/electric/test/electric/postgres/extension_test.exs
- e2e/tests/01.02_electrification.lux
- e2e/tests/01.07_postgres_dropped_columns_are_not_electrified.lux
> fix(electric): Filter out dropped columns in `electric.lookup_columns()`

- .changeset/rare-dogs-cheat.md
- components/electric/priv/sql_function_templates/perform_reordered_op_installer_function.sql.eex
- e2e/tests/03.26_node_pk_position_does_not_matter_for_compensations.lux
Original bug was that values from PKs were put in different columns. Reason for that bug is sneaky: I used a `%ROWTYPE` variable to store results of a `SELECT`, but `SELECT` selected PKs of the table first, and then all other columns. I assumed that `SELECT ... INTO` would fill the variable based on the column names, given that they match column names on the `%ROWTYPE` variable, but instead it used a column order to fill the fields of the variable, so PK values got into first columns of the table, and all columns up to PK were "moved" one over.
The solution here is to use a generic `RECORD` variable instead, because we're referring to columns by name later, and the way `SELECT` is built, it guarantees that every column of the original table is present.
> fix: make sure PKs in any positions work with compensations

- .changeset/grumpy-years-cheer.md
- clients/typescript/src/notifiers/event.ts
See https://github.com/electric-sql/electric/pull/1191 for description of issues that arose from removing the global emitter.
I'm opening this PR in the case we decide that we want to reintroduce it as it ensures that all instantiated electric clients will share notifications between them.
> fix(client): Reintroduce global emitter

- .github/workflows/examples_e2e.yml
- examples/_testing/e2e/website-demos/demos.spec.ts
- examples/_testing/package.json
- examples/_testing/playwright.config.ts
- examples/_testing/tsconfig.json
- examples/introduction/README.md
- examples/introduction/src/config.ts
- examples/introduction/src/env.d.ts
- examples/introduction/vite.config.ts
- pnpm-lock.yaml
Adds playwright e2e suite for testing the intro demos, similar to the website e2e's but the duplication is necessary due to 1) the submodule approach and 2) the different build settings and deployments (the website tests e2e agains the actual deployed netlify build)
> feat(examples): Adding E2E coverage for website intro demos

- .changeset/five-humans-ring.md
- clients/typescript/package.json
Adds peer dependency optional flags that are missing (also reordered to match peer dep order).
Relevant PR: https://github.com/electric-sql/electric/pull/1187
> chore(client): Add missing optional flag for peer dpeendencies

- .changeset/lazy-rocks-switch.md
- examples/starter/e2e/create-project.e2e.test.js
- examples/starter/e2e/test-utils.js
- examples/starter/src/file-utils.ts
We had an issue with some peer deps not being marked as optional that started causing the npm install to fail (see https://github.com/electric-sql/electric/pull/1205).
Despite that because the starter cli does not return a non zero exit code if it fails at the dep installation phase, some tests were passing - I've modified them to check explicitly that the dep installation error is not shown.
Until we upgrade the electric-sql package with the optional peer dep flag, I've added the `--legacy-peer-deps` to `npm install` calls to work around this issue. I will roll this back immediately after release after confirming that the individual examples work correctly as well.
> chore(starter): Test CLI more thoroughly for dep installation failure

- .changeset/two-ties-scream.md
- clients/typescript/src/satellite/client.ts
Addressing issue [raised in discord](https://discord.com/channels/933657521581858818/1231997358133477477)
The `TextEncoderLite` polyfill for the TextEncoder does not coerce its input to a string, and we force cast numbers with `as string` in the encoding stage, resulting in the input being encoded as an empty bytearray.
This does mean that the polyfill does not have the _exact_ same behaviour as the original (which it should), but the immediate solution is to respect types and not force cast to a string when it isn't.
> fix(client): Fix text encoding polyfill being fed numbers

- .changeset/strange-rabbits-compete.md
- clients/typescript/src/drivers/generic/adapter.ts
- clients/typescript/test/drivers/generic-adapters.test.ts
Fixes:
1) Duplicate rollbacks in interactive transactions, as a failing statement within a transaction would first trigger a rollback from within the `Transaction` object and then trigger a second one from the adapter's `transaction` API (see [discord chat](https://discord.com/channels/933657521581858818/1224163932630159461))
2) Interleaving of statements before a rollback occurs, as a failing statement within an interactive transaction would release the adapter's lock _before_ running `ROLLBACK` and thus lead to interleaving of statements run.
I've added failing tests for both cases and subsequently a fix for both.
I've kept multiple lock `release` calls to maintain the performance optimization of calling `release` _immediately_ after a commit is successful to avoid another event loop …
> fix(client): Fix duplicate rollback issue in adapter

- .changeset/four-onions-boil.md
- clients/typescript/package.json
Every Electric app needs Zod in order to use the generated client. However, in recent versions of Zod something changed that breaks the types in the generated client (cf. https://github.com/electric-sql/electric/pull/700). Therefore, Electric apps should always use Zod version 3.21.1. Added this as a peer dependency such that npm complains if the app installs a different version. Similarly, added an optional peer dependency for Prisma v4 such that it complains if the app installs another version of Prisma.
> chore (client): add Zod and Prisma as (optional) peer dependencies

- .changeset/weak-ducks-cross.md
This should have been included in 27fcdfc9edda93b046f64a771cd771dffccfb591.
> Add changeset for the signing key decoding change

- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/process.test.ts
- components/electric/lib/electric/satellite/permissions/state.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/satellite/subscriptions/permissions_read_filter_test.exs
- components/electric/test/electric/satellite/subscriptions_test.exs
- components/electric/test/support/postgres_test_connection.ex
- e2e/tests/02.02_migrations_get_streamed_to_satellite.lux
- e2e/tests/03.03_node_satellite_sends_and_recieves_data.lux
- e2e/tests/03.04_node_satellite_correctly_updates_serialization_caches.lux
- e2e/tests/03.06_node_satellite_does_sync_on_subscribe.lux
- e2e/tests/03.07_node_satellite_can_delete_freshly_synced_rows.lux
- e2e/tests/03.08_node_satellite_can_resume_subscriptions_on_reconnect.lux
- e2e/tests/03.11_node_satellite_compensations_work.lux
- e2e/tests/03.12_server_correctly_continues_the_replication.lux
- e2e/tests/03.21_node_satellite_correctly_handles_move_in_move_out.lux
- e2e/tests/03.22_node_satellite_can_disconnect_and_reconnect.lux
- e2e/tests/03.24_node_satellite_can_transform_at_replication_boundary.lux
- e2e/tests/03.27_postgres_dropped_columns_are_not_electrified.lux
- e2e/tests/06.02_permissions_change_propagation.lux
- e2e/tests/06.04_permissions_changes_resubscribe.lux
- e2e/tests/_shared.luxinc
Rather than attempt to reset the server connection's state after we've asked the client to reset itself, we just close the connection. The client will then re-connect automatically and, since it's had its state reset, the server will treat it as a first connection (including dropping all client reconnection state).
Since this is intended as an enabling simplification to maintain consistency between client and server in the simplest way possible, pending a more efficient, less brutal but much more complicated solution, I've tried to keep the changes to the protocol as small as possible. 
Hence the use of `throw` -- it's either that or restructure all the message handling on the server side to be more of a `reduce_while` style.
> Issue client reset message when permissions change

- examples/linearlite/.env
- examples/linearlite/db/load_data.js
- examples/linearlite/db/migrations/01-create_tables.sql
- examples/linearlite/package-lock.json
- examples/linearlite/package.json
- examples/linearlite/src/components/Modal.tsx
- examples/linearlite/src/components/TopFilter.tsx
- examples/linearlite/src/components/contextmenu/PriorityMenu.tsx
- examples/linearlite/src/components/contextmenu/menu.tsx
- examples/linearlite/src/electric.tsx
- examples/linearlite/vite.config.ts
Enables using Linearlite with PGlite or wa-sqlite by setting the `ELECTRIC_CLIENT_DB` env var to either `wa-sqlite` or `pglite`. This can be done in the `.env` file or any other standard way. It will be embedded into the build so a build will be for one or the other.
To be merged after #1038 with the `electric-sql` rep either pointing at a canary build or a published version.
> Linearlite with PGlite

- components/electric/lib/electric/postgres/repo/client.ex
- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/satellite/client_reconnection_info.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/test/electric/satellite/ws_server_test.exs
- e2e/tests/03.26_node_satellite_can_resume_replication_after_server_restart.lux
This is a follow-up to https://github.com/electric-sql/electric/pull/1116, specifically addressing [Ilia's request](https://github.com/electric-sql/electric/pull/1116#discussion_r1568646066).
Client reconnection info is now reloaded from the database at client connection time. This way we can ensure consistency between the data cached in ETS and data stored in the database.
> chore(electric): Load and clear client reconnection info per client

- components/electric/lib/electric/satellite/client_reconnection_info.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/test/electric/satellite/ws_server_test.exs
`fetch_subscription()` and `delete_subscription()` were only used when iterating over a list of subcription IDs. This PR changes those functions to issue bulk ETS and database calls that operate on the whole list of subscription IDs at once.
> chore(electric): Fetch and delete client subscriptions in bulk

- docs/api/_ELECTRIC_RESUMABLE_WAL_WINDOW.md
- docs/api/_ELECTRIC_TXN_CACHE_SIZE.md
- docs/api/service.md
Doc updates for https://github.com/electric-sql/electric/pull/1043.
Preview: https://deploy-preview-115--electric-sql-website.netlify.app/docs/api/service#electric_resumable_wal_window
> chore(docs): Document WAL window configuration options

- docs/api/_AUTH_JWT_KEY.md
- docs/api/_AUTH_JWT_KEY_IS_BASE64_ENCODED.md
- docs/api/service.md
- docs/usage/auth/secure.md
Documentation update for https://github.com/electric-sql/electric/pull/1168.
Preview:
- https://deploy-preview-122--electric-sql-website.netlify.app/docs/usage/auth/secure#auth_jwt_key_is_base64_encoded
- https://deploy-preview-122--electric-sql-website.netlify.app/docs/api/service#secure-mode
> chore(docs): Document the AUTH_JWT_KEY_IS_BASE64_ENCODED option

- .changeset/fast-boats-check.md
- clients/typescript/src/cli/migrations/migrate.ts
This PR fixes the CLI to pass the right dialect argument to the migrations endpoint and also error if the status code indicates a failure.
> fix (client): pass correct dialect spelling to migrations endpoint

- .changeset/spicy-items-poke.md
- clients/typescript/src/satellite/process.ts
Previous version prior to PG support didn't reference columns in the `ON CONFLICT`:https://github.com/electric-sql/electric/blame/c8e698148d4082d2c3fc1f081d410434f228b01b/clients/typescript/src/satellite/process.ts#L1631
I suspect this bug was inherited from the Tauri Linearlite demo as it only had PKs as "id"
> fix(client) Change _applyNonDeleteOperation to use pk column for creating the `ON CONFLICT` statement

- .changeset/breezy-meals-reflect.md
- clients/typescript/src/migrators/query-builder/pgBuilder.ts
Fixes #1238
Old subquery returns multiple rows when there was an index on other columns. This one is limited to `contype = 'p'` for primary key constraints.
> fix(client): Fix Postgres introspection subquery to only look at PK constraints

- .changeset/odd-bulldogs-move.md
- components/electric/lib/electric/replication/postgres_manager.ex
`Postgrex` connector doesn't support a behaviour equivalent to `sslmode=prefer` like `:epgsql` does, which we made use of when `DATABASE_REQUIRE_SSL=false`. To emulate support for that, after we make the first connection with `:epgsql`, we update the config to either force SSL or disable SSL based on how `:epgsql` connected.
> fix: set `Postgrex` SSL mode based on the connection by `:epgsql`

- docs/api/clients/typescript.md
- docs/examples/basic.md
- docs/examples/linear-lite.md
- docs/integrations/drivers/_category_.yml
- docs/integrations/drivers/index.md
- docs/integrations/drivers/mobile/_category_.yml
- docs/integrations/drivers/other/_category_.yml
- docs/integrations/drivers/other/generic.md
- docs/integrations/drivers/server/_category_.yml
- docs/integrations/drivers/server/better-sqlite3.md
- docs/integrations/drivers/server/pglite.md
- docs/integrations/drivers/server/postgres.md
- docs/integrations/drivers/web/_category_.yml
- docs/integrations/drivers/web/pglite.md
- docs/quickstart/_setup_manual.md
- docs/quickstart/index.md
- docs/recipes/01-read-only/data-viewer.md
- docs/reference/architecture.md
- docs/top-level-listings/integrations.md
- docs/top-level-listings/reference.md
- docs/usage/data-access/client.md
- docs/usage/data-access/shapes.md
- docs/usage/data-modelling/types.md
Preview: https://deploy-preview-128--electric-sql-website.netlify.app
node-postgres driver docs may need editing if a change is made due to this: https://github.com/electric-sql/electric/pull/1038#discussion_r1586623987
> chore(docs): PG on the client

- e2e/satellite_client/src/client.ts
- e2e/satellite_client/src/prisma/schema.prisma
- e2e/tests/_satellite_macros.luxinc
I've looked into why Lux didn't catch this. It appears to be because it was matching the same string that appears async in stdout via a SatOpLog. So I've tweaked the expectation so that it is more strict.
Another minor issue we found in the e2e client is the prisma definition for the enums table. We generate the Dart e2e client from the schema file, and the Enums model didn't include a `@@map`, so the generated table name was uppercase. But the e2e test creates the enums table as lowercase.
There appears to be other typing issues in the client, but I'm not sure how to resolve.
cc @kevin-dp
> fix(e2e_client): Fixes some typings in the e2e satellite client

- .changeset/lemon-buttons-warn.md
- clients/typescript/test/satellite/client.test.ts
- clients/typescript/test/satellite/merge.test.ts
- clients/typescript/test/satellite/server_ws_stub.ts
We found that the PG ports can collide in 2 of the tests.
We've also included a way to automatically assign a port to the client tests http server, as we've sometimes found some flakiness with the fixed port being used already.
> fix(client_tests): Fix port collisions

- docs/reference/roadmap.md
Fixes #1178.
Preview: https://deploy-preview-132--electric-sql-website.netlify.app/docs/reference/roadmap#failure-modes
> chore(docs): Update the cleanup snippet under "Failure modes"

- components/toolbar/vite.config.ts
Rollup removes invalid legacy annotations - they are warnings not errors but they fail the build so suppressing them should work for now.
> fix(toolbar): Suppress warning for invalid annotation

- .changeset/tall-bees-dream.md
- components/toolbar/package.json
- components/toolbar/src/api/interface.ts
- components/toolbar/src/api/statements.ts
- components/toolbar/src/api/toolbar.ts
- components/toolbar/src/tabs/LocalDBTab.tsx
- components/toolbar/src/tabs/SQLTab.tsx
- components/toolbar/test/api.test.ts
- components/toolbar/vitest.config.ts
- pnpm-lock.yaml
Add support for postgres dialect - modified the test suite to check for both postgres and sqlite dialects.
Abstracted the sql related code to support both dialects to a different module.
The schema hover card for PG uses a table with the column specification rather than the plain SQL since it doesn't expose it like SQLite, that makes them not behave the same but I think it's fine for now and for the purpose of the toolbar.
> feat(toolbar): Support Postgres dialect in toolbar

- .changeset/red-insects-provide.md
- clients/typescript/src/drivers/node-postgres/database.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/satellite/common.ts
- clients/typescript/test/satellite/process.timing.ts
- clients/typescript/test/satellite/process.ts
- clients/typescript/test/satellite/sqlite/process.timing.test.ts
We've encountered a race condition that can occurr if, after cancelling the throttle when stopping the process, some other piece of code calls throttlesnapshot. That's because cancelling the throttle doesn't prevent from scheduling new ones.
The proposed solution is to assign undefined to the function, so places that would normally trigger a snapshot, like the poll interval, would just do nothing until properly closed.
On top of this, we found that `setClientListeners` is only called when instantiating the process, but it's cleaned up when calling `stop` with the `disconnect` function. This makes it so that stopping and then starting the process won't have some of the client listeners properly set up. The proposed solution is to just move the client listeners intialization to the `start` …
> fix(client): Better throttle snapshot stop strategy 

- .changeset/sharp-dragons-design.md
- components/toolbar/package.json
Removing sourcemap files from published package after a discussion with @balegas - will reduce the package size on NPM significantly, if anyone wants to debug the toolbar they can do that on the project directly.
> chore(toolbar): Remove sourcemap files from published package

- .changeset/polite-donkeys-reflect.md
- components/toolbar/src/index.tsx
Checks whether container element has already been added before proceeding to add toolbar.
With React's `StrictMode` and other cases the `addToolbar` call might occur twice, handling it with a warning I believe is better than letting it add a broken DOM element.
> fix(toolbar): Guard against adding toolbar to DOM twice

- clients/typescript/src/satellite/mock.ts
- clients/typescript/test/satellite/process.ts
It looks like the new test `notifies for shape lifecycle` can fail with the postgres driver. When expecting 1 notifications, 2 were sent instead. This seems to be because the subscription data is emitted before the `Process.subscribe` ends (there is an `await setMeta` that can take a bit longer than the 1 ms delay the mock uses, when using the Postgres driver. 
I don't know if there is better way to solve this.
cc @msfstef
> fix(client_test): Improve flakyness of shape lifecycle test 

- .changeset/brown-candles-develop.md
- components/toolbar/src/api/interface.ts
- components/toolbar/src/api/toolbar.ts
- components/toolbar/src/tabs/ShapesTab.tsx
Remove the `setInterval` call used to monitor shapes in the toolbar and use the new notifier method instead.
> fix(toolbar): Use shape sub notifier in toolbar

- .changeset/five-rats-shake.md
- .changeset/selfish-years-suffer.md
- clients/typescript/src/satellite/client.ts
- clients/typescript/src/satellite/index.ts
- clients/typescript/src/satellite/mock.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/util/asyncEventEmitter.ts
- clients/typescript/src/util/encoders/sqliteEncoders.ts
- clients/typescript/test/satellite/process.ts
Currently if there is an unhandled exception in an event handler of asyncEventEmitter they are silenced and don't make it to a global error handler or console. This changes it to re-throw them async using `queueMicrotask` so that they happen outside of the promise awaited by `allSettled`.
> fix(client): asyncEventEmitter to not silence unhandled exceptions raised in event handlers

- clients/typescript/src/util/asyncEventEmitter.ts
Minor correction to the fix implemented in https://github.com/electric-sql/electric/pull/1247
Reintroducing the `queueMicrotask` throwing approach to ensure errors are definitely not suppressed (e.g. they need to be thrown independently of all listener promises `settling`/fulfilling) and ideally if more than one of them occur, all of them are exposed to the global error handler. See discussion here https://github.com/electric-sql/electric/pull/1247#discussion_r1620774644
The `queueMicrotask` API seems to be widely supported by browsers and runtimes so I don't think there's a need to worry. The alternative is also to use `setTimeout` which is also widely supported, but that might cause the errors to be thrown significantly later than when they were emitted.
> fix(client): Rethrow async event emitter errors ASAP

- .changeset/yellow-geckos-mix.md
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
Addresses [this issue](https://linear.app/electric-sql/issue/VAX-1888/temporary-replication-slot-name-too-long-crashes-electric)
This is a quick fix to avoid failures because of long names but the longer term solution is to ensure the replication slot names are smaller in general, see issue description for suggestions.
> fix(electric): Fix temporary replication slot going over character limit

- .changeset/nasty-buses-wink.md
- .changeset/pretty-zoos-mate.md
- clients/typescript/src/cli/config-options.ts
- clients/typescript/src/cli/config.ts
- clients/typescript/src/cli/docker-commands/command-psql.ts
- clients/typescript/src/cli/docker-commands/command-start.ts
- clients/typescript/src/cli/migrations/command-generate.ts
- clients/typescript/src/cli/migrations/migrate.ts
- clients/typescript/src/cli/tunnel/command-proxy-tunnel.ts
- clients/typescript/src/cli/util/index.ts
- clients/typescript/src/cli/util/parse.ts
- clients/typescript/src/cli/util/paths.ts
- clients/typescript/src/cli/util/string.ts
- clients/typescript/src/cli/utils.ts
- clients/typescript/test/cli/config-options.test.ts
- clients/typescript/test/cli/util/parse.test.ts
- clients/typescript/test/cli/util/string.test.ts
This is just to demonstrate the direction in which URL parsing can be improved in the CLI.
First, more test coverage is needed for some not-too-uncommon edge cases.
Second, more uniformunity is needed in the parsing code. Currently, in `src/cli/utils.ts` alone the database URL is parsed using a regexp, the service URL is parsed using the deprecated `url.parse()` method. All of this can be replaced with the built-in `URL` class and its properties/method. That class can also be used for building URLs, instead of ad-hoc string concatenation that doesn't escape URL components.
> fix(client): Fix URL parsing in the CLI

- .changeset/grumpy-goats-work.md
- components/electric/lib/electric/application.ex
- components/electric/lib/electric/replication/postgres_connector.ex
Previously, we would ignore any non-raising connector startup failures, failing to even log them.
With this change we make sure all connectors are running and log a fatal error when that's not the case.
Side note: there's an ongoing work in https://github.com/electric-sql/electric/pull/1226 on adding an e2e test to verify the correct output of such errors.
> fix(electric): Handle connector errors during startup

- .changeset/thin-impalas-bathe.md
- components/electric/lib/electric/postgres/repo.ex
Fixes #1278.
I have verified this fix by building a custom Docker image for this commit and deploying it to a DigitalOcean droplet that has IPv6 connectivity. The sync service connected to Supabase, the Ecto repo pool initialized successfully.
> fix(electric): Use the same TCP options for epgsql and Ecto connections

- components/electric/lib/electric/replication/postgres_connector.ex
Related: https://github.com/electric-sql/electric/issues/971.
> chore(electric): Improve error messages when the replication slot is already in use

- .changeset/polite-donkeys-reflect.md
- components/toolbar/src/index.tsx
Instead of guarding against remounting the toolbar, clean it up by removing the whole shadow dom root and remount it.
Main modification required was to deep clone the style from the template rather than just import it.
Alternative fix to https://github.com/electric-sql/electric/pull/1280
> fix(toolbar): Remount toolbar rather than block it

- .changeset/clean-singers-eat.md
- clients/typescript/src/config/index.ts
- clients/typescript/src/drivers/better-sqlite3/adapter.ts
- clients/typescript/src/drivers/generic/adapter.ts
- clients/typescript/src/electric/adapter.ts
- clients/typescript/src/migrators/bundle.ts
- clients/typescript/src/migrators/index.ts
- clients/typescript/src/migrators/mock.ts
- clients/typescript/src/satellite/config.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/src/util/transactions.ts
- clients/typescript/test/drivers/better-sqlite3.test.ts
- clients/typescript/test/drivers/generic-adapters.test.ts
- clients/typescript/test/util/transactions.test.ts
- pnpm-lock.yaml
This PR introduces an additional flag that can be enabled when electrifying a SQLite database. When the flag is enabled, the Satellite process disables FK checks on incoming transactions. This flag is useful for performance reasons as skipping FK checks greatly speeds up initial data sync when there is a lot of data.
Note that disabling FK checks can't be done transactionally so we have to disable FKs, apply the TX, and then re-enable FKs. Therefore, it is important that no transactions are ran concurrently (this is ensured by the mutex that our drivers hold).
We assume that Electric exlusively owns the DB connection and thus that nobody executes a concurrent TX directly on the DB connection.
> feat (client): flag to disable FKs on incoming TXs in SQLite

- clients/typescript/src/cli/config.ts
- clients/typescript/src/cli/configure/command-show-config.ts
- clients/typescript/src/cli/docker-commands/command-start.ts
- clients/typescript/test/cli/config.test.ts
Add print utility that redacts config and use that instead of console.log (for easier search later and modifying redaction logic if necessary without missing anything)
Also don't throw for unknown keys outside of the `Config` spec to allow flexibility
Finally build DB url for postgres option with the url building utility
> fix(cli): Fix cli config redact not redacting everywhere and throwing for unknown keys

- components/electric/Dockerfile
Since our Docker-based distribution of the sync service is stateless, every time a Docker container is started, it downloads the same tzdata database from a remote host.
To avoid doing that, we bundle the latest database file with the release.
> chore(electric): Bundle the latest tzdata database into sync service's Docker image

- components/electric/config/runtime.exs
- components/electric/config/runtime.test.exs
- components/electric/lib/electric/ddlx/command.ex
- components/electric/lib/electric/postgres/proxy/errors.ex
- components/electric/lib/electric/postgres/proxy/injector/operation.ex
- components/electric/lib/electric/postgres/proxy/query_analyser.ex
- components/electric/lib/electric/satellite/permissions.ex
- components/electric/lib/electric/satellite/permissions/write.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/test/electric/postgres/proxy/injector/electric_test.exs
- components/electric/test/electric/postgres/proxy/injector_test.exs
- components/electric/test/electric/postgres/proxy/query_analyser_test.exs
- components/electric/test/electric/postgres/proxy/schema_validation_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- docs/reference/roadmap.md
- docs/usage/data-modelling/permissions.md
- e2e/tests/02.03_partial_replication_based_on_user_id.lux
- e2e/tests/compose.yaml
Adds a feature flag `permissions` which turns on perms for both reads and writes (on the server), and another separate flag which enables granting write permissions.
So enabling `permissions` turns moves electric into a read-only mode using the permissions expressed via the DDLX
> Disable granting write permissions

- clients/typescript/src/_generated/protocol/satellite.ts
- clients/typescript/src/util/proto.ts
- clients/typescript/src/util/types.ts
- components/electric/config/runtime.exs
- components/electric/config/runtime.test.exs
- components/electric/lib/electric/ddlx/command.ex
- components/electric/lib/electric/postgres/proxy/errors.ex
- components/electric/lib/electric/postgres/proxy/injector/operation.ex
- components/electric/lib/electric/postgres/proxy/query_analyser.ex
- components/electric/lib/electric/satellite/permissions.ex
- components/electric/lib/electric/satellite/permissions/write.ex
- components/electric/lib/electric/satellite/protobuf_messages.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/write_validation.ex
- components/electric/test/electric/postgres/proxy/injector/electric_test.exs
- components/electric/test/electric/postgres/proxy/injector_test.exs
- components/electric/test/electric/postgres/proxy/query_analyser_test.exs
- components/electric/test/electric/postgres/proxy/schema_validation_test.exs
- components/electric/test/electric/satellite/permissions_test.exs
- components/electric/test/electric/satellite/write_validation_test.exs
- components/electric/test/electric/satellite/ws_server_test.exs
- components/electric/test/electric/satellite/ws_write_permissions_test.exs
- components/electric/test/support/mock_schema_loader.ex
- components/electric/test/support/satellite/ws_server_helpers.ex
- docs/reference/roadmap.md
- docs/usage/data-modelling/permissions.md
- e2e/tests/02.03_partial_replication_based_on_user_id.lux
- e2e/tests/03.25_node_pk_position_does_not_matter_for_compensations.lux
- e2e/tests/compose.yaml
- protocol/satellite.proto
As part of the move to read-only permissions this adds in permissions checks for writes from the clients. With this in place and a later pr to disable GRANTing write permissions, we can enable read-only permissions without needing to do the full implementation of scoped write permissions (which we need to figure out). If you can't grant write perms then we don't need to resolve them.
Note for reviewers: The permissions feature flag naming ceases to make sense with this pr, but that's all sorted in the next one, #1347
> Check permissions for incoming operations

- components/electric/test/electric/postgres/extension/ddl_capture_test.exs
Currently on the latest macOS the tests fail with `eaddrinuse`
This is due to the port being blocked:
- "On MacOS Big Sur and later, port 55555 ... is blocked" - [source](https://docs.solace.com/Software-Broker/SW-Broker-Set-Up/Containers/Set-Up-Docker-Container-macOS.htm#:~:text=On%20MacOS%20Big%20Sur%20and,%22port%20in%20use%22%20error)
- See also: https://forums.developer.apple.com/forums/thread/671197
This PR changes the port number used in the test
> Support macOS Big Sur and above

- docs/api/service.md
- docs/deployment/_render.md
- docs/deployment/docker.md
- docs/deployment/k8s.md
- docs/examples/notes/running.md
- docs/quickstart/_setup_manual.md
- docs/reference/architecture.md
- docs/usage/installation/service.md
Recommending setting a `LOGICAL_PUBLISHER_HOST` complicates the examples compared with just setting `ELECTRIC_WRITE_TO_PG_MODE=direct_writes` because this way you don't need to worry about having your docker electric addressable from Postgres.
> docs: switch config examples to use direct writes mode.

- .changeset/green-hornets-know.md
- components/electric/Dockerfile
- components/electric/rel/vm.args.eex
As explained in the newly added `rel/vm.args.eex` file, not doing this may lead to excessive memory usage of BEAM's OS process.
Specific comment on the Elixir Forum confirming that trying to limit the Docker container memory causes beam to get killed with an OOM error without this fix - https://elixirforum.com/t/elixir-erlang-docker-containers-ram-usage-on-different-oss-kernels/57251/15.
> fix(electric): Limit the number of Erlang ports at startup

- .changeset/khaki-needles-dream.md
Added a link to the PR for the change to circumvent the issue of the patch being assigned to the wrong commit, as I think it's useful for anyone wanting to figure out why the change was made to be able to see the description on the PR.
> chore(client): Add client to patch message for `WITHOUT ROWID` update

- .changeset/wild-buckets-tease.md
- components/electric/lib/electric/postgres/proxy/injector/electric.ex
- components/electric/lib/electric/postgres/proxy/injector/state.ex
- components/electric/lib/electric/postgres/proxy/query_analyser.ex
- components/electric/test/electric/postgres/proxy/injector_test.exs
psycopg sends begin, commit and rollback statements using the extended, parse, bind, execute, protocol, which is... different
> fix(electric): Add python psycopg3 support

- .changeset/curly-cheetahs-mix.md
- .github/workflows/examples_e2e.yml
Forgot to add a changeset for https://github.com/electric-sql/electric/pull/1378
Also the examples are using a fixed version of electric so until the update makes it to the examples they cannot be ran at Node v22 so rolling that back
> chore: Add Node update changeset

- .changeset/fast-fishes-hunt.md
- clients/typescript/src/config/index.ts
- clients/typescript/src/migrators/bundle.ts
- clients/typescript/src/migrators/index.ts
- clients/typescript/src/migrators/mock.ts
- clients/typescript/src/satellite/config.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/src/satellite/registry.ts
- clients/typescript/src/util/transactions.ts
- clients/typescript/test/satellite/process.ts
- clients/typescript/test/satellite/registry.test.ts
- clients/typescript/test/util/transactions.test.ts
Decided to go for an enumeration as this is more explicit than the `boolean | undefined`:
```ts
enum ForeignKeyChecks {
enabled = 'enabled',
disabled = 'disabled',
inherit = 'inherit',
}
```
> feat (client): renamed disableFKs flag and modified default to disable FKs on SQLite

- docs/api/clients/typescript.md
Follow-up to https://github.com/electric-sql/electric/pull/1376.
> chore(docs): Update documentation for the renamed foreignKeyChecksDownstream option

- components/electric/lib/electric/features.ex
- components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
- components/electric/lib/electric/postgres/cached_wal/producer.ex
- components/electric/lib/electric/postgres/extension/schema_cache.ex
- components/electric/lib/electric/postgres/oid_database.ex
- components/electric/lib/electric/postgres/proxy/handler.ex
- components/electric/lib/electric/postgres/proxy/sasl/scram_locked_cache.ex
- components/electric/lib/electric/postgres/proxy/upstream_connection.ex
- components/electric/lib/electric/replication/initial_sync.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- components/electric/lib/electric/replication/postgres/migration_consumer.ex
- components/electric/lib/electric/replication/postgres/slot_server.ex
- components/electric/lib/electric/replication/postgres/tcp_server.ex
- components/electric/lib/electric/replication/postgres/writer.ex
- components/electric/lib/electric/replication/postgres_manager.ex
- components/electric/lib/electric/replication/satellite_collector_consumer.ex
- components/electric/lib/electric/replication/satellite_collector_producer.ex
- components/electric/lib/electric/replication/satellite_connector.ex
- components/electric/lib/electric/satellite/client_manager.ex
- components/electric/lib/electric/satellite/client_reconnection_info.ex
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/ws_server.ex
- components/electric/lib/electric/telemetry/call_home_reporter.ex
Adding labels to processes to make using the Erlang Observer and various debugging tasks easier
> Add process labels

- .changeset/warm-months-explain.md
- components/electric/lib/electric/postgres/repo.ex
- components/electric/lib/electric/replication/postgres_manager.ex
When we upgraded the sync service to OTP 27.0, we missed the changed default from `verify_none` to `verify_peer` in SSL connections.
We now explicitly set `verify` to `verify_none` because it's currently the only way to ensure encrypted connections work even when a faulty certificate chain is presented by the PG host. This behaviour matches that of `psql <DATABASE_URL>?sslmode=require`.
Here's an example of connecting to DigitalOcean's Managed PostgreSQL to illustrate the point:
```
$ psql 'postgresql://...?sslmode=require'
Null display is "∅".
Output format is aligned.
Expanded display is used automatically.
Line style is unicode.
Border style is 1.
psql (16.1, server 16.3)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help. …
```
> fix(electric): Update SSL logic after upgrading to OTP 27.0

- .changeset/quick-crabs-accept.md
- components/electric/lib/electric/replication/shapes/sent_rows_graph.ex
- components/electric/test/electric/replication/shapes/sent_rows_graph_test.exs
Addresses [VAX-1977](https://linear.app/electric-sql/issue/VAX-1977/unsubscribes-really-slow-due-to-sent-rows-graph-popping-implementation)
While running Linearlite multi-project, I noticed unsubscribes took a very long time, and I found that the `Graph.delete_vertices` operation is what takes the most time to run by far, not scaling very well.
It doesn't make sense to me that deleting a bunch of vertices from a tree graph would take this long especially when traversing the whole graph is fast, so reconstructing it should really not be too much trouble (?), so my conjecture is that [the `delete_vertices` implementation](https://github.com/bitwalker/libgraph/blob/460cdfd9a163a533bdab0a160ba7ccf888047927/lib/graph.ex#L890-L926) which interacts with a map quite a lot is just suboptimal.
The …
> feat(electric): Proposed speedup of Sent Rows Graph popping method

- .changeset/fast-poems-perform.md
- clients/typescript/src/migrators/query-builder/builder.ts
- clients/typescript/src/migrators/query-builder/pgBuilder.ts
- clients/typescript/src/migrators/query-builder/sqliteBuilder.ts
- clients/typescript/src/satellite/oplog.ts
- clients/typescript/src/satellite/process.ts
- clients/typescript/test/migrators/builder.ts
Addresses [VAX-1985](https://linear.app/electric-sql/issue/VAX-1985/large-unsubscribes-lead-client-with-wa-sqlite-driver-to-a-stack)
Apparently the method we were using, where we chained `OR` and `AND` clauses in the `WHERE` clause, led to:
1. SQLite call stack overflow (at least with `wa-sqlite`) at around 6k `OR` clauses, far below the max parameter limit
2. Sub-optimal performance in both SQLite and PGlite
I've converted the batching to use `IN` statements for both single-column queries and multi-column ones, like with composite primary keys. The performance is significantly improved and has room for more improvement:
- ~4700ms pglite
- ~500ms wa-sqlite (arbitrary small batching to avoid overflow)
- ~700ms pglite
- ~2000ms wa-sqlite (max 6k batches)
- ~100ms pglite
- ~450ms wa-sqlite
- …
> fix(client): Fix batch deletes causing call stack overflow

- components/electric/lib/electric/replication/postgres_manager.ex
Merging https://github.com/electric-sql/electric/pull/1370 into `main` inadvertently broke the fix that had been introduced in https://github.com/electric-sql/electric/pull/1396. That latter PR's description goes into detail about why we are not ready to validate server certificates.
> fix(electric): Skip loading cacerts

- .changeset/rare-dancers-explain.md
- components/electric/lib/electric/satellite/serialization.ex
To prevent the 100MB payload limit:
```
[Symbol(kError)]: RangeError: Max payload size exceeded
at Receiver.haveLength (/Users/rob/src/electric-sql/electric/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/receiver.js:419:28)
at Receiver.getPayloadLength64 (/Users/rob/src/electric-sql/electric/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/receiver.js:406:10)
at Receiver.startLoop (/Users/rob/src/electric-sql/electric/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/receiver.js:161:16)
at Receiver._write (/Users/rob/src/electric-sql/electric/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/receiver.js:94:10)
at writeOrBuffer (node:internal/streams/writable:564:12)
at _write (node:internal/streams/writable:493:10)
at Writable.write (node:internal/streams/writable:502:10)
at …
```
> Chunk large satellite payloads

- .changeset/itchy-badgers-collect.md
- clients/typescript/src/client/model/table.ts
This PR adds deprecation warnings on all DAL methods.
> chore (client): deprecation warnings for DAL

- .changeset/forty-tables-study.md
- components/toolbar/package.json
- examples/linearlite/package-lock.json
- examples/linearlite/package.json
- pnpm-lock.yaml
I've updated the linearlite dependency as it was failing to build and also modified the toolbar workspace dependencies to allow for the closest patch version rather than the exact one.
We might want to do something similar for the CLI and Drivers packages but since they are more tightly coupled we can keep them as `workspace:*` rather than `workspace:~` - once we move to v1 we might want `worksapce:^`
> chore(linearlite): Fix linearlite deps

- clients/typescript/src/satellite/process.ts
- clients/typescript/src/util/proto.ts
- components/electric/lib/electric/satellite/protocol.ex
- components/electric/lib/electric/satellite/serialization.ex
- components/electric/lib/electric/satellite/serialization/data_validation_error.ex
- components/electric/test/electric/satellite/serialization_test.exs
https://linear.app/electric-sql/issue/VAX-1983/improve-error-reporting-from-server-to-client
This PR add the ability of the client to show friendly error messages when the error has originated on the server.
For example:
```
an error occurred in satellite: INVALID_REQUEST Unexpected value for int2 column: 32769
```
At this stage I've not tried to hide any noise such as the stack trace in these scenarios. So the user in fact sees all of this:
```
an error occurred in satellite: INVALID_REQUEST Unexpected value for int2 column: 32769
Client can't connect with the server after a fatal error. This can happen due to divergence between local client and server. Use developer tools to clear the local database, or delete the database file. We're working on tools to allow recovering the state of …
```
> Server to client error messages

- components/electric/lib/electric/replication/postgres/client.ex
- components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
- e2e/tests/01.08_electric_acknowledges_logical_message_lsn.lux
We've had the logic for advancing the main replication slot for some time now. That slot is used as a way to retain WAL records, allowing the sync service to maintain a window within which it can go back in time and replay old transactions.
A separate replication slot is used for the logical replication connection that the sync service maintains with Postgres when it's running. This slot is also known as the active replication slot.
The issue this PR addresses is caused by the fact that the active replication slot is never advanced when electrified tables aren't seeing any writes. This manifests as an endlessly growing replication lag and disk usage when the database sees a constant rate of writes to non-electrified tables:
With the fix in this PR in place, the sync service can now …
> fix(electric): Advance the active replication slot even when there are no writes to electrified tables

- docs/api/clients/typescript.md
- examples/linearlite/package.json
- examples/nextjs-example/app/match-stream.ts
- examples/nextjs-example/package.json
- examples/redis-client/package.json
- examples/redis-client/src/index.ts
- examples/remix-basic/app/match-stream.ts
- examples/remix-basic/package.json
- packages/react-hooks/CHANGELOG.md
- packages/react-hooks/package.json
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
- packages/react-hooks/test/support/global-setup.ts
- packages/react-hooks/test/support/test-context.ts
- packages/react-hooks/test/support/test-helpers.ts
- packages/typescript-client/CHANGELOG.md
- packages/typescript-client/README.md
- packages/typescript-client/package.json
- pnpm-lock.yaml
We're going to deprecate `electric-sql` and just keep all npm packages under the `@electric-sql` namespace.
> feat: update package name for typescript client to @electric-sql/client

- packages/sync-service/lib/electric/connection_manager.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/test/electric/postgres/replication_client_test.exs
Some changes to make some types of test failure less likely.
Recent example - https://github.com/electric-sql/electric-next/actions/runs/10256059321/job/28374360808?pr=254. These happen occasionally but are impossible to reproduce deliberately. I suspect the issue is related to the use of persistent slot and auto-reconnection logic that results Postgres delivering a logical message with a lower WAL offset than the one in `ReplicationClient`'s state.
> fix: Completely disable ReplicationClient's auto-reconnection logic

- .changeset/eight-dragons-brake.md
- packages/sync-service/lib/electric/log_items.ex
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/test/electric/log_item_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/log_offset_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/support/test_utils.ex
JSON encoding on write rather than read to reduce memory footprint. For example the memory use of an initial sync of a 35MB/200k row table can be reduced from 50MB to 25MB on the first initial sync (which includes the encoding and the writing to storage) and to 6MB on subsequent initial syncs (where we just read from storage and there's no encoding).
This change also allows some simplifications, so I have included them as refactoring in this PR:
- Logic to do with the structure and how to create Log Items has been consolidated to a new module `LogItems`
- The `prepared_change` intermediate state has been removed. The transformation `Changes > list(prepared_change) > LogItems` now is simply `Changes > LogItems` which makes the code more readable ( `prepared_change` was a 5 tuple rather …
> feat(sync-service): Encode JSON encode on write rather than read

- .changeset/fifty-frogs-warn.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> fix(sync-server): Fix error that occurs when `/shape` response stream is closed before it is complete

- .changeset/metal-flowers-share.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/shape_cache.ex
On out-of-the-box PostgreSQL the default connection maximum is 100, and you have to restart the server to raise that. This makes 50 a sane default, leaving enough headroom for other backends to connect to the same PG. Users that have a different connection limit on their PG can raise their pool size accordingly.
> feat: make DB pool size configurable with default of 50

- .changeset/loud-roses-fetch.md
- packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
- packages/sync-service/lib/electric/schema.ex
- packages/sync-service/test/electric/schema_test.exs
- packages/typescript-client/src/parser.ts
- packages/typescript-client/src/types.ts
- packages/typescript-client/test/parser.test.ts
This PR addresses https://github.com/electric-sql/electric/issues/1507.
The sync service is modified to include a `not_null: true` field on columns that have a `NOT NULL` constraint. For nullable columns we do not include this information as it is assumed to be nullable by default (consistent with Postgres).
The TypeScript client parses Database NULL values into JavaScript `null` only if the column is nullable.
> feat: include nullability in schema and parse null values on client

- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/support/component_setup.ex
> tests: add a test of idempotency of same txn storage

- .changeset/kind-starfishes-tap.md
- packages/sync-service/lib/electric/concurrent_stream.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/test/electric/concurrent_stream_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
Previously shapes with one million rows or more (170MB+) would timeout waiting for the snapshot to be created. Now the snapshot is streamed from the database into storage while simultaneously being streamed from storage to the client. This means the first packets of the response can be sent without waiting for the snapshot to finish. This means we now support tables with over a million rows. Ilia is currently benchmarking this branch to see what the new limits are. 
This PR addresses #1438 and #1444
I think there are quite a few simplifications that could happen off the back of this change, but I have kept the refactoring to a minimum in this PR and will instead address the simplifications in separate PRs.
> feat(sync-service): Streaming the response to the client without waiting for the snapshot to finish

- .changeset/curvy-tables-smash.md
- packages/react-hooks/test/support/test-context.ts
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/shapes/shape_test.exs
- packages/typescript-client/test/support/test-context.ts
This PR addresses https://github.com/electric-sql/electric/issues/1449 as it adds support for qualified schema and table names. To this end, i modified `validate_table` to parse (quoted) schema and table names.
> feat (sync service): support qualified schema and table names

- docs/guides/quickstart.md
Addresses the missing `x-electric-schema` header in the example response in the quickstart as per https://github.com/electric-sql/electric/issues/1443.
> docs: add x-electric-schema header in quickstart reponse example

- docs/electric-api.yaml
Some examples in the OpenAPI spec were still using the old `number/number` format for log offsets instead of `number_number`. This fixes those occurences as per https://github.com/electric-sql/electric/issues/1452.
> docs: fix offset formatting in OpenAPI spec

- .changeset/clever-parents-fail.md
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/collector.ex
- packages/sync-service/lib/electric/replication/changes.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/test/electric/postgres/replication_client/collector_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/support/component_setup.ex
This PR addresses https://github.com/electric-sql/electric/issues/1535 by detecting relation changes and cleaning up the shapes affected by the relation change. Note that Postgres' logical replication stream propagates relation changes lazily. So we won't detect the migration until somebody actually inserts/updates/deletes a row from a migrated table.
This PR is affected by a bug that causes schema information not to be deleted when a shape is cleaned. Because of that, when testing this PR you will notice that if we add a column the shape is cleaned but then if we fetch the shape again the new column is not present in the resulting rows. This should be fixed when the schema information bug is fixed.
> feat: clean shapes affected by relation changes

- .changeset/sour-oranges-clap.md
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/collector.ex
- packages/sync-service/test/electric/postgres/replication_client/collector_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
`ReplicationClient` was trying to be strict about LSN ordering of operations it was receiving from Postgres. But since LSNs of operations belonging to different concurrent transactions may be interleaved in the WAL, we should only make assumptions about ordering between complete transactions.
This change fixes #1548.
> fix: Remove invalid assumption about cross-transaction LSN monotonicity

- packages/sync-service/lib/electric/log_items.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes/querying.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/querying_test.exs
Closes #1536, pulls out the JSON-ification responsibility out of storage and into querying for easier iteration over that responsibility.
> fix: refactor out JSON serialization

- .changeset/wicked-bottles-attack.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
Fixes https://github.com/electric-sql/electric/issues/1552.
This PR addresses a bug that caused an infinite loop of failing requests.
The root cause for the bug is that we were always using the offset of the last change in a transaction but a shape may not be affected by all changes in the transaction (in which case the real latest offset would be the offset of the latest relevant change for that shape in the transaction). Because of that, when the shape plug checks if we have a log entry for the given offset, it may not exist and return a 409.
As a result of not finding an entry for the exact offset, Electric responds with a 409. The client thus comes back with an initial sync request (offset -1) and then Electric sends the latest offset it knows about which is again the commit offset. …
> fix: don't check for exact log offset existence

- .changeset/neat-bikes-trade.md
- examples/auth/app/layout.tsx
- examples/auth/app/providers.tsx
- examples/basic-example/src/App.tsx
- examples/linearlite/src/App.tsx
- examples/nextjs-example/app/layout.tsx
- examples/nextjs-example/app/providers.tsx
- examples/remix-basic/app/root.tsx
- examples/todo-app/src/routes/root.tsx
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
Fixes https://github.com/electric-sql/electric/issues/1571.
Removes the `ShapesProvider` and also updates the examples.
This is a breaking change since old applications use this `ShapesProvider` which no longer exists. Luckily, the fix is simple, just remove the `ShapesProvider` altogether.
> Feat!: remove shapes provider

- .changeset/pretty-donuts-rule.md
- examples/nextjs-example/app/match-stream.ts
- examples/redis-client/src/index.ts
- examples/remix-basic/app/match-stream.ts
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/helpers.ts
- packages/typescript-client/src/index.ts
- packages/typescript-client/src/types.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/helpers.test-d.ts
- packages/typescript-client/test/helpers.test.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/vitest.config.ts
Addresses https://github.com/electric-sql/electric/issues/1453
Adds the type guards to check whether a message is a `ControlMessage` or a `ChangeMessage`, documented, tested, and exported.
I've also honed in on the message type definitions a bit more as I had experienced an uncaught bug due to the generality of the `Headers` type.
> feat: `Message` type guard helpers

- examples/auth/app/page.tsx
The API calls for each user were cached so this PR adds a query-string per org-id so the browser caching works correctly.
> chore: fix auth example's caching

- .changeset/soft-gifts-watch.md
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/persistent_kv/mock.ex
- packages/sync-service/lib/electric/postgres/inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/stub_inspector.ex
Fixes https://github.com/electric-sql/electric/issues/1550.
This PR extends the shape log collector to also clean the cached column information from ETS when a relation changes. This ensures that when a table is migrated, we don't re-use the old table information from ETS but instead load it from Postgres and re-populate the cache with the new column info.
**There's one corner case that this PR does not address:**
- Create table, insert data
- Sync a shape containing that table
- Drop the table
- Delete the shape
- Recreate the table but with a different schema
- Insert some data into the new table
- Sync a shape containing the newly recreated table
In the above scenario, when syncing the newly recreated table, we get the new data but in the old schema (so we only get the columns that …
> fix: clean cached column information on delete

- .changeset/perfect-moons-end.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/support/component_setup.ex
This PR removes the `list_active_shapes` function and replaces its usages by `list_shapes`.
Also renames the `meta_table` field in `ShapeStatus` to `shape_meta_table` in order to be consistent with the naming throughout the rest of the codebase.
> chore: remove list_active_shapes

- .changeset/dull-islands-join.md
- packages/sync-service/lib/electric/replication/eval/env/explicit_casts.ex
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/test/electric/replication/eval/parser_test.exs
Support for the missing comparison predicates in WHERE clauses, as mentioned in #1441:
-  x BETWEEN y AND z
-  x NOT BETWEEN y AND z
-  z BETWEEN SYMMETRIC y AND z
-  z NOT BETWEEN SYMMETRIC y AND z
-  x IS UNKNOWN
-  x IS NOT UNKNOWN
> feat(sync-service): Support missing comparison predicates

- .changeset/lemon-eggs-care.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test-d.ts
- packages/react-hooks/vitest.config.ts
The default value for the `selector` argument used to be typed as `never` which is wrong. This PR improves the type of the default value.
> chore (react-hooks): improve type of selector argument in useShape hook

- .changeset/sharp-icons-serve.md
- packages/typescript-client/src/parser.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/parser.test.ts
Addresses https://github.com/electric-sql/electric/issues/1597
I also made the types include the possibility of `null` being a value that needs to be parsed and changed the parsers accordingly.
I don't love that currently if a field is not nullable and `null` is received it tries to force it to a field (like `null` to `0` if it's a number), and this logic definitely does not work on arrays marked as `NOT NULL` that are `null`. Are we against throwing for those cases?
> fix: Nullable arrays not being parsed as `null`

- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/plug/delete_shape_plug.ex
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/log_chunker.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shape_cache/log_chunker.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
Addresses https://github.com/electric-sql/electric/issues/1581
Will outline work done tomorrow, need to add some more tests as well - also I have deviated from the original design due to [this thread](https://electric-sql.slab.com/posts/rfc-chunking-the-log-2zee9qad#thread-xqaece2t).
I have externalised the chunk index from within the log itself but have kept it in storage - this might have a non-trivial impact on performance due to the additional IO involved in 1) storing the checkpoints and 2) reading the checkpoints on every request.
The benefits of externalising the index is that it makes it queriable, so we can still immediately know the end offset of a chunk before actually streaming it, which allows parallelisation of requests etc.
> feat: Log chunking

- docs/api/integrations/react.md
The snippet on the React integration page was renaming `data` to `fooData` but then using `data` which does not exist. Removed the renaming.
> chore (docs): fix React integration snippet

- .changeset/nine-worms-dance.md
- packages/react-hooks/package.json
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
- packages/react-hooks/test/support/react-setup.ts
- packages/react-hooks/vitest.config.ts
- pnpm-lock.yaml
Addresses https://github.com/electric-sql/electric/issues/1446
There is some weirdness with the `useSyncExternalStoreWithSelector` hook when passed a ref w.r.t. to selector changing - need to look into this deeper, I suspect memoization is using referential equality checks which is messing things up.
> Fix: `useShape` not correctly updating data when `selector` prop changes

- .changeset/seven-forks-happen.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
The `useShape` hook is behaving strangely when switching between different `where` conditions. I noticed that the `const latestShapeData = useRef(parseShapeData(shape))` was not updating when the underlying `where` parameters changed, while the other values within the useShape hook like `shape`, `shapeStream`, etc. were updating correctly. I propose adding the `shapeHash` in the `UseShapeResult`, as well as as a second argument to `parseShapeData`, so when the `useShape` is rendered we can determine wether we need to reset the `UseShapeResult`/`parseShapeData` reference.
nice work on this project all!
> fix: useShape re-renders on where state change

- .changeset/mean-wombats-search.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/log_chunker.ex
- packages/sync-service/lib/electric/shape_cache/mixed_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
This introduces a new storage backend, that's build as a plain file for snapshots, and CubDB for any metadata and ongoing logs. The benefit here is that we don't have to close the file while processing the results coming from the PostgreSQL query, unlike with batched CubDB writes. The result is that we're writing the snapshot roughly at the same rate as PostgreSQL generates query results.
This storage greatly improves initial snapshot performance (about triples the speed of snapshot creation), as well as RAM usage of Electric (benchmark made with 15s connection checkout timeout, hence the cutoff):
> feat!: add mixed storage

- .changeset/lemon-countries-own.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/mixed_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/supervisor.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/log_chunker.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/test_utils.ex
Based on feedback from @icehaunter - moving the chunking to the `ShapeConsumer` to reduce duplication and limit the storage layer's responsibility (as well as splitting IO from processing/preparing).
The JSON serializing and chunking of the log is now handled by the `ShapeConsumer` (see `prepare_log_entries` method), so storage only needs to distinguish between actual log items and chunk boundaries. That's perhaps the main coupling point/interface change that is noteworthy.
I've also moved the `chunk_byte_threshold` config outside of storage as it is no longer its responsibility, which meant threading it through a bunch of places. I'm happy to change that if there's a better pattern to do that.
> chore: Externalize log chunking from storage to `ShapeConsumer`

- .changeset/ninety-snakes-rest.md
- packages/sync-service/lib/electric/shapes/querying.ex
Improves performance heavily by moving row-to-JSON initial snapshot logic into PG. Currently utilizes hand-crafted JSON structure, but I'll make another test later if we can use a cleaner JSON building approach. 
Currently, if used with "mixed storage pr", it gives good improvements:
> feat: move row-to-JSON serialization for initial shape data to PG

- .changeset/poor-turtles-double.md
- packages/sync-service/config/runtime.exs
Replace individual persistence location configuration with a single `STORAGE_DIR` environment variable, that should be bound to a volume to survive Electric restarts. If you were using `CUBDB_FILE_PATH`, you should move that folder into a subdirectory named `shapes` and configure `STORAGE_DIR` to the previous directory.
> feat!: unify storage location for configuration ease

- packages/sync-service/lib/electric/shape_cache/cub_db_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
These should have been updated in c3a7beb but were overlooked.
The previous guard `max_offset == :infinity` would always evaluate to `false` and the `not is_log_offset_lt(...)` guard would always be used. The fixed version, i.e. `max_offset == @last_log_offset`, adds a micro-optimisation that can sometimes skip the comparison. No new test here because I haven't come up with a way to challenge the invariant that is asserted by this function's guards.
> fix: Remove incorrect uses of :infinity where LogOffset.t is expected

- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
Fixes #1563
With the new single-shape storage implementation, we can remove the `shape_id` param from almost all the Storage behaviour calls and also remove it from the actual db keys.
Some of the callbacks are also unecessary, such as `list_shapes` and `add_shape`. Instead we need a simple way to get a shapes current offset and snapshot xmin
> Clean up storage API

- .changeset/brown-turtles-listen.md
- .changeset/funny-houses-remember.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/client.test.ts
This PR fixes https://github.com/electric-sql/electric/issues/1468 as it exposes a `lastSynced` getter on the `ShapeStream` and `Shape` classes which is the number of milliseconds since last sync with the server.
> feat (client): expose time elapsed since last sync

- .changeset/cold-wolves-cheer.md
- packages/sync-service/lib/electric/plug/options_shape_plug.ex
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/test/electric/plug/options_shape_plug_test.exs
This PR fixes https://github.com/electric-sql/electric/issues/1646 by adding support for HTTP OPTIONS requests.
> feat (sync-service): support OPTIONS requests

- .changeset/shiny-beans-do.md
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/test/electric/plug/router_test.exs
This PR fixes https://github.com/electric-sql/electric/issues/1645 by adding support for HTTP HEAD requests.
> feat (sync-service): support HTTP HEAD requests

- .changeset/odd-trees-deny.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/test_storage.ex
Snapshot initialisation is done in two steps, set xmin and mark the snapshot started.
The `ShapeCache.await_snapshot_start/2` function was using the presence of an xmin for the given shape to determine if the snapshot was running. This would lead to occasional errors ("snapshot no longer available") if await_snapshot_start was called after the xmin call but before the snapshot was marked as started. 
This PR fixes this by using the snapshot start marker test in the await_snapshot_start function.
Unfortunately, despite a lot of hair tearing, I couldn't get the consumer_test.exs tests to pass using any combination of `Mox.allow/4`. I don't know if it's a problem with our particular setup of a bug in Mox itself, but the `ShapeCache.cast` call would inevitably be rejected by Mox. I could get …
> Fix snapshot race condition

- .changeset/large-cherries-lick.md
- packages/typescript-client/src/parser.ts
- packages/typescript-client/test/parser.test.ts
Hi there,
first of all, I really like your project! Amazing work! 🚀 
Thank you!
While integrating it I found a bug:
When a shape includes a column, that is nullable and currently null or set to null, the typescript client is crashing:
The code is checking if the `typeof value` is `object` and is then trying to iterate over it's keys.
However, `typeof null` is also `object`. This is why it crashes here, as it cannot iterate over null.
This PR fixes https://github.com/electric-sql/electric/issues/1673.
A simple check for `null` fixes this as proposed in this PR.
Could you please merge it? Or is there anything I've overseen?
Thanks!
> Fix null value parsing

- .changeset/flat-ears-yawn.md
- .changeset/happy-crews-tie.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/typescript-client/src/client.ts
This PR fixes https://github.com/electric-sql/electric/issues/1663.
The implemented semantics are the following.
- When shape id exists:
- and is the currently active shape for this shape definition:
- serve it normally
- and is not the currently active shape for that shape definition:
- return 400 (because there must be a mismatch between shape ID and shape def, otherwise this would be the active shape for that shape definition)
- When shape id does not (or no longer) exist:
- if there is an active shape for this shape definition:
- return 409 that redirects to the active shape
- if there is no active shape for this shape definition:
- create the shape
- return a 409 with a redirect to the newly created shape
> feat (sync-service): validate shape ID matches shape definition from URL

- examples/nextjs-example/package.json
- examples/remix-basic/package.json
- examples/tanstack-example/package.json
Duplicated package names causes problems with various monorepo tools.  The package names now match the folder name.
> fix: fix package.json names that were duplicated

- .changeset/lovely-rules-argue.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
Part of #1664.
Below are some trace examples from Honeycomb.
Initial snapshot:
Chunked response to a "GET shape" request:
Transaction processing time in the replication client with the number changes as an attribute:
> chore: Add OpenTelemetry spans to ServeShapePlug and ReplicationClient

- .changeset/thick-experts-call.md
- packages/sync-service/lib/electric/connection_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/timeline.ex
- packages/sync-service/test/electric/timeline_test.exs
Fixes https://github.com/electric-sql/electric/issues/1689.
This PR uses Postgres' `system_identifier` to detect when Electric is connected to a different Postgres database than before. When that is the case, we log a warning and clean all shapes. Cleaning all shapes is consistent with how we handle Point In Time Recoveries (where we also clean all shapes).
Note: this is a breaking change because we modify the structure of the timeline we store persistently. We used to just store the timeline ID, but now we store a list `[pg_id, timeline_id]` so we can't read out old persisted timeline information as we are expecting the new structure.
> feat (sync-service)!: clean all shapes when switching to a different DB

- .changeset/hot-otters-crash.md
- packages/sync-service/.env.dev
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/shape_cache/log_chunker.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/typescript-client/test/integration.test.ts
Addresses https://github.com/electric-sql/electric/issues/1667
We were using  10kB chunks rather than 10MB chunks - whoops!
This is still the uncompressed threshold, if gzip is added the chunks should be _significantly_ smaller, but we need some work on estimating that (generally speaking for json it could be 90-95% size reduction, but it's hard to tell if some rows contain large items that are not easily compressable)
I've kept the dev environment chunk size to 10kB such that integration tests can work with small chunks and still be fast (i.e. we don't have to load PG with hundreds of MB of data to test chunking)
> fix: Adjust chunk size to 10 MB

- .changeset/rare-cooks-marry.md
- .github/workflows/elixir_tests.yml
- packages/sync-service/config/runtime.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
This modifies the unit tests to use the publication filter logic for PG 15 as that is more advanced than the logic for version 14 and below.
> chore (sync-service): run filter logic for PG version 15 in unit tests

- .changeset/brown-files-flash.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/client.test.ts
- website/docs/api/integrations/react.md
This PR introduces the `isLoading` status on the `ShapeStream` and `Shape` classes and on the `useShape` hook as well. As requested here: https://github.com/electric-sql/electric/issues/1687#issuecomment-2352856430.
> feat (client): expose isLoading status

- .changeset/wicked-beds-play.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/typescript-client/test/integration.test.ts
Cleans up the underlying data for the shape, not only the metadata.
I'm not entirely sure if this is the best approach or if there's a cleaner way @robacourt ?
(also fixed an integration test that was causing issues)
> fix: Clean shape data when individual shape is cleaned up

- .changeset/curly-terms-sparkle.md
- packages/sync-service/mix.exs
Another fix on top of https://github.com/electric-sql/electric/pull/1713.
This is the correct stanza. Taken from https://github.com/electric-sql/electric-old/blob/b4da7af0e45ed7c34a5069640922ab8acca389bd/components/electric/mix.exs#L21-L27.
> fix(sync-service): Fix the start order of OT apps for real this time

- .changeset/four-chicken-crash.md
- .github/workflows/elixir_tests.yml
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/connection_manager.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_setup.ex
This PR fixes https://github.com/electric-sql/electric/issues/1712.
We were previously reading out `server_version` which is a string and were casting it to an integer in order to get PG's major version number. However, casting to integer does not work when the `server_version` is set to e.g. `16.4 (Debian 16.4-1.pgdg1123+1)` which some providers do. This PR changes this such that we no longer cast the string but instead read the version number from the `server_version_num` setting which is an integer (cf. https://pgpedia.info/s/server_version_num.html and https://pgpedia.info/s/server_version_num.html).
> fix (sync-service): query PG version number using PG's `server_version_num` setting

- .changeset/tricky-houses-burn.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/shape.ts
- packages/typescript-client/test/client.test.ts
- website/docs/api/integrations/react.md
This PR extends the client to expose a `lastSyncedAt` field which indicates the last time at which the client synced with Electric.
> feat (client): expose time at which client last synced with Electric sync service

- website/docs/api/clients/typescript.md
Fixes a broken open brace in the TypeScript client docs (it was using the unicode code for an open brace instead of open brace itself).
> chore (docs): fix open brace in TypeScript client docs

- website/docs/guides/shapes.md
- website/electric-api.yaml
Extend the shape docs to explain that shapes are not deleted automatically when tables are dropped.
Fixes https://github.com/electric-sql/electric/issues/1706.
> docs: document shape deletion on table drop

- .changeset/lucky-crabs-lie.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/typescript-client/src/constants.ts
- packages/typescript-client/test/cache.test.ts
- packages/typescript-client/test/integration.test.ts
This PR removes the x- prefix from Electric's custom headers, as essentially the x- prefix has been deprecated for a while. **This is a breaking change** as it changes the names of the headers. Fixes https://github.com/electric-sql/electric/issues/1737.
> chore!: remove x- prefix from custom HTTP headers

- .changeset/metal-horses-call.md
- .changeset/warm-grapes-brush.md
- .support/docker-compose.yml
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/constants.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/fetch.test.ts
- packages/typescript-client/test/integration.test.ts
Followup to https://github.com/electric-sql/electric/pull/1731
Implemented a fetch wrapper that does not wait for the chunk bodies to be streamed to the client and processed by the subscribers, and instead prefetches a number of chunks from the network as soon as the available headers to determine the next chunk are available.
I also had to implement another response header on our api called `electric-chunk-up-to-date`, similarly to how we use `electric-chunk-last-offset`, which allows us to know all the necessary chunk metadata without having to read the actual body. If we do not know if a chunk is an `up-to-date` chunk, we don't know whether we should request the next one, and whether its caching policy should be adjusted on the CDN.
I've set the default for prefetching to 2 chunks, but …
> feat: Chunk prefetching in `ShapeStream`

- .changeset/kind-turkeys-reply.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
Closes #1751.
Electric can be configured to listen on the `:::` IPv6 address, as opposed to the default `0.0.0.0` IPv4 one, by configuring it with `LISTEN_ON_IPV6=true`.
> feat(sync-service): Support listening on IPv6 network interfaces

- .changeset/poor-candles-fly.md
- integration-tests/tests/crash-recovery.lux
- integration-tests/tests/invalidated-replication-slot.lux
- integration-tests/tests/macros.luxinc
- integration-tests/tests/postgres-disconnection.lux
- integration-tests/tests/rolling-deploy.lux
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/connection_manager.ex
- packages/sync-service/lib/electric/lock_connection.ex
- packages/sync-service/lib/electric/plug/health_check_plug.ex
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/connection_setup.ex
- packages/sync-service/lib/electric/service_status.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/plug/health_check_plug_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/postgres/lock_connection_test.exs
- packages/sync-service/test/support/component_setup.ex
Addresses https://github.com/electric-sql/electric/issues/1749
- Makes publication and slot names configurable via a `REPLICATION_STREAM_ID` env variable, which can ultimately be used for multiple electric deploys
- Quotes all publication and slot names to address potential issues with configurable names (alternative is to force downcase them when initialised to avoid nasty case-sensitive bugs)
- Waits for a message from `Electric.LockConnection` that the lock is acquired before initialising `ConnectionManager` with the replication stream and shapes.
- If more than one Electric tries to connect to the same replication slot (with the same `REPLICATION_STREAM_ID`), it will make a blocking query to acquire the lock that will resolve once the previous Electric using that slot releases it - …
> fix: Handle replication slot conflicts

- .changeset/dry-buses-fail.md
- packages/sync-service/lib/electric/connection_manager.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
- packages/sync-service/test/support/db_setup.ex
We were querying it after starting the replication client before, which was too late, because by that time the shape recovery process might have already reached `Electric.Postgres.Configuration.configure_tables_for_replication!()` where the version is used to branch the control flow. This was causing flake in integration tests due to the version not always being there and the unsupported query being issue against Postgres version 14.
In short, this PR resolves the flakiness in integration tests, they should be consistently green from now on. 
The choice of augmenting the `LockConnection` module with version querying and a crude state machine might seem dubious but the end result is simpler this way, compared to adding version querying to the replication client, for example.
> fix(sync-service): Query Postgres server version at the start of connection setup

- website/docs/quickstart.md
Just a little docs thing...
The JSON output in the quickstart example isn't formatted as stated/expected.
> Format quickstart output

- packages/sync-service/Dockerfile
Running the benchmarks should only happen once the ./health endpoint has returned `active`. To do this we add a health-check when running the docker image that uses curl:
```
if [[ "`curl localhost:3000/v1/health`" != '{"status":"active"}' ]]; then exit 1; fi
```
This PR adds curl to the docker image to allow this health check to work.
> (chore) Add curl to Dockerfile to allow benchmarking to do health-checks

- .changeset/chilly-carpets-compare.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/stream.test.ts
Implements feature described in https://github.com/electric-sql/electric/issues/1748
Attaches headers to all requests - figured we'd go with the simple route of static dictionary of headers to add, we can always enhance it with a function dependent on the state of the stream and even potentially make it an async function that waits for the headers to be provided before making the next request - but KISS
> feat: Add `headers` utility option to `ShapeStream` API

- .changeset/metal-rocks-type.md
- packages/sync-service/lib/electric/postgres/inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/postgres/inspector/ets_inspector_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_structure_setup.ex
- packages/sync-service/test/support/stub_inspector.ex
This PR fixes https://github.com/electric-sql/electric/issues/1764 according to the approach that was decided by @KyleAMathews, namely to adhere to Postgres' way of handling identifiers. Therefore, this PR modifies Electric such that it passes the user-provided root table to Postgres which then returns the actual relation (i.e. schema and table name). Which we then use throughout the rest of the code as before.
We extended the ETS inspector with a write-through cache that caches the relation. For any incoming request, it tries to fetch the relation for that table from the cache. If not found, it loads it from PG and stores it in the cache. Note that many table name spellings can refer to the same relation, e.g. `users`, `USERS`, `public.users`, etc. all refer to the same relation …
> fix (sync-service): let Postgres handle user-provided root table name

- .changeset/mean-swans-act.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/dev/docker-compose-otel.yml
This PR fixes https://github.com/electric-sql/electric/issues/1714 by introducing a separate `OTEL_DEBUG` env var to enable printing the spans to stdout while also being able to export the spans using `OTEL_EXPORT`.
> feat (sync-service): add OTEL_DEBUG environment variable

- website/docs/guides/shapes.md
Partly addresses https://github.com/electric-sql/electric/issues/1769 although it would be much better to add more technical details.
https://deploy-preview-1773--electric-next.netlify.app/docs/guides/shapes#where-clause
> docs: where clause limitations with feature request CTA.

- .changeset/weak-chairs-type.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/test_storage.ex
More radical alternative to https://github.com/electric-sql/electric/pull/1805
Addresses https://github.com/electric-sql/electric/issues/1802
Moves the shape definition to the `Storage` interface.
I've started with just making `ShapeStatus` use the `Storage` for recovering shapes - but if we also store OIDs of the relation we can also do away with storing relations and get rid of any persistence in `ShapeStatus`
I believe this is mergeable if we want to move at least shape definitions to the storage and think about relations in a separate PR
> feat: Restoring shapes only through the `Storage` interface

- packages/sync-service/lib/electric/shapes/consumer.ex
This is the simplest change to meet the criteria of #1744 .
It's faster and uses less memory:
Than our current version:
Because of the reduction in memory use it can handle bigger transactions at 100k shapes:
vs our la
test version:
> feat(sync-service): Move WHERE clause evaluation to single process

- .changeset/curly-ravens-film.md
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/test/fetch.test.ts
- website/electric-api.yaml
Fixes https://github.com/electric-sql/electric/issues/1770
With https://github.com/electric-sql/electric/pull/1787 we've managed to return 429s whenever there's too many concurrent shape creations that cause the database connection pool to be exhausted.
This PR just ensures that the client does indeed retry on 429s - for now just with our regular exponential backoff, as there is no standard for retry headers to respect.
P.S. additional changes to the openapi spec done by my formatter 👀 I can roll them back if you think they are worse than before
> fix: Handle 429s in the client

- .changeset/odd-ants-smell.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/connection_manager.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/support/db_setup.ex
Fix #1718.
Obfuscation is implemented by wrapping the password in a zero-arity function as early as possible, so that the password is never stored in cleartext in any of our processes' state. The deobfuscation happens right before passing connection options to Postgrex. This creates an explicit point of hand-off where the responsibility for keeping the password from getting leaked is transfered from our code to Postgrex.
> Obfuscate database password to avoid accidentally leaking it in logs

- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
I saw a test failure in `main` due to the long poll timeout being set to 100 millisec in one of the tests, resulting in a division-by-zero error in ServeShapePlug:
```
1) test ServeShapePlug sends an up-to-date response after a timeout if no changes are observed (Electric.Plug.ServeShapePlugTest)
test/electric/plug/serve_shape_plug_test.exs:472
** (ArithmeticError) bad argument in arithmetic expression
code: |> ServeShapePlug.call([])
stacktrace:
(electric 0.7.2) lib/electric/plug/serve_shape_plug.ex:33: Electric.Plug.ServeShapePlug.TimeUtils.seconds_since_oct9th_2024_next_interval/1
(electric 0.7.2) lib/electric/plug/serve_shape_plug.ex:354: Electric.Plug.ServeShapePlug.put_resp_cache_headers/2
(electric 0.7.2) lib/electric/plug/serve_shape_plug.ex:1: …
```
> fix(sync-service): Fix a division-by-zero error in a unit test

- .changeset/large-days-attend.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/plug/utils.ex
- packages/sync-service/lib/electric/postgres/identifiers.ex
- packages/sync-service/lib/electric/replication/changes.ex
- packages/sync-service/lib/electric/shapes/querying.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/plug/utils_test.exs
- packages/sync-service/test/electric/postgres/identifiers_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/constants.ts
- packages/typescript-client/test/integration.test.ts
- website/electric-api.yaml
Implements https://github.com/electric-sql/electric/issues/1804
- I've picked `columns` as the query parameter name, as `select` might confuse people and get compared to SQL `SELECT`s, and `filter` is too close to what the `where` parameter does.
- The columns are comma separated column names, parsed at the validation stage
- If the parameter is specified, it *has to include* the primary key columns
- We could make it such that the PK is always included, but it feels like it might be confusing - explicit is better?
- For tables without a primary key, we treat _all_ columns as primary keys - we might want to revisit that w.r.t. to this feature
- Columns are validated also by ensuring that all specified column names match the ones in the schema
- The selected columns are stored in the …
> feat: Add `columns` API query parameter to filter table columns

- .changeset/sweet-papayas-shake.md
- packages/sync-service/lib/electric/replication/eval/env.ex
- packages/sync-service/lib/electric/replication/eval/env/known_functions.ex
- packages/sync-service/lib/electric/replication/eval/lookups.ex
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/lib/electric/replication/eval/runner.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/lib/pg_interop/array.ex
- packages/sync-service/test/electric/replication/eval/parser_test.exs
- packages/sync-service/test/electric/replication/eval/runner_test.exs
- packages/sync-service/test/pg_interop/array_test.exs
Adds support for:
1. Usage of array columns in where clauses
2. Base operators for arrays: `@>`, `<@`, `&&`, `||`
3. Validation for polymorphic operators (`anyarray` pseudo-type and others), paving way for other functions that accept arrays 
Closes #1767, #1766
> feat: support array functions in where clauses

- packages/sync-service/.env.dev
- packages/sync-service/config/runtime.exs
We have detailed debug logs that log every transaction incoming from Postgres, including its every change. This is not a good default for a production environment where the rate of writes may easily spam the logs, drawing them almost useless.
We leave debug as the default for the dev env.
> chore(sync-service): Set default log level to 'info' in production

- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
Fix https://github.com/electric-sql/electric/issues/1837
> Fix: prevent the server from returning the same cursor as it received

- .changeset/tasty-carpets-accept.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/postgres/identifiers.ex
While setting up another project, I noticed that replication slots _cannot_ contain special characters, so parsing and validating the provided id early will prevent unnecessary headaches.
> fix: Parse and validate `REPLICATION_STREAM_ID`

- .changeset/rare-lemons-give.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/support/transaction_consumer.ex
Fixes https://github.com/electric-sql/electric/issues/1870
With recent changes to the codebase, relation changes are handled by individual shape consumers the same way transactions are, and they trigger cleanups or other processes.
I've made the relation handling match the transaction handling, including the dropping of relation messages if no subscribers are present.
> fix: Relation handling should match transaction handling

- .changeset/slow-panthers-design.md
- packages/sync-service/lib/electric/postgres/identifiers.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
Fixes https://github.com/electric-sql/electric/issues/1814
We still go to PG to validate the table as we need its OID, so this is not strictly necessary, but since we have validation logic we might as well validate things locally to avoid going to PG for clearly invalid table identifiers?
This also fixes the accepted characters by PG for identifiers [based on the docs](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) as it was excluding some unicode chars and dollar signs before.
> chore: Validate table names locally first

- .changeset/flat-melons-attack.md
- packages/sync-service/lib/electric/plug/options_shape_plug.ex
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/plug/utils.ex
- packages/sync-service/test/electric/plug/options_shape_plug_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
Fixes https://github.com/electric-sql/electric/issues/1824
Moves the CORS header logic to a utility and at the router level so we can define the allowed methods for each endpoint.
Defining it in each endpoint is counterintuitive as for all `/v1/shape/:root_table` endpoints we should be returning the same allowed headers.
> fix: Unify CORS header handling

- .changeset/pretty-scissors-search.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/integration.test.ts
Fixes https://github.com/electric-sql/electric/issues/1876
The issue was that we were sending `must-refetch` messages with some of our 400s, although they were unrecoverable and re-fetching would trigger an infinite loop.
I've made the server send 400 errors for the cases where the `shape_id` and `shape_definition` do not match, with an explanatory message, and I've made the client terminate when receiving such an error.
As a temporary measure, the error is not thrown into the ether but stored in the `ShapeStream` (accessible via `stream.error`).
We have had some discussions with @balegas about making errors more "handleable" by changing our approach to the `ShapeStream` instantiation. I think this warrants opening a new issue and corresponding PR to discuss more thoroughly.
> fix: Handle 400 errors as unrecoverable

- .changeset/quiet-bees-prove.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test.tsx
Fixes https://github.com/electric-sql/electric/issues/1690
> fix: Clear react caches when stream is errored

- website/docs/api/clients/typescript.md
I went to share it with someone and it took a bit to find it & then I couldn't link directly to the custom parsing.
> chore(docs): Add sub-header for custom parsing in typescript docs

- .changeset/tall-chairs-punch.md
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
This commit addresses 2 issues:
First, the deadlock occurred when trying to add where clauses to existing tables - we executed `ALTER TABLE` that took out an exclusive access lock over one table definition, then executed `SET TABLES` on a publication that requested shared access lock over all tables mentioned in the publication which includes tables that are already exclusively locked by another concurrent shape creation. This caused a deadlock. This was addressed by switching the order of alter table and alter publication.
Second, there was a race condition when 2 new shapes tried updating the publication where clause and because it's done in a read-then-update way, not as a single statement, the read might have missed the concurrent update and the resulting state was wrong. This was …
> fix: address deadlock with concurrent snapshot creation

- examples/tanstack-example/package.json
- pnpm-lock.yaml
`forever` is getting this error:
```
> forever start src/server/app.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: src/server/app.js
(node:62642) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:62642) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
```
Forever hasn't been released in 3 years so I guess has accumulated enough bitrot to die.
We'll use concurrently instead.
> fix: use different way to start server in tanstack example

- .changeset/chatty-adults-heal.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/connection_setup.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/test/electric/replication/eval/runner_test.exs
Plus:
- set the db connection pool timeout to `:infinity` for snapshot creation (large datasets can timeout when writing the snapshot otherwise)
- set `LOG_OTP_REPORTS=true` to turn on SASL reporting at runtime
- add some more fine-grained log messages
- include some tests that validate our handling of nulls when evaluating array comparisons in where clauses
> Wrap more steps in snapshot with telemetry spans

- website/about/jobs/index.md
- website/about/jobs/pglite-engineer.md
- website/about/team.md
- website/data/activeJobs.data.ts
Jobs now have an `active: true | false` flag. Active: false but published means the job page is still visible for applicants to read.
I've also just unpublished the Airtable application form for the PGlite Engineer role.
> jobs: close PGlite Engineer and make listings dynamic.

- .changeset/sharp-moons-provide.md
- packages/sync-service/lib/electric/log_items.ex
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/log_item_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
- packages/sync-service/test/support/test_utils.ex
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/constants.ts
- packages/typescript-client/test/client.test.ts
With `replica=full` update messages include the full row, not just
the changed columns.
Phoenix.LiveView Stream integration requires the full row to perform an
update, not just the changed values. This adds a parameter to the shape
definition that turns off the column diffing for updates.
Since we were just dropping unchanged values this is a minor change to
the wiring. Most of the work here is adding the configuration.
> Add parameter to API to send entire row on update

- website/.vitepress/config.mts
- website/docs/api/http.md
- website/docs/guides/writing-your-own-client.md
See https://deploy-preview-1892--electric-next.netlify.app/docs/guides/writing-your-own-client
The URL format and headers have been updated to match the latest in https://github.com/electric-sql/electric/pull/1900
> docs: Writing your own client guide.

- .changeset/light-foxes-shout.md
- packages/elixir-client/lib/electric/client/shape_definition.ex
- packages/elixir-client/package.json
- packages/elixir-client/test/electric/client/shape_definition_test.exs
So that the electric phoenix gateway can drop client compatible opts into the front-end
> Add JSON output to shape params

- .github/workflows/ts_test.yml
- integration-tests/tests/_macros.luxinc
- packages/react-hooks/test/support/global-setup.ts
- packages/sync-service/.env.dev
- packages/sync-service/.env.test
- packages/sync-service/config/runtime.exs
- packages/typescript-client/test/support/global-setup.ts
Missed this when working on https://github.com/electric-sql/electric/issues/1927
> fix: also change DATABASE_ID to ELECTRIC_DATABASE_ID

- .github/workflows/elixir_client_tests.yml
- .github/workflows/elixir_tests.yml
- .github/workflows/integration_tests.yml
- .github/workflows/ts_test.yml
Currently we are successfully caching the MIX_ENV=test version, but some tests run with electric with MIX_ENV=dev, which results in a recompilation of deps and code.
> include MIX_ENV in cache keys

- .github/workflows/integration_tests.yml
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/multi-tenancy.lux
- integration-tests/tests/resuming-replication-at-consistent-point.lux
- integration-tests/tests/rolling-deploy.lux
This PR adds an e2e test for multi tenancy.
It checks:
- adding new tenants
- per-tenant health check
- initial sync works
- live queries work and does not interfere between tenants
- tenants are persisted and reloaded when Electric restarts
- tenants can be deleted
> chore: e2e test for multi tenancy

- .changeset/funny-spoons-trade.md
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/multi-tenancy.lux
- packages/sync-service/lib/electric/tenant_manager.ex
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/health_check_plug_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/tenant_manager_test.exs
- packages/sync-service/test/support/component_setup.ex
This PR applies the refactoring proposed by @icehaunter which consists of storing the tenant information in a protected ETS table. Any process can read the tenant information from the ETS table.
On every shape request the tenant information is loaded from the ETS table.
Concurrent shape requests can read this information from the ETS table concurrently.
Writes to the ETS table are less frequent (only when adding or removing tenants) and are still serialised through the tenant manager's genserver and thus are not prone to race conditions.
> chore (sync service): refactor tenant manager to store tenant info in ETS table

- .changeset/dirty-wolves-wash.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
When root table is missing it should return 400 with the correct message. Currently it is returning 500 which would lead to clients retrying even through the request is malformed.
> fix: Root table validation should return 400

- packages/typescript-client/README.md
- packages/typescript-client/src/client.ts
- website/docs/api/clients/typescript.md
e.g.
```tsx
const streamWithParams = new ShapeStream({
url: `${BASE_URL}/v1/shape`,
table: `foo`,
params: {
'custom-param': 'value'
}
})
```
> feat: let users add custom parameters

- examples/nextjs-example/.sst/platform/config.d.ts
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/__snapshots__/client.test.ts.snap
- packages/typescript-client/test/client.test.ts
did this wrong in #1978 so that combined with #1983, passing a reserved parameter just means it silently fails atm.
> fix: do validation for params off constructor so it can throw before starting

- .github/workflows/deploy_examples.yml
- examples/linearlite/sst.config.ts
- examples/nextjs-example/.sst/platform/config.d.ts
- examples/nextjs-example/sst-env.d.ts
- examples/nextjs-example/tsconfig.json
A small one to load initial data in Linearlite example
> examples: Linearlite load initial data

- .changeset/shiny-rules-drive.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/error.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/test/client.test.ts
- website/electric-api.yaml
Fixes https://github.com/electric-sql/electric/issues/1950
Questions:
- Are the headers only required on 2XX responses or also on other responses?
They are currently only being checked on 2XX responses.
- Are we checking *all* required headers?
Currently we check `electric-offset`, `electric-handle`, and `electric-schema`
> chore (ts-client): validate required Electric headers on response

- packages/cloud-sync-service/lib/cloud_electric/tenant_manager.ex
- packages/cloud-sync-service/test/cloud_electric/plug/delete_database_plug_test.exs
- packages/sync-service/lib/electric/connection/manager.ex
Following on from #1965 this drops the replication slot as well as the publication.
> Drop replication slot on database delete

- .changeset/bright-melons-pay.md
- packages/elixir-client/lib/electric/client.ex
- packages/elixir-client/lib/electric/client/fetch/request.ex
- packages/elixir-client/test/electric/client_test.exs
use `base_url` for the old behaviour of automatically appending `/v1/shape` and `endpoint` to explictly set the full URL of the shape api
Fixes #1992
> Allow for configuration of non-standard API endpoints

- website/.vitepress/config.mts
- website/data/activeJobs.data.ts
- website/data/use-cases.data.ts
- website/src/partials/sync-into-pglite.tsx
Previous matching was generating wrong blog structure (paths were split on arbitrary `-`), which led to "dead link" complaints. Also the `.split` of the path was wrong because preceding slash is not part of the file, but maybe that's incosistent between mac & linux so I replaced it with a definitely crossplatform call
> chore: fixed website builds

- website/docs/guides/troubleshooting.md
This PR documents the problem when Electric client complains about missing headers and how to solve it.
It was requested in https://github.com/electric-sql/electric/pull/1957 and that PR will need to be updated such that the error message refers to the section we add to the troubleshooting guide in this PR. Once this PR has been approved and the title of the subsection won't change we can add the link in the other PR.
TODO:
- Potentially add a code snippet showing proxy configuration. Although it seems that Caddy forwards the headers automatically unless you explicitly remove headers. So not sure if a snippet is needed, @KyleAMathews ?
> docs: document missing headers problem

- .changeset/strong-pumpkins-smoke.md
- packages/elixir-client/lib/electric/client/fetch/http.ex
This allows electric client to be used in non-https environments, such as local development, without additional configuration
> feat: allow http1 protocol on Electric client

- .changeset/grumpy-cougars-cheat.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/shape.ts
- packages/typescript-client/test/integration.test.ts
Fixes https://github.com/electric-sql/electric/issues/1996.
We remove `subscribeOnceToUpToDate` in favor of subscribing to the stream and "waiting" for the first `up-to-date` control message. **This is a breaking change.**
> feat! (ts client): Remove subscribeOnceToUpToDate from shape stream

- .changeset/clever-dots-admire.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
Fixes #1925 . Errors that occur while consuming the replication stream that are to do with a specific shape, cause that shape's consumer to remove the shape and shut down, leaving the other shapes unaffected.
Errors can occur:
1. In the selector which happens on a process common to all shapes. 
2. On the consumer process.
This PR addresses both types of error. Previous to this PR, these errors would cause the sync service to get into an infinite crash loop and would stop responding to HTTP requests.
> feat (sync-service): Prevent shape consumer errors from affecting other shapes

- .changeset/fair-pants-pretend.md
- .changeset/grumpy-cougars-cheat.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/support/global-setup.ts
- packages/react-hooks/test/support/test-context.ts
- packages/typescript-client/README.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/error.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/src/parser.ts
- packages/typescript-client/src/shape.ts
- packages/typescript-client/test/__snapshots__/client.test.ts.snap
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/parser.test.ts
- packages/typescript-client/test/support/test-context.ts
- website/docs/api/clients/typescript.md
Fixes https://github.com/electric-sql/electric/issues/1983
> fix: always throw errors & always use named Error classes

- .changeset/loud-peaches-mate.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/integration.test.ts
This PR modifies the `onError` handler that is supported by the shape stream such that it can recover from certain HTTP request errors. For example, if the HTTP request fails with a 401 because of an expired token, the handler could fetch a new token, and try again by returning the modified HTTP headers. The shapestream will then retry.
**Accompanying docs PR: https://github.com/electric-sql/electric/pull/2018**
> feat: enable error handler to recover from failed HTTP requests

- .github/workflows/deploy_examples.yml
This prevent the action from failing on main.
> Fix: only try to add comment to PR thread if we're on a PR

- .changeset/selfish-rings-mate.md
- packages/elixir-client/lib/electric/client/fetch/request.ex
- packages/elixir-client/test/electric/client/fetch/request_test.exs
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/test/fetch.test.ts
- packages/typescript-client/test/stream.test.ts
Closes https://github.com/electric-sql/electric/issues/2041
To be fair, by virtue of the clients having a fixed process by which the parameters are appended and updated they were already stable, but an explicit ordering step ensures that changes in the order of those operations don't break caching between versions, and is generally more explicit.
> feat(clients): Always order query params

- .changeset/silly-shoes-appear.md
- packages/sync-service/lib/electric/process_registry.ex
- packages/sync-service/test/electric/process_registry_test.exs
Ensures that we can hold connections when electric is not ready even if it is not started (useful in multi tenant)
> fix: Fix registry alive call

- packages/sync-service/lib/electric/shapes/consumer.ex
This PR addresses [Kyle's comment](https://github.com/electric-sql/electric/pull/2043#pullrequestreview-2461985569) and adds the replication lag to the current span instead of creating a new span.
> chore (sync service): add replication lag to current span

- .changeset/warm-brooms-approve.md
- packages/sync-service/lib/electric/shape_cache.ex
We have seen some issues related to https://github.com/lucaong/cubdb/issues/71 come up during recovery, and it currently causes issues with the whole electric.
Initially my thought was to delete the shape entirely if it fails, but perhaps as an initial workaround we might just want to log the error and continue recovery without the problematic shape?
> fix: Log error without falling over for failed recovery

- .changeset/hungry-apples-sell.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/crashing_file_storage.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/utils_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/support/test_storage.ex
Followup to https://github.com/electric-sql/electric/pull/2049
We are currently leaving folders behind when deleting shapes, which do take up a little bit of space and eventually could be a bit of an issue. This PR takes care of removing everything.
Additionally, when a shape fails to recover by not being able to start the consumer at all (see CubDB issue), the shape data is removed using a new method called `unsafe_cleanup!` which simply `rm -rf`s the shape directory. Not great to use while the shape is active as it can cause various bugs, but great for cleaning up.
> fix: Clean up shape folders and remove unrecoverable shapes

- website/.vitepress/config.mts
- website/.vitepress/theme/custom.css
- website/blog/posts/2024-07-17-electric-next.md
- website/docs/api/config.md
- website/docs/guides/deployment.md
- website/docs/guides/installation.md
- website/docs/guides/shapes.md
- website/docs/guides/writing-your-own-client.md
- website/docs/integrations/phoenix.md
- website/docs/reference/alternatives.md
- website/index.md
- website/product/cloud.md
- website/product/electric.md
- website/product/pglite.md
- website/public/_redirects
Less confusing -- we are ElectricSQL and our product is the Electric sync engine. Both "Electric" for short. Using the product title "Sync" was silly and confusing.
> website: rename `Sync` product to `Electric`.

- .changeset/nine-gorillas-rush.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
> Include cache headers in 304 responses

- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/telemetry.ex
The thing being measured here is the size of the WAL that Electric's replication slot retains, so I think the new name describes it better.
This change also restructures the code a bit to make the dependency on the DB connection pool crystal clear.
> Rename "replication lag" to "retained WAL size"

- examples/basic-example/README.md
- examples/basic-example/db/migrations/01-create_items_table.sql
- examples/basic-example/package.json
- examples/basic-example/src/Example.tsx
- examples/gatekeeper-auth/README.md
- examples/linearlite/README.md
- examples/nextjs-example/README.md
- examples/proxy-auth/README.md
- examples/redis-sync/README.md
- examples/remix-basic/README.md
- examples/tanstack-example/README.md
- examples/todo-app/README.md
- package.json
I've been working with the examples quite a lot and I've commonly experienced stale database and disk state from running `docker compose up` in the foreground followed by `ctl+c` to stop and also from forgetting to run `pnpm backend:down`.
So ... as a systemic solution, I've updated the `example-backend:up` script in the root package.json to always run `example-backend:down` first. This means that examples always start with a clean slate and no weird / stuck table and or disk state.
I also then did a pass through the example READMEs, explaining this and re-formatting the instructions a touch.
> examples: always start clean and update running instructions.

- .changeset/few-gorillas-fetch.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
Part of https://github.com/electric-sql/electric/issues/2032.
I removed 2 spans that seem redundant:
- `shape_write.log_collector.handle_txn`: this span wraps the `handle_transaction` function. However, there is already a span `pg_txn.replication_client.transaction_received` that in fact calls into `handle_transaction`.
- `shape_write.log_collector.handle_relation`: this span wraps the handling of relation messages. Similarly to transactions, there is a `pg_txn.replication_client.relation_received` span that ends up calling into the `handle_relation` function.
Here are the relevant code snippets:
`Electric.Postgres.ReplicationClient`:
```ex
{m, f, args} = state.transaction_received
OpenTelemetry.with_span(
"pg_txn.replication_client.transaction_received",
[num_changes: …
```
> chore (sync service): remove redundant spans

- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/telemetry/sampler.ex
Part of https://github.com/electric-sql/electric/issues/2032.
We noticed that most spans are descendants of the `pg_txn.replication_client.process_x_log_data` root span.
Therefore, we decided to only sample a portion of those spans.
This PR introduces a custom sampler that works as follows:
- Samples a configurable ratio of `pg_txn.replication_client.process_x_log_data` root spans
- Samples all other root spans
- Child spans are sampled if their parent is sampled
We would like to sample all errors.
To do this we need to make the sampling decision at the end of the span when we have all attributes and events because errors are recorded using an "exception" event, this is known as tail sampling. However, the Erlang opentelemetry library only seems to support head sampling:
> Sampling is …
> chore (sync service): probablistic sampling of transaction spans

- .changeset/sweet-timers-add.md
- packages/sync-service/.env.dev
- packages/sync-service/.env.test
- packages/sync-service/config/runtime.exs
Related documentation update - https://github.com/electric-sql/electric/pull/2067.
> Add ability to disable colored logs; rename logging-related env vars

- examples/nextjs-example/sst.config.ts
This allows easier identifications of the database for an app in the different stages. We're already doing this for Linearlite.
> Use stage for database name in examples

- .changeset/stupid-weeks-look.md
- examples/gatekeeper-auth/README.md
- packages/sync-service/lib/electric/connection/manager.ex
> Fallback to using unencrypted DB connection when possible

- packages/sync-service/test/electric/shapes/filter_test.exs
Follow up to #2076, based on @alco 's comments, this documents the optimisation tests.
> chore (sync-service): Add documentation for optimisation tests

- .changeset/tiny-socks-drive.md
- examples/basic-example/src/Example.tsx
- examples/linearlite/src/pages/Issue/Comments.tsx
- examples/linearlite/src/shapes.ts
- examples/nextjs-example/app/page.tsx
- examples/proxy-auth/app/page.tsx
- examples/redis-sync/src/index.ts
- examples/todo-app/src/routes/index.tsx
- packages/react-hooks/README.md
- packages/react-hooks/src/react-hooks.tsx
- packages/react-hooks/test/react-hooks.test-d.ts
- packages/react-hooks/test/react-hooks.test.tsx
- packages/typescript-client/README.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/shape.ts
- packages/typescript-client/test/client.test-d.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/stream.test.ts
- website/docs/api/clients/typescript.md
- website/docs/integrations/react.md
Fix https://github.com/electric-sql/electric/issues/2079
Electric's TypeScript client is currently tightly coupled to PostgreSQL-specific options in its `ShapeStreamOptions` interface. As Electric plans to support multiple data sources in the future, we need to separate protocol-level options from source-specific options.
1. Created a new `PostgresParams` type to define PostgreSQL-specific parameters:
- `table`: The root table for the shape
- `where`: Where clauses for the shape
- `columns`: Columns to include in the shape
- `replica`: Whether to send full or partial row updates
2. Moved PostgreSQL-specific options from the top-level `ShapeStreamOptions` interface to the `params` sub-key
3. Updated `ParamsRecord` type to include PostgreSQL parameters
4. Updated the `ShapeStream` class to …
> Move non-protocol options like table & where to the params sub-key

- .changeset/young-falcons-rest.md
- packages/react-hooks/src/react-hooks.tsx
The current behavior also clears them when there's an error which leads to an infinite loop with a bad stream being recreated over and over.
> fix: only clear the React stream/shape cache when the previous stream/shape was aborted

- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/querying.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
- packages/sync-service/test/electric/postgres/replication_client_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/querying_test.exs
This PR is an alternative to https://github.com/electric-sql/electric/pull/2077.
Instead of injecting the OTEL attributes and passing them around everywhere, we store each stack's OTEL attributes in a dedicated persistent term. When creating a span we lookup the OTEL attributes for that stack and add them to the span.
> chore (sync service): store OTEL attributes per stack in a persistent term

- packages/sync-service/lib/electric/stack_supervisor.ex
This PR improves the nimble spec for validating span attributes.
> chore (sync service): improve nimble spec for telemetry span attributes

- README.md
- examples/remix-basic/app/routes/_index.tsx
- examples/tanstack-example/src/Example.tsx
- website/docs/guides/deployment.md
- website/docs/guides/shapes.md
- website/docs/integrations/cloudflare.md
- website/docs/integrations/expo.md
- website/docs/integrations/netlify.md
- website/docs/integrations/supabase.md
- website/docs/quickstart.md
- website/src/partials/home-cta.md
- website/use-cases/state-transfer.md
Missed a few places where we need to update the switch to put the shape definition in the `params` key from https://github.com/electric-sql/electric/pull/2081
> docs: update shape definitions to use new `params` key.

- packages/sync-service/.env.dev
- packages/sync-service/.env.test
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/dynamic_consumer_supervisor.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/postgres/lock_connection_test.exs
- website/docs/api/config.md
Adds stack id & other useful metadata to all processes we spawn, and configures logger to actually print it
> feat: configure logging to be more explicit

- .changeset/modern-poets-film.md
- packages/typescript-client/src/fetch.ts
Fix https://github.com/electric-sql/electric/issues/2072
Not all implementations of JS have the `has(name, value)` syntax
> Use "get" instead of "has" for checking searchParams

- website/docs/api/config.md
Follow-up to #2067 and #2100. Fixing the config option naming before the beta release.
> Rename LOGGING to LOG in the docs

- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/dynamic_consumer_supervisor.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/telemetry/sentry.ex
This PR adds logger metadata as Sentry tags such that errors in Sentry can be searched/filtered on this metadata.
> chore (sync service): add logger metadata as Sentry tags

- packages/sync-service/lib/electric/telemetry/sentry.ex
This PR configures Sentry to also track logged errors and not only process crashes.
> chore (sync service): track errors with Sentry

- README.md
1. Minor NITs & formatting fixes
2. Add Table of Contents
3. Add a new tagline
> Update README: `It's like GraphQL, but for Postgres.`

- .changeset/polite-frogs-yell.md
- packages/elixir-client/lib/electric/client/offset.ex
- packages/elixir-client/test/electric/client/mock_test.exs
- packages/elixir-client/test/support/client_helpers.ex
- packages/react-hooks/test/react-hooks.test.tsx
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/replication/log_offset.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/crashing_file_storage.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/querying.ex
- packages/sync-service/mix.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/querying_test.exs
- packages/sync-service/test/support/test_storage.ex
- packages/typescript-client/test/integration.test.ts
This PR changes the way we write snapshots to disk, the storage API to request them, and some logic around offsets.
1. The `Storage.get_snapshot/1` method is gone. It's now unified under `Storage.get_log_stream/3`, with some caveats.
2. The offsets within the snapshot rows are not updated, so now latest item on the sent log may have mismatching `offset` field to the `electric-offset` header of the same response. All our clients respect the header, and that's the only correct behaviour going forward. There is a decision to remove `offset` from our items entirely, but that's a separate PR.
3. While we're making the snapshot, we cannot know how many chunks are going to be there until we make them. Thus we allow clients to request any chunks up to `LogOffset.new(0, :infinity)`, and consider …
> feat: introduce initial snapshot chunking

- pnpm-lock.yaml
- website/.npmrc
- website/package.json
I've noticed that the lock file sometimes flops between different versions.
This should lock (haha) that down.
> Fix: lock version of pnpm that we're using

- website/.vitepress/theme/custom.css
- website/product/cloud.md
- website/product/electric.md
- website/product/pglite.md
Minor one to merge when the BETA release is being made.
> website: mark products with status label.

- .changeset/fresh-beers-allow.md
- packages/elixir-client/lib/electric/client.ex
- packages/elixir-client/lib/electric/client/fetch.ex
- packages/elixir-client/lib/electric/client/fetch/http.ex
- packages/elixir-client/lib/electric/client/fetch/pool.ex
- packages/elixir-client/lib/electric/client/fetch/request.ex
- packages/elixir-client/lib/electric/client/fetch/response.ex
- packages/elixir-client/lib/electric/client/message.ex
- packages/elixir-client/lib/electric/client/stream.ex
- packages/elixir-client/test/electric/client_test.exs
Allows for a persistent connection per client rather than the default request coalescing behaviour.
Also expand replication stream messages with the timestamp of the actual HTTP request and the handle of the shape.
Basically enhancements for the load generation client to enable stats collection and improve the resume/reconnect behaviour.
> Add elixir client request pool behaviour

- .github/workflows/changesets_release.yml
- .github/workflows/deploy_examples.yml
- .github/workflows/teardown_examples_pr_stack.yml
- .github/workflows/ts_test.yml
- .tool-versions
- website/netlify.toml
We always should use `.tool-versions` as the authoritative source across the toolchain
> chore: make sure .tool-versions matches package.json

- .changeset/lucky-boats-lie.md
- packages/elixir-client/lib/electric/client/fetch/monitor.ex
- packages/elixir-client/lib/electric/client/fetch/pool.ex
- packages/elixir-client/lib/electric/client/fetch/request.ex
Fixes https://electricsql-04.sentry.io/issues/14068898/?project=4508410462404688&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=2
> Fix elixir-client race condition

- .changeset/lucky-cats-teach.md
- packages/sync-service/Dockerfile
- packages/sync-service/lib/electric/plug/health_check_plug.ex
- packages/sync-service/test/electric/plug/health_check_plug_test.exs
Before we were returning 503s for anything other than `active` status - for some health check services (like AWS Fargate) you can only rely on the status code, and technically Electric in `waiting` and `active` status is ready to accept requests, just not service them.
I've changed it so that:
- `waiting` and `starting` return 202, requests are accepted and held but failed after a timeout if not activated
- `active` returns 200
- `stopping` returns 503, we haven't implemented it yet anyway
Not sure if we should consider this a breaking change and how we handle releases at the moment @KyleAMathews .
> feat: Convert `waiting` and `starting` status to 202

- .github/workflows/benchmarking.yml
- .github/workflows/benchmarking_dockerhub_tags.yml
Fixes the CI benchmarks by including the newly added `where_clause` field.
> (chore) Fix CI benchmarks

- packages/sync-service/Dockerfile
It means it will be slightly slower to turn `healthy` but that's ok
> fix: Remove `--start-interval` as it is a relatively recent docker feature

- .changeset/beige-mice-notice.md
- packages/elixir-client/lib/electric/client/fetch/monitor.ex
- packages/elixir-client/lib/electric/client/mock.ex
- packages/elixir-client/test/electric/client_test.exs
Fixes race condition where the monitoring process would start, initialise the request process, and the request would complete before the listener registered itself with the monitoring process.
This would normally trigger an error and a retry, so overall it's not a critical bug for production, but in our tests where our responses are mocked exactly once, if a response was missed the test would time out.
My approach was to "hold" the response in the monitor until at least one subscriber is present - I don't love it cause then for the monitor to shut down it needs to have something registered to it after initialization, but it felt like a decent fix with the assunmption that each monitor process will be accompanied with a registration.
> fix(elixir-client): Fix monitoring registration race condition

- packages/sync-service/README.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric.ex
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/lib/electric/telemetry/call_home_reporter.ex
- packages/sync-service/test/electric/config_parser_test.exs
- packages/sync-service/test/electric/config_test.exs
Refactor app config to make most values optional.
Except for connection_opts, all the config settings have defaults. When embedding electric inside another elixir app, our runtime.exs won't be sourced so the developer would be forced to unnecessarily set all these configuration values.
Moves the default values from runtime.exs to the point of usage so we don't have defaults in two places.
> Simplify configuration of the electric app

- .github/workflows/elixir_tests.yml
- packages/sync-service/dev/docker-compose.yml
- packages/sync-service/test/support/db_setup.ex
Had to trim the unique test db names, for some reason Postgrex was failing otherwise with pg17 (used short hashes to improve uniqueness guarantee)
> chore: Add pg17 to test matrix

- .changeset/breezy-boats-tease.md
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_setup.ex
- packages/sync-service/test/support/transaction_case.ex
I ran tests individually and in groups with many repetitions until failure to find flaky spots, and also went over the CI logs to see tests that failed, and made some changes to fix that.
Main test changes:
- Unique per-test publication when using `:with_publication` using test name based hash
- Use per test `:with_shared_db` for `TransactionCase` - otherwise connections are not closed in time and we run into too many clients issues
- Longer time to get `:ready` message when spinning up full stack - on CI you can see that sometimes the logs indicate that we're _almost_ ready but it times out with the default
Actual code changes:
- Stop trapping exits in the `Shapes.Consumer`, we don't handle it in `handle_info` and I think it was leftover from when I was doing termination cleanups. I …
> chore: Fix more Elixir test flakes

- .changeset/wicked-papayas-tease.md
- packages/typescript-client/README.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/test/client.test-d.ts
- packages/typescript-client/test/client.test.ts
- website/docs/api/clients/typescript.md
- website/docs/guides/auth.md
Fix https://github.com/electric-sql/electric/issues/2181
This PR adds support for function-based options in the TypeScript client's params and headers. Functions can be either synchronous or asynchronous and are resolved in parallel when needed.
```typescript
const stream = new ShapeStream({
url: 'http://localhost:3000/v1/shape',
params: {
table: 'items',
userId: () => getCurrentUserId(),
filter: async () => await getUserPreferences()
},
headers: {
'Authorization': async () => `Bearer ${await getAccessToken()}`
}
})
```
- Authentication tokens that need to be refreshed
- User-specific parameters that may change
- Dynamic filtering based on current state
- Multi-tenant applications where context determines the request
We chose to implement this using direct function values rather than a …
> feat: let users pass sync/async functions for resolving option values for headers/params

- .github/workflows/changesets_release.yml
- package.json
- pnpm-lock.yaml
- scripts/tag-latest.mjs
Changeset doesn't allow custom tags with prereleases 🤷 https://github.com/changesets/changesets/issues/546
> fix: run dist-tag after changeset publish to set latest tag on npm

- .gitignore
- examples/bash/README.md
- examples/bash/client.bash
https://github.com/user-attachments/assets/e91888ac-f659-44ab-9a28-350055ed787d
> fix bash example client to work with latest server

- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/telemetry.ex
While I was testing the shut down of `Electric.Connection.Supervisor`, I saw errors getting logged when one of telemetry_poller's probes timed out on a `GenServer.call()` to the connection manager. The thing is, we didn't even need telemetry poller running in that scenario.
> Do not start telemetry_poller when no metric exports are configured

- packages/sync-service/lib/electric/connection/manager.ex
Fixes #1960.
I have manually verified that attempts to restore the replication connection now respect exponential backoff and that it eventually connects if I stop the other Electric instance that was holding the replication slot.
> Use exponential backoff when restoring a crashed replication connection

- packages/sync-service/lib/electric/process_registry.ex
By massaging options inside child_spec's definition we make the module behave differently when its start_link() function is called directly (during manual or automated testing) compared to when it's started by a supervisor.
> The child_spec() function should not contain any logic

- .changeset/stale-bats-tickle.md
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/test/electric/replication/eval/runner_test.exs
> fix(sync-service): Fix bug with logical operators with 3 or more arguments

- .changeset/ten-socks-promise.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/plug/utils.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/postgres/inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/dispatcher.ex
- packages/sync-service/lib/electric/shapes/filter.ex
- packages/sync-service/lib/electric/shapes/partitions.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/postgres/inspector/ets_inspector_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/dispatcher_test.exs
- packages/sync-service/test/electric/shapes/filter_test.exs
- packages/sync-service/test/electric/shapes/partitioned_tables_test.exs
- packages/sync-service/test/electric/shapes/partitions_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/stub_inspector.ex
- website/docs/guides/shapes.md
Allows for subscribing to partitions of a partitioned table (which you could already do) but also subscribing to the root, partitioned, table and receiving all updates across all partitions.
Fixes #2118 
Major changes:
- Add support for partitioned table types in the various inspector queries
- Include partition hierarchy information in relation information from pg and in inspector relation info
- Force reload of table information when receiving a new relation that is a partition
- Add partition information to `Filter` so that it can correctly pass on a change on a partition table to a shape on the partition root.
- For a shape subscribed to the partition root, changes coming in on partitions will be re-written so that their relation matches the partition root. The change `key`s are not …
> Add partitioned tables support

- website/docs/guides/troubleshooting.md
It appears that you now (at least on my machine) need to specify the `localhost` host name in the caddy file to get it to properly enable tls.
> docs: Fix caddy reverse proxy docs

- examples/linearlite-read-only/sst.config.ts
- examples/nextjs/sst.config.ts
Previous was wrong and redundant, as the stage specified in CI is `production` not `Production`
> chore: Simpler example stage DB naming

- .changeset/mighty-monkeys-marry.md
- packages/elixir-client/lib/electric/client/fetch/monitor.ex
rather than complex logic around subscriber vs response ordering (which was fallible), simply don't launch the request until we have at least one subscriber
@msfstef this was causing flaky tests in the cloud repo
> fix race condition when using mock backend

- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/test/electric/telemetry_test.exs
Telemetry uses `:memsup.get_system_memory_data/0` to collect memory stats however this call is OS specific and causes the telemetry tests to fail when run on macOS. This PR allows memory stats to gathered regardless of the OS, albeit gathering less stats on macOS.
> (chore) Fix telemetry tests on macOS

- packages/sync-service/test/electric/postgres/configuration_test.exs
This PR fixes the sporadic test that can be seen failing here:
https://github.com/electric-sql/electric/actions/runs/12934429277/job/36075427601
I've also added the cause to slab so that we can hopefully prevent this kind of issue in the future:
https://electric-sql.slab.com/posts/sporadically-failing-elixir-tests-pfyia5on?shr=vrDh-k20QJMXaygzaPfMu4J4
> (chore): Fix sporadically failing test due to capture_log

- .changeset/healthy-seas-bathe.md
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
The `recover_shape` and `refresh_publication` are in the `init` path of `ShapeCache`, and there is no reason why we would be waiting for responses.
The `recover_shape` has no expected failure as it simply updates a map with appropriate counters.
The `refresh_publication` will schedule a publication update, but we don't have to wait for it to finish to consider `ShapeCache` ready, as the shape consumers are already up and running and any new shapes will trigger another publication update after this one.
These changes are based off of Sentry errors noticed from the cloud.
I've also set the publication update debounce time to 0ms, so now it simply waits until end of current process message queue. This addresses an unnecessary delay in `prepare_table` calls (@robacourt), since even when there …
> fix: Do not await for responses when recovering pub filters

- .changeset/seven-files-thank.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/test_storage.ex
When cleaning up a shape we call `cleanup!` and (in the case of FileStorage) attempt to remove the data directory while the CubDb process is still running.
This fails (`File.rm_rf/1` returns `{:error, :eexist, _}`) because the files are still in use. 
Instead of removing the directory on `cleanup!` while the process(es) are still running, instead teardown the consumer supervision tree and use `unsafe_cleanup!/1` do remove the directories. 
`unsafe_cleanup!` is already documented as something that should be runnable without any active processes, so this is an ideal use.
Fixes problems with https://github.com/electric-sql/stratovolt/pull/243
> Use `unsafe_cleanup!/1` to delete data after consumer has stopped

- .changeset/curly-horses-hear.md
- packages/sync-service/lib/electric/connection/manager.ex
When `DATABASE_USE_IPV6` is enabled, but the provided DB URL has no resolvable IPv6 address (no AAAA record), naively fallback to IPv4.
A more general discussion on this fallback behaviour for Erlang's networking stack can be found here https://github.com/erlang/otp/issues/8548
Ideally we would be able to handle this sort of fallback directly with Postgrex, and it used to have the possibility to specify multiple endpoints with different options that it would try sequentially, but it is no longer supported.
I have opened an issue to see if there is a potential solution to this that can be supported by Postgrex directly https://github.com/elixir-ecto/postgrex/issues/730
Perhaps once we are happy with both IPv6 and IPv4 being supported out of the box we can remove the `DATABASE_USE_IPV6` …
> fix: Fallback to IPv4 from IPv6

- .changeset/smooth-lions-joke.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/dispatcher.ex
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/test/electric/shapes/dispatcher_test.exs
- packages/sync-service/test/support/transaction_consumer.ex
This PR improves observability by:
- Connecting shape consumer spans to replication traces
- Adding `electric.shapes.total_shapes.count` metric to OTEL metrics (Closes #2269 although I have not added "shapes that have an active subscriber" as this information is already available in the traces)
- Adding `electric.storage.used` metric to OTEL metrics
- Adding CPU % utilisation per core telemetry and exposing them to the OTEL metrics. CPU metrics are already available, but % utilisation per core seems a simple one to comprehend and in a form our customers will understand.
> feat(sync-service): Connect shape consumer spans to replication traces and add OTEL metrics

- packages/sync-service/lib/electric/connection/manager.ex
Fixes issue introduced in https://github.com/electric-sql/electric/pull/2283
The passthrough would not work and if an error came through that wasn't `:nxdomain` it would enter an infinite loop (whoops).
I've added the case of an error where network is unreachable that @samwillis run into, assuming it's because IPv6 is not enabled on the machine, but am reluctant on disabling IPv6 on _all_ `DBConnection` errors or tcp errors.
We definitely do not want to make IPv6 enabled by default until we sort this out.
> fix: Passthrough errors to avoid infinite loop when falling back to IPv4

- .changeset/brown-poems-watch.md
- .changeset/sixty-queens-agree.md
- .changeset/sweet-yaks-jog.md
- packages/elixir-client/lib/electric/client/message.ex
- packages/elixir-client/lib/electric/client/stream.ex
- packages/elixir-client/test/electric/client/value_mapper_test.exs
- packages/elixir-client/test/electric/client_test.exs
- packages/sync-service/lib/electric/log_items.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/file_storage/log_file.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/querying.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/log_item_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/shape_cache/file_storage/compaction_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shapes/querying_test.exs
- packages/sync-service/test/support/test_utils.ex
- packages/typescript-client/src/types.ts
- packages/typescript-client/test/integration.test.ts
- website/electric-api.yaml
Closes #2214 
Removes `offset` property from all messages going forward. This simplifies the wire protocol as currently we had discrepancies between in-item offsets and header offsets when working with chunked initial snapshot. Now headers are the only correct way to work with the offsets. This is reflected in client libraries.
Adds two headers to *live* (i.e. non-snapshot, not-compacted) changes: `lsn` and `op_position`. The `lsn` marks items in the same transaction and provides a monotonic system-wide value for common prefix calculations. It will be heavily used in further PRs. The `op_position` lists an operation's order in the original transaction, allowing correct operation ordering when merging and applying 2 shape streams together without a need for a topological sort.
> feat!: remove `offset` and add `lsn` header on the wire

- .changeset/breezy-knives-bow.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/manager/connection_backoff.ex
- packages/sync-service/test/electric/connection/manager/connection_backoff_test.exs
The sign of the total retry time was reversed. Lack of tests -> dumb mistakes.
Is there any reason we don't have a test suite for the `Connection.Manager`? It's a bit of an overhead to set it up, I've separated the `ConnectionBackoff` logic to basically just slightly enhance `:backoff` with total retry time and reverted the rest of the logic in the connection manager to be how it was (probably was the best option to start with).
> fix: Fix total retry time from reconnnection attempts

- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/mix.exs
> Add missing metric gathering to the telemetry poller config

- .changeset/lemon-taxis-stare.md
- integration-tests/tests/invalidated-replication-slot.lux
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
The StackSupervisor will shut itself down as a consequence.
In a multi-tenant setup, this effectively shuts down a single tenant while allowing the other tenants to keep chugging along.
Closes #2178.
> Shut down the connection supervisor in case of an unrecoverable replication error

- .changeset/shy-bags-deliver.md
- packages/react-hooks/package.json
Closes https://github.com/electric-sql/electric/issues/2315
Looser requirement for the peer dependency to avoid the reported warnings with v19 react. We ideally want to be testing it with multiple major react versions though to make sure we actually support them.
> fix: Looser `react` peer dependency versions

- integration-tests/tests/invalidated-replication-slot.lux
- packages/sync-service/lib/electric/stack_supervisor.ex
Monitor the stack supervisor process to guarantee its eventual shutdown. Previously, it might not have shut down in time before the liveness check performed in the integration test.
> More determinism in the invalidated-replication-slot.lux test

- .changeset/funny-hairs-grab.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/mix.exs
The `runtime: false` option in mix.exs was the wrong one to use: it excluded the dependency from release packaging, resulting in the release startup failure when `ELECTRIC_USAGE_REPORTING=true`.
The correct way to make telemetry_poller's default reporting disabled is to configure it as such.
Fixes https://github.com/electric-sql/electric/issues/2323.
> Bring back the inclusion of telemetry_poller in releases

- packages/sync-service/.env.dev
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/shapes/filter.ex
- packages/sync-service/lib/electric/shapes/filter/index.ex
- packages/sync-service/lib/electric/shapes/filter/table.ex
- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
- packages/sync-service/lib/electric/telemetry/optional_spans.ex
- packages/sync-service/lib/electric/telemetry/sampler.ex
- packages/sync-service/test/electric/telemetry/open_telemetry_test.exs
To diagnose slow where clause filtering this PR introduces 3 new optional filter spans:
- `filter.filter_using_indexes` - how long index based filtering takes. Attributes: table and index count
- `filter.filter_other_shapes` - how long non-index based filtering takes. Attributes: table and shape count
- `filter.index.filter_matched_shapes` - how long filtering the matched shapes takes after the change has matched an index. Attributes: field, matched_shape_count
In order to do this, this PR also introduces:
- Optional spans (see the `OptionalSpans` module)
- Open Telemetry Baggage propagation between processes. This reduces noise in the code by not requiring `stack_id` to be passed around to everywhere we do tracing.
- Changed the shapes collection in the index from a list to a map, this …
> feat(sync-service): Add optional where clause filtering tracing

- website/docs/guides/deployment.md
Fairly certain that the original author meant `throughout`
> chore(docs): Update typo in Deployment guide

- .changeset/popular-shrimps-ring.md
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
- packages/sync-service/lib/electric/telemetry/opts.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
Following @msfstef 's comments on [this PR](https://github.com/electric-sql/stratovolt/pull/311) - This PR separates the telemetry config from application environment config
> chore(sync-service): Isolate telemetry config

- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/crashing_file_storage.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/pg_interop/postgrex/extensions/pg_snapshot.ex
- packages/sync-service/lib/pg_interop/postgrex/types.ex
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/pg_interop/postgrex/extensions/pg_snapshot_test.exs
- packages/sync-service/test/support/db_setup.ex
- packages/sync-service/test/support/test_storage.ex
Electric now stores the full pg snapshot info in the shape snapshot. Transaction filtering logic is then improved to skip additional transactions that are already included in the snapshot.
This change is backwards-compatible with existing shapes.
Fixes #2313.
> Fix transaction filtering by taking into account snapshot's xmax and xip_list

- .changeset/fuzzy-dingos-doubt.md
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/test/electric/shape_cache/file_storage/compaction_test.exs
- packages/sync-service/test/electric/shape_cache/file_storage/key_index_test.exs
- packages/sync-service/test/electric/utils_test.exs
When the input file is small enough to fit into a single chunk. The problem is that `File.stream!`, by default, looks for line break characters and normalizes any `\r\n` into `\n` when reading from the file. So the data it writes into the target file is different from the one it read from chunk_0 if it so happens that the latter has the sequence of bytes `<<13, 10>>` in it.
> Fix file corruption in Electric.Utils.external_merge_sort()

- .changeset/wet-zebras-laugh.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
Fixes https://github.com/electric-sql/stratovolt/issues/299
It's a bit confusing because we use the same attirbute names elsewhere and use different values (e.g. `"shape.root_table"` is also added as a span in `Electric.Shapes.Consumer`, but there it uses the namespaced tuple instead of the request provided table).
Right now they are coming in as `nil` because there is no such thing as a `:shape` key in the parameters, so I'm changing this to at least always try and include something.
This populating of attributes happens both at the start of the request and at the end - I always try to use the raw query parameter value, because it should always be available and it is what we will try to correlate to request spans from proxies etc. I have the parsed parameter fallback but I'm not sure if …
> fix: Ensure shape info is added to OTEL spans in shape requests

- packages/sync-service/README.md
The format for the version couldn't resolve:
> Because your app depends on electric >= 1.0.0-beta-1 which doesn't match any versions, version solving failed.
> ** (Mix) Hex dependency resolution failed
> Fix version format in README.md

- .changeset/lazy-cameras-clap.md
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
Fixes https://github.com/electric-sql/electric/issues/2360
This will make the running Electric fallback to replicating whole tables if it receives any shapes with unsupported where clauses (e.g. enums, varchar with `IN` checks, user-defined data types in general, and who knows what else).
There is no "recovery" mechanism to return to row-filtering as the Postgres error does not allow for an easy way to check which where clause caused the issue - once we go to relation-only filtering we stay there, like we would if an active shape had no where clause or if we were in PG14.
Ideally we would detect where clauses that are unsupported at the relation filter processing level, so we can fine tune that, but until then this fallback makes sure that Electric works even if an unsupported where …
> feat: Fallback to include whole table in replication if where clauses unsupported

- .changeset/mean-lies-kiss.md
- .changeset/twelve-jeans-admire.md
- packages/sync-service/lib/electric/shapes/filter.ex
- packages/sync-service/lib/electric/shapes/filter/index.ex
- packages/sync-service/lib/electric/shapes/filter/indexes/equality_index.ex
- packages/sync-service/lib/electric/shapes/filter/indexes/inclusion_index.ex
- packages/sync-service/lib/electric/shapes/filter/table.ex
- packages/sync-service/lib/electric/shapes/filter/where_condition.ex
- packages/sync-service/mix.exs
- packages/sync-service/test/electric/shapes/filter_test.exs
This PR seeks to address trigger.dev's WAL lag issues by adding two optimisations to where clause filtering:
- Allow multiple conditions in a where clause to be optimised (not just one)
- Optimise where clauses that have a condition in the form 'array_field @> array_const'
This feature alone should halve the processing time for trigger.dev as they have many where clauses in the form `WHERE runtimeEnvironmentId = ? AND batchId = ?` where if a change matched the `runtimeEnvironmentId` it would then have to iterate through the `batchId`s. Now it doesn't - the `batchId` condition is indexed as well.
Trigger.dev's other problematic where clauses are in the form `WHERE runtimeEnvironmentId = ? AND runTags @> ?` and this feature optimises the `@>` operation. The algorithm for this optimisation …
> feat(sync-service): index for array contains

- .changeset/brown-plants-count.md
- packages/elixir-client/config/runtime.exs
- packages/sync-service/config/config.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/process_registry.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/utils.ex
- packages/sync-service/mix.exs
- packages/sync-service/test/test_helper.exs
- remove the requirement to obfuscate db connection passwords in your config. in e.g. dev mode it's common to just have your db creds in config/dev.exs where you don't have access to the functions in electric. so rather than raise in this common scenario, just make the obfuscate_password function idempotent and apply it every time
- make the library mode the default
- add functions to application to get a proper configuration with the possibility of overrides
- make long_poll_timeout configurable because, why not? everything else is....
> sync-service: make configuration easier and more accessible 

- .changeset/seven-guests-appear.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/shapes/api/params.ex
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
- Api.predefined_shape/2 allows for configuring an endpoint with a pre-defined shape
- All http logic is now encapsulated by the api, including not-modified handling and cache-control headers
> sync-service: improve shapes api encapsulation

- .changeset/few-trains-kick.md
- packages/sync-service/Dockerfile
- packages/sync-service/lib/electric/plug/router.ex
- packages/sync-service/lib/electric/plug/utility_router.ex
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
- packages/sync-service/lib/electric/telemetry/call_home_reporter.ex
- packages/sync-service/lib/electric/telemetry/sampler.ex
- packages/sync-service/lib/electric/telemetry/sentry.ex
- packages/sync-service/lib/electric/telemetry/sentry_req_http_client.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
- packages/sync-service/mix.exs
configure telemetry dependencies to only be included when building the `application` target and do compile-time checks to exclude certain modules when compiling without telemetry
uses both checks against Mix.target() and checks for the presence of dependent modules to make compilation and runtime robust when running as docker application, local dev server and when used as a dependency
having said that, a better solution would be to move the telemetry to a separate library and have it included when needed but this solves the main problem of un-wanted telemetry dependencies being included (and needing configuration) when electric is included as a dependency
> sync-service: only include telemetry dependencies and processes in application target build

- .changeset/old-tigers-collect.md
- .changeset/serious-clouds-thank.md
- packages/experimental/package.json
- packages/experimental/src/index.ts
- packages/experimental/src/multi-shape-stream.ts
- packages/experimental/test/multi-shape-stream.test-d.ts
- packages/experimental/test/multi-shape-stream.test.ts
- packages/experimental/test/support/test-context.ts
- packages/typescript-client/src/client.ts
- pnpm-lock.yaml
This adds two new APIs to the @electric-sql/experimental package:
A multi-shape stream is a stream that can subscribe to multiple shapes. It ensures that all shapes will receive at least an `up-to-date` message from Electric within the `checkForUpdatesAfter` interval.
The emitted messages have an additional `shape` prop that is the name of the shape provided in the shapes object when constructing the `MultiShapeStream`.
```ts
const multiShapeStream = new MultiShapeStream({
shapes: {
shape1: {
url: 'http://localhost:3000/v1/shape1',
},
shape2: {
url: 'http://localhost:3000/v1/shape2',
},
},
})
multiShapeStream.subscribe((msgs) => {
console.log(msgs)
})
// or with ShapeStream instances
const multiShapeStream = new MultiShapeStream({
shapes: {
shape1: new ShapeStream({ url: …
```
> feat(experimental): MultiShapeStream and TransactionalMultiShapeStream APIs

- .changeset/modern-chicken-juggle.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/debug/process.ex
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
- packages/sync-service/lib/electric/telemetry/opts.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
Adds ability to send metrics to Honeycomb that break down process memory use by process type. 
This is optional telemetry as it creates a significant amount of extra chargeable metric units in Honeycomb. It's off by default but can be turned on with `ELECTRIC_OTEL_PER_PROCESS_METRICS=true` and the amount of chargeable metric units reduced by reducing `ELECTRIC_OTEL_EXPORT_PERIOD` and `ELECTRIC_TELEMETRY_TOP_PROCESS_COUNT`.
> feat(sync-service): Add option to send memory metrics per process type

- website/electric-api.yaml
I haven't verified all possible response formats but these changes bring the documentation in line with what we have in the tests under `test/electric/plug/serve_shape_plug_test.exs`.
> Update the OpenAPI spec to match the actual response format of 409 errors

- packages/typescript-client/test/client.test-d.ts
- website/docs/api/clients/typescript.md
I copy/pasted this from the docs and was stumped for a while why things weren't working
> Fix timestampz typo

- .changeset/few-cougars-judge.md
- .changeset/silver-mirrors-jump.md
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- website/electric-api.yaml
Closes https://github.com/electric-sql/electric/issues/2361
Also makes the `location` header in 409 responses carry over the full shape query as the original shape.
> fix: Correct OpenAPI spec for 409

- .changeset/blue-pears-worry.md
- packages/typescript-client/src/fetch.ts
Closes https://github.com/electric-sql/electric/issues/2334
Listener gets cleaned up if:
- Parent signal is aborted (because of the `once: true` setting)
- Chained abort controller calls `abort` (because of the `signal: aborter.signal` setting)
- The `cleanup` callback is used, which we do at the end of the request that uses this chaining
This should take care of any potential leaks due to listeners.
> fix: Clean up chained abort signal listener

- .changeset/strange-snails-hug.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/dispatcher.ex
- packages/sync-service/lib/electric/shapes/filter.ex
Trigger.dev is getting WAL lag due to electric's replication stream processing being slow, we know it's inside the `pg_txn.replication_client.transaction_received` span but it's not where clause filtering or anything on the shape specific processes (e.g. writing to disk). This PR adds attributes to the `pg_txn.replication_client.transaction_received` span that time various parts of that processing to pintpoint the area of slowness.
> feat(sync-service): Add telemetry to time various parts of the WAL processing

- .changeset/chilled-papayas-draw.md
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/test/electric/shapes/api_test.exs
Closes https://github.com/electric-sql/electric/issues/2289
It seems that connections are being handled by a process pool of sorts, which means that they are never removed from the registry.
>Within a Bandit server, an HTTP/1 connection is modeled as a single process. This process is tied to the lifecycle of the underlying TCP connection; **in the case of an HTTP client which makes use of HTTP's keep-alive feature** to make multiple requests on the same connection, **all of these requests will be serviced by this same process**.
This is from [Bandit's docs](https://github.com/mtrudel/bandit/blob/main/lib/bandit/http1/README.md) and I've verified it by reproducing @magnetised 's situation described in the issue.
I initially used an approach where an ephemeral process/`Task` is the one …
> fix: Avoid long-lived listeners for changes due to connection process reuse

- .changeset/dirty-humans-press.md
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/support/test-helpers.ts
Found out that live requesters would get the _entire_ transaction regardless of its size while I was working on making the TS tests less flaky.
I've modified the TS chunk test to test chunking both of the initial snapshot and subsequent transactions, without arbitrary `sleep` calls, so it was ending up doing a live request and noticed I was getting a single >40kb response unless I "slept" a bit before requesting such that it was not a live request.
The required change is really small, we just look for the chunk log offset once we receive new changes.
> fix: Return chunked responses to live requesters

- .changeset/lazy-carrots-guess.md
- packages/sync-service/lib/electric/postgres/lsn.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/support/transaction_consumer.ex
Fixes transactions getting dropped incorrectly because of invalid LSN comparisons, introduced in https://github.com/electric-sql/electric/pull/2382
> Fix incorrect LSN comparisons

- packages/sync-service/lib/electric/replication/shape_log_collector.ex
Following on from #2423 , this fixes another comparison.
> Fix LSN comparison

- packages/experimental/test/multi-shape-stream.test.ts
- packages/experimental/test/support/test-context.ts
- packages/experimental/test/support/test-helpers.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/support/test-context.ts
- packages/typescript-client/test/support/test-helpers.ts
Replaces unnecessary `sleep` calls intended to wait for transactions to get processed and go through the sync service with a `waitForIssues` test method, which starts a stream and waits for a given number of changes to go through.
I've added a manual `Process.sleep(200)` in the `process_x_log_data` call where we process the replication stream to simulate slow replication and render all the arbitrary `sleep` calls invalid, and then went through the failing tests one by one and made changes such that they work regardless of these delays that occur in CI.
> chore: Fix flaky TS tests

- .changeset/smart-apples-stare.md
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
for embedded electric, in dev mode we don't want the browser to cache responses because it causes problems with restarts/migrations etc, so add a flag to just turn them off.
also includes allowing configuration of the stack_ready_timeout and a higher default for that (was 100ms which is a bit harsh)
> Add config option to disable cache headers

- integration-tests/scripts/electric_dev.sh
- integration-tests/tests/installation-id-persistence.lux
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
- packages/sync-service/lib/electric/telemetry/opts.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
An integration test to verify the persistence and a matching change in cloud are coming up as follow-up PRs.
> Generate and store installation_id to maintain metric continuity between restarts

- website/src/components/BlogPostHeader.vue
I noticed that the publication dates on the blog posts were not updated correctly on navigation.
The date loads correctly on the first page, but is not updated on navigation.
**Reproduction**:
1. Go to https://electric-sql.com/blog/2022/05/03/introducing-rich-crdts
See this:
2. Navigate to the first blog post in the list, see this:
> fix: make blog post publication date update on navigation

- .github/workflows/elixir_tests.yml
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/test_helper.exs
"Graceful" here means we return a 500 with a clear error, and next request will succeed if that one can take out a lock. That's instead of crash that leaves the system in unrecoverable state. Closes #2403
> fix: ensure graceful crash when `ALTER TABLE` can't take a lock

- .changeset/flat-hornets-ring.md
- .github/workflows/elixir_tests.yml
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/pooled-connections.lux
- packages/sync-service/.env.test
- packages/sync-service/README.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/dev/docker-compose.yml
- packages/sync-service/dev/pgbouncer.ini
- packages/sync-service/dev/userlist.txt
- packages/sync-service/lib/electric.ex
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_setup.ex
- website/docs/api/config.md
- website/docs/guides/deployment.md
Closes https://github.com/electric-sql/electric/issues/1885
- Introduce separate env var `ELECTRIC_QUERY_DATABASE_URL`
- Add another `connection_opts` field to `replication_opts`, so there are two of them
- Fallback to using the same ones, but still keep them separate and maintain them separately
- Main disadvantage of this approach is that the fallbacks for SSL and IPv6 might need to happen twice if a separate connection string is not being used - this can be improved by only populating the `replication_opts`'s `connection_opts` right before starting the replication client with the single `connection_opts` available if a separate one was not provided.
- Make all tests (e.g. router tests) use a `pgBouncer` connection string
- Had to ensure connections are terminated explicitly at the end …
> feat: Implement separate, potentially pooled `ELECTRIC_QUERY_DATABASE_URL`

- .changeset/wet-melons-cry.md
- packages/experimental/src/bigint-utils.ts
- packages/experimental/src/multi-shape-stream.ts
- packages/experimental/test/bigint-utils.test.ts
- packages/experimental/test/multi-shape-stream.test.ts
- packages/sync-service/lib/electric/log_items.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/test/electric/log_item_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
Follow-up to https://github.com/electric-sql/electric/pull/2442
Randomizing the WAL start point in tests has highlighted problems with how we handle LSNs in Javascript.
Javascript can only do max 53-bit number representations, after which it will start doing nonsense without telling you (gotta love it), but LSNs span the entire 64-bit range.
In order to fix that, we encode the `lsn` and `global_last_seen_lsn` as strings in the responses rather than integers, so that Javascript can either compare them as strings or convert them to `BigInt`s, both would yield valid comparisons.
JSON itself does not really care, and other languages are able to parse large integers correctly, but for the sake of portability in the current landscape I think it's better to keep it encoded only once and as a …
> Fix LSN encoding in responses and handling in JS

- packages/sync-service/lib/electric/plug/router.ex
In certain environments, e.g. when running in a cloudflare tunnel, the `server` header that we set to `"ElectricSQL/#{version}"` gets overwritten by cloudflare with the value `"cloudflare"`. This PR renames the response header to `electric-version` to avoid this and improve visibility.
**Should we mark this as a breaking change or not?**
If someone relies on this header it is in theory a breaking change.
Or we could keep the `server` header and also introduce the `electric-server` header.
> chore: Rename server header to electric-server

- .changeset/big-candles-approve.md
- packages/sync-service/lib/electric/replication/changes.ex
- packages/sync-service/lib/electric/replication/eval/expr.ex
- packages/sync-service/lib/electric/replication/persistent_replication_state.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/replication/shape_log_collector/affected_columns.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/lib/electric/shapes/querying.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector/affected_columns_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/filter_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
We have a process setup where we have 2 layers of supervisors which store entire child spec of their children as state, plus the `ShapeLogCollector` that the shape consumers register with, plus the consumers themselves -- all these processes happen to have shapes in their state. _Arguably, we can inject shapes into consumers bypassing supervisors, but that's a different PR._ These shapes, however, happened to know entire schema of the table they were defined against, which was duplicated a lot. This caused a lot of unnecessary memory usage when the table schema was sufficiently large.
So, in numbers, for a 75 column table, without any transactions going through (just shape creation)
Baseline, no shapes: 71kB
- Current, 300 shapes
- Total (for shape-related processes): 64.1MB
- Total …
> feat: remove full table info from shape definitions to lower mem

- website/docs/api/config.md
I had set `required={false}` but the presence of the flag alone shows the env var as required - removing it so the docs are not cofusing.
> fix: Remove required flag on `ELECTRIC_QUERY_DATABASE_URL`

- website/docs/api/clients/typescript.md
- website/electric-api.yaml
Updated docs for the changes to `replica=full`. To merge after https://github.com/electric-sql/electric/pull/2381
> chore(docs): update docs for replica=full

- packages/sync-service/lib/electric/application.ex
and make `Electric.Application.configuration/1` public again
> Mark functions required by Phoenix.Sync

- .changeset/honest-crabs-sing.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/lsn_tracker.ex
- packages/sync-service/lib/electric/postgres/lsn.ex
- packages/sync-service/lib/electric/replication/log_offset.ex
- packages/sync-service/lib/electric/replication/persistent_replication_state.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/test/electric/lsn_tracker_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
Speed up replication processing by removing file writes from the main processing loop:
- persisting the tracked relations now only happens on a relation change, not every transaction
- `last_processed_lsn` is no longer persisted, but it is worked out from the last lsn seen in the shape logs. This also avoids a race condition where the lsn is written in the shape logs but not the PersistedReplicationState.
As part of this PR, this also fixes a bug we found where `last_processed_lsn` was always being set to `Lsn.from_integer(0)` on start-up rather than reading from disk.
Please note that as part of this PR, `last_processed_lsn` and `global_last_seen_lsn` no longer include LSNs from transactions that do not affect any shapes.
Here we can see a 20% increase in WAL processing speed:
> Removing file writes from the main WAL processing loop

- .changeset/two-spies-care.md
- packages/sync-service/lib/electric/shapes/filter.ex
- packages/sync-service/lib/electric/shapes/filter/indexes/inclusion_index.ex
- packages/sync-service/test/electric/shapes/filter_test.exs
Currently if a shape has a where clause that includes `array_field @> array_constant` and the array_field is null, the index will log an exception and fallback to non indexed where clause evaluation which is slow. This PR adds supprt for null arrays in the inclusion index.
>  fix(sync-service): Fix where clause inclusion index to support array is null

- .changeset/three-pans-bake.md
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/shapes/shape_test.exs
There was an error in the parsing of old shape definitions introduced when the table info was removed from the shape in https://github.com/electric-sql/electric/pull/2454
I've added a test for parsing the flags so that they are properly parsed as a map rather than a list, which was causing the publication manager to fail:
> fix: Fix backwards compatibility parsing of shape definitions' flags

- .changeset/brown-impalas-listen.md
- packages/experimental/src/bigint-utils.ts
- packages/experimental/src/multi-shape-stream.ts
- packages/experimental/test/bigint-utils.test.ts
Closes https://github.com/electric-sql/electric/issues/2493
We should avoid this pattern for functions that are to be used with unbounded argument sizes (if not avoid it all together given this issue)
> fix: Avoid function arg destructuring to not hit stack limits

- .changeset/short-crabs-glow.md
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/router_test.exs
> fix: skip updates that don't change any columns

- .changeset/hungry-beers-jog.md
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/typescript-client/test/integration.test.ts
Followup to https://github.com/electric-sql/electric/pull/2487
In the above PR I fixed an issue that would cause the publication manager to exit, which made Electric go into a restart loop.
There were two issues that compounded that problem:
1. I had previously converted the recovery of the shapes on the publication manager asynchronous, using `cast` instead of `call`, which means that Electric went ahead with initialisation and marked itself healthy despite not managing to actually recover - if it had waited for the recovery to finish and fail the container would never have been marked as healthy and never deployed.
2. If a recovery fails, for whatever reason, it might enter into an infinite recovery loop as it is likely some of the persisted state from which we are trying to recover is …
> fix: Synchronously refresh publication and clear cache if failed

- .changeset/forty-buttons-accept.md
- packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
- packages/sync-service/test/support/stub_inspector.ex
Closes #2448 
Generated columns cannot be included in a publication by PostgreSQL, so we disallow them in shapes. When doing `CREATE PUBLICATION p FOR TABLE t` without a column list, generated columns are omitted. When doing an explicit `FOR TABLE t (id)` (if `id` is generated), then it says `ERROR:  cannot use generated column "id" in publication column list`. 
We could, later, allow generated columns based on the subset of where clause functions we support by filling the stored values on our side too, but that's a way off.
> fix: disallow generated columns in shapes

- .changeset/hungry-pugs-kiss.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
With this PR, once the number of shapes exceeds `max_shapes` shapes are expired, least recently used first.
`max_shapes` is currently fixed and specified with the new `ELECTRIC_EXPERIMENTAL_MAX_SHAPES` environment variable. The env var has `EXPERIMENTAL` in it's name to convey that we will not be supporting this variable in the future since we would prefer that `max_shapes` was dynamically calculated. However for trigger.dev we can see setting max_shapes to 8000 should prevent WAL lag and shapes that have not been used for about two hours are expired which suits their needs.
A shapes `last_read` time is not currently persisted to disk. That has been left to a later PR. For trigger.dev this is fine since they do not currently recover shapes on restart. In the event that shape recovery was …
> feat(sync-service): Add LRU shape expiry

- .changeset/rich-glasses-run.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
Closes #2444
There will be a follow-up to refetch a schema even in absence of updates
> fix: refetch schema info when seeing a relation

- .changeset/pink-panthers-draw.md
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/filter.ex
Includes two changes:
[Include error time in filter span](https://github.com/electric-sql/electric/commit/dae5c7f59d0908be861f4e06c747b9f922135ad1)
[Time how log it takes for txn message to be received](https://github.com/electric-sql/electric/commit/32a467351b30715de2f0104255aaebdd529dfe3e)
> Improved replication processing telemetry

- .changeset/lazy-eyes-add.md
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- Catch the exits when altering tables to account for GenServer timeouts as well as DBConnection raises:
- Closes #2502 
- Closes #2503 
- Make sure to mark snapshot as started only after getting first row from PG to avoid race condition where the file wasn't created yet
- Closes #2505
> fix: better error handling for timing issues when accessing PG

- .changeset/chatty-pens-notice.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/fetch.test.ts
Closes https://github.com/electric-sql/electric/issues/2538
Maintain backwards compatibility after https://github.com/electric-sql/electric/pull/2486
The change was forwards compatible (old clients work with new servers) but not backwards compatible (new clients didn't work with old servers - old enough that they wouldn't return a body with the 204).
NOTE: The change was actually both forwards and backwards compatible as of the official 1.0.0 release, as we were already (wrongly) including a body with 204 responses at that point. I think that we should not reinsert this for the sake of backwards compatibility for versions prior to the official 1.0.0.
> fix: Maintain backwards compatibility with 204s

- .changeset/orange-insects-wait.md
- packages/sync-service/lib/debug/process.ex
- packages/sync-service/lib/electric/debug/process.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
- packages/sync-service/test/electric/debug/process_test.exs
the with clause meant that instead of returning a %{type, memory} map dead processes were returning just `:dead`.
Fixes https://github.com/electric-sql/electric/issues/2534
> Fix error with dead processes

- .github/workflows/changesets_release.yml
This PR extends the changesets workflow such that we trigger the Cloud workflow for updating the version of Electric that is used by the cloud.
> chore: Trigger Cloud workflow for updating Electric on release

- .changeset/shaggy-masks-cheer.md
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
This should fix #2536.
My brain is too fried by now to write a proper test for this. I'll finish it tomorrow or feel free to pick it up.
> Fix shape param encoding in the location header returned as part of a 409 response

- .changeset/breezy-trainers-brake.md
- integration-tests/tests/invalidated-replication-slot.lux
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
This PR handles the Postgres "database does not exist" error which can occur when a user deletes their database. This is a fatal error we can't recover from so we now also handle it like that. I modified the shutdown method to log a warning rather than an error since the shutdown is not unexpected since we are shutting it down on purpose as a response to the DB no longer existing. This will also avoid that this error pops up in Sentry for our cloud.
Fixes https://github.com/electric-sql/electric/issues/2552
> fix: Handle db does not exist error as a fatal error

- integration-tests/tests/startup-delayed-by-pending-transaction.lux
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/lsn_tracker.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/connection_setup.ex
- packages/sync-service/mix.exs
- packages/sync-service/test/electric/lsn_tracker_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
This unblocks the connection manager process even if the replication client gets stuck waiting for all pending transactions to commit or rollback.
Fixes #2391.
The PR also adjusts the handling of connection options, in particular the fallback logic for noSSL and IPv4.
> Make the initialization procedure of ReplicationClient async

- .changeset/giant-fishes-tease.md
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
There's no need to reply with a 200 and then require a second request to get the 409 status. we can just send the 409 immediately and save a round-trip. the two are functionally identical - a live request returns a 409, only the duration of that request changes.
Fixes #2585
> Return 409 immediately to live requests when shape invalidated

- .github/workflows/changesets_release.yml
I regenerated the cross repo PAT as it was expired and i updated the CROSSREPO_PAT accordingly.
This PR replaces the use of the CLOUD_REPO_TRIGGER_TOKEN by the CROSSREPO_PAT we already had in place.
> chore: Use cross repo PAT instead of cloud repo PAT

- .changeset/twenty-rings-lay.md
- packages/sync-service/lib/electric/connection/manager.ex
This fixes an error we're seeing sometimes in Sentry around monitoring. Not sure about the root cause of process being unresponsive, but it might be that it's a slow query against Postgres that's blocking the entire thing. This PR moves the wal query into a task so that the manager can continue to handle `DOWN` messages and such
> fix: improve error handling around a periodic wal size check

- .changeset/tasty-readers-boil.md
- packages/sync-service/config/config.exs
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/test/electric/shape_cache_test.exs
We had an issue, where when we cleaned up shapes (e.g. on `purge_all_shapes` which happened to be triggered for everyone because of `timeline null` issue), if the processes were never started (again, in particular for `purge_all_shapes`, then the shape handle failed to be cleaned up, and it got our system into an incosistent state where the ETS said shape exists, but no associated processes were ever started
> fix: shape cleanup should delete the shape handle too

- packages/elixir-client/test/electric/client/embedded_test.exs
- packages/elixir-client/test/electric/client_test.exs
- packages/sync-service/.env.test
- packages/sync-service/config/runtime.exs
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/health_check_plug_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/postgres/lock_connection_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/test_helper.exs
#2541 turned out to be partly misleading.
This change addresses the confusion and makes log level in the test env fully configurable with env variables.
> Configuring log level in the test environment

- .changeset/sour-poems-beg.md
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/shapes/consumer_test.exs
Issue was only with shapes that didn't observe any writes after being created. When creating a snapshot, we don't know ahead of reading how many total rows we would read from DB, so we created a shape with an in-memory value for last known offset of `0_inf` - after all real snapshot chunks (denoted as `0_1`, `0_2`, ..., `0_n`), but before real LSNs with `x_y` where x > 0. On a restart however we'd read actually created chunk lists and fill in "last known" offset to be say `0_2` instead. Which meant suddenly clients who previously read through the snapshot and were just hanging waiting for new changes got the 400 because requested `0_inf` was indeed larger than presumed maximum of `0_2`. The PR just makes it so that the state of the world after a restart is consistent with the one we …
> fix: Electric restart shouldn't cause requests with `0_inf` to fail

- examples/write-patterns/patterns/4-through-the-db/local-schema.sql
As pointed out by @itoxiq, the delete trigger was not actually wired up. This was a mistake in the example code.
> examples: wire up delete trigger in through the DB example.

- examples/proxy-auth/app/shape-proxy/route.ts
- examples/remix/app/routes/shape-proxy.ts
- examples/yjs/app/shape-proxy/[...table]/route.ts
- website/docs/guides/auth.md
- website/product/cloud.md
Tighten the code pattern & also add it to the cloud docs as well where it was missing.
> Improve proxy docs around removing content-length/content-encoding

- .changeset/popular-mice-change.md
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
> fix: ensure split PK update is always visible

- website/electric-api.yaml
Introduces the `secret` query param in favor of `api_secret` which is deprecated and will be removed in v2.
> docs: Mark api_secret as deprecated in OpenAPI spec

- .changeset/thirty-jeans-hope.md
- packages/sync-service/lib/electric/connection/manager.ex
Addresses #2612 and https://github.com/electric-sql/stratovolt/issues/421.
Here's an example of what it looks like and PG is stopped and later restarted:
> Surface more connection-related events as stack events

- .changeset/purple-snakes-poke.md
- integration-tests/tests/installation-id-persistence.lux
- packages/sync-service/lib/electric.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
`instance_id` is required in telemetry_opts but in application_telemetry supervision tree we load it from Electric (supervision tree?) configuration, which is not started with the top-level application in Cloud.
```elixir
defp telemetry_opts(opts) do
[
instance_id: Keyword.fetch!(opts, :instance_id),
...
]
end
```
This was causing issues when we enable the call_home_telemetry in Cloud since it emits some metrics for the instance even without any tenants. Hope this is right, but I'm happy to learn if there is a better way of doing it.
> fix: load instance_id from opts for configuring application_telemetry

- .changeset/metal-trains-yell.md
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
We observed the `unsafe_cleanup!` call on shape files failing with an `:eexist` reason on the `File.rm_rf!` calls, which didn't make much sense.
Looking at the Elixir source we suspect that the issue is `rm_dir` failing due to some race occurring:
https://github.com/elixir-lang/elixir/blob/e35ffc5a903bff3b595e323eb1ac12c4ecd515ad/lib/elixir/lib/file.ex#L1308-L1312
Here's a discussion with Gemini about this as well https://gemini.google.com/share/d36919a2b507
Potentially the directory is assumed to be empty after files have been deleted but something causes it to not actually be fully empty, especially on weirder filesystems like AWS' EFS which is networkd and distributed.
This PR suggests adding some arbitrary retries with small waits in an attempt to mitigate this issue - I'm open to …
> fix: Add retries on shape file cleanup operation to prevent `EEXIST` race

- .changeset/dull-seals-flow.md
- integration-tests/tests/invalid-wal-level.lux
- integration-tests/tests/replication-slot-self-conflict.lux
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/connection_setup.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/test/electric/connection/manager_test.exs
- packages/sync-service/test/electric/db_connection_error_test.exs
- packages/sync-service/test/electric/postgres/lock_connection_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
The highlight of this PR is the code refactoring inside Connection.Manager module to make the state machine that it implements more explicit and transitions between steps better documented.
Not too long ago we made the initialization of ReplicationClient asynchronous which had been necessitated by the possibility of its startup getting blocked on a pending DB transaction. This PR also makes LockConnection's initialization async for consistency. Both types of processes now return early from their respective `init()` callbacks and then cast messages to the connection manager when reaching a new milestone (connected, lock_acquired, ready_to_stream, streaming_started).
What prompted this refactoring was a new failure state we had discovered. If there's a pending transaction that blocks …
> Refactor and fix connection initialization/reconnection backoff

- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/dynamic_consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/shape_cleaner.ex
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/partitioned_tables_test.exs
- packages/sync-service/test/electric/shapes/shape_cleaner_test.exs
- packages/sync-service/test/support/component_setup.ex
Followup to https://github.com/electric-sql/electric/pull/2656
Need to fix a shape cache test still but opening for visibility
> fix: Only cleanup shapes via `ShapeCleaner`

- website/demos/encryption.md
- website/demos/nextjs.md
- website/demos/phoenix-liveview.md
- website/demos/react.md
- website/demos/remix.md
- website/demos/tanstack.md
- website/demos/todo-app.md
- website/docs/guides/auth.md
- website/docs/guides/writes.md
While reading through the documentation, I noticed a couple of broken GitHub links. This PR fixes those links to ensure they correctly point to the intended locations, improving the developer experience and helping others navigate the docs more easily.
> docs: fix broken github links

- website/electric-api.yaml
Fixes a minor typo in the OpenAPI spec.
> docs: fix typo in OpenAPI spec

- .changeset/mighty-otters-fry.md
- packages/sync-service/lib/electric/connection/manager.ex
I'm investigating some issues around the release of the advisory lock - sometimes I've noticed that we've terminated the Electric process but when trying to grab the relevant advisory lock elsewhere we fail as the lock is still in use.
I'm not sure how quickly Postgres should be responding to the session ending and releasing the lock, I assume very quickly, but I started thinking about what happens with connection pooling.
For example, pgBouncer [does not support session locks](https://www.pgbouncer.org/features.html) when in transaction pooling mode, and generally unless advisory locks are explicitly supported poolers would mess with the expected behaviour of the advisory lock.
For that reason I suggest using the unpooled connection for the advisory lock. I also thought that we might …
> fix: Use regular connection for advisory lock instead of pooled one

- .changeset/gentle-buttons-cover.md
- packages/sync-service/lib/electric/postgres/lock_connection.ex
The lock acquisition might take a while, and many PG providers might time out the statement execution - we're fine to just keep trying but we should only log unexpected errors.
We could argue that we don't even want to backoff and retry, and just immediately retry, but I'm worried that since the providers are timing statements out we might be better off not retrying immediately.
> fix: Only log unexpected lock acquisition errors

- .github/workflows/deploy_all_examples.yml
- .github/workflows/deploy_examples.yml
- .github/workflows/teardown_examples_pr_stack.yml
Currently, example apps are deployed sequentially. This takes a very long time (> 40 minutes). This is not very practical when we want to quickly test changes to one of these example apps. This PR modifies the workflow to **deploy** the **changed examples in parallel**.
> chore (examples): Deploy example apps in parallel

- examples/nextjs/sst.config.ts
The website links to https://nextjs.examples.electric-sql.com/ but the demo is actually at https://nextjs.electric-sql.com/
This PR modifies the SST code to host the example under the examples subdomain.
> chore (examples): Move nextjs to examples subdomain

- .changeset/gorgeous-kiwis-crash.md
- packages/sync-service/lib/electric/connection/manager.ex
Closes https://github.com/electric-sql/electric/issues/2691
Added a 5 second timeout - what we've observed is setup errors would come through within a few milliseconds, but I think allowing a few seconds is reasonable. A connection that falls over within 5 seconds of being established should be considered unsuccessful IMO.
I've avoided using timers and storing timer references, as I think we can get the job done by relying on the fact that if the replication client pid is the same between receiving the first message and the timeout passing, we can consider the connection successful.
Will test this ad hoc with @alco 's reproduction steps - we don't really have proper testing around the ConnMan so not sure what to do with this.
> fix: Add timeout before considering replication connection successful

- .github/workflows/deploy_examples.yml
This PR fixes a problem with the deployment action in CI which would try to deploy with an empty matrix when none of the deployable examples changed.
> chore (examples): Do not deploy if there are no changes to the examples

- .changeset/dirty-cherries-poke.md
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex
- packages/sync-service/lib/electric/shapes/monitor/cleanup_task_supervisor.ex
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/monitor_test.exs
- packages/sync-service/test/support/component_setup.ex
Ensures calls to `PublicationManager` are made with an associated shape handle to ensure idempotency and proper cleanups.
This prevents cases where the following happens:
1. Shape with handle X and shape definition A is added
2. Shape with handle Y != X and shape definition A is added
3. Shape X is removed/deleted - cleanup ends up trying to clean the associated publication more than once
4. Shape Y gets accidentally removed from the publication because of Shape X's cleanup
To avoid such cases, we also keep track of the shape handles we track - this is not a large memory overhead and ensures we no longer have to worry about this. We can improve the approach but tracking shape handles in the publication is something we definitely want to do.
> feat: Idempotent `PublicationManager` calls

- .changeset/loud-walls-do.md
- .github/workflows/elixir_tests.yml
- packages/sync-service/config/config.exs
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/telemetry.ex
- packages/sync-service/mix.exs
- packages/sync-service/test/electric/telemetry/application_telemetry_test.exs
- packages/sync-service/test/test_helper.exs
This PR fixes the typo in the `targets` option for telemetry deps. All it does is make sure those deps aren't compiled when Mix target is set to anything other than `application`.
We also disable compilation of telemetry modules in the test env to make sure the stub code is exercised. A new CI step has been added specifically for the tests that exercise ApplicationTelemetry.
> Fix the gating of telemetry deps behind a Mix target

- .changeset/happy-cats-do.md
- packages/sync-service/lib/electric/plug/utility_router.ex
- packages/sync-service/lib/electric/telemetry/application_telemetry.ex
Fixes #2674.
Trying to report out custom per-process-type memory metrics as part of telemetry poller's builtin `memory` probe was a mistake, as explained in the linked issue. This PR defines a separate event for our custom memory probes.
Now, instead of exporting `vm.memory.processes_by_type` we have the  `process.memory.total` measurement which is tagged with the process type/name. Such measurements are still reported only for the top N processes.
From what I've been able to find, the `vm.memory.processes_by_type` metric has only been referenced in Honeycomb by @robacourt's query that showcased the mem usage grouped by process type/name.
> Fix issues in Prometheus metric collection

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Not sure this is how it works but we can at least try.
> Add default issue types in issue templates

- packages/typescript-client/src/client.ts
- packages/typescript-client/test/client.test-d.ts
- packages/typescript-client/test/client.test.ts
If a generic type is passed, we should constrain the columns argument to the keys in the type.
I don't think this actually works — if someone better at typescript could look at it and figure out why, that'd be appreciated :-D
> Type columns argument to typescript client

- .github/workflows/deploy_examples.yml
We're pinning this action because some versions were compromised and we want to be sure we don't accidentally use one of those versions. This hash corresponds to the latest release: v46.0.5
> chore (deployments): Pin changed-files action

- .changeset/olive-garlics-clap.md
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/typescript-client/test/cache.test.ts
- website/electric-api.yaml
Closes https://github.com/electric-sql/electric/issues/2504
Technically we were documenting this in our OpenAPI spec, so even though we don't use it in our clients and we don't advertise it much in our docs this _is_ a bit of a breaking change?
I'll let @KyleAMathews decide if we want to move forward with this, I've prepared this PR to get rid of it just to accelerate a decision on this.
> fix: Remove location header from 409 responses

- .changeset/hot-carpets-destroy.md
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/support/test_utils.ex
Fixes https://github.com/electric-sql/electric/issues/2559
The steps to reproduce this issue, along with a host of other ones, was to essentially delete the database while a request was in-flight and waiting for updates (either new changes or a shape rotation).
If the database is deleted or the connection fails for any other reason, the stack is retrying and trying to set itself up, which means that the `LsnTracker` ETS table is not live, and thus the `global_last_seen_lsn` cannot be read.
Initially I tried to address that problem in isolation, but more kept coming, and I thought that the cleanest thing would be to ensure that the stack is actually up and running after a long poll timeout and return the same class of stack not ready errors if it is not.
This means potentially adding, at …
> fix: Ensure stack is active after long poll timeout

- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache/storage_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/mocks.ex
keeping the same Mock.* naming
This prevents expectations defined in simultaneously executing tests from clashing. I think this is the cause of various flakes in the CI - we define expectations on `Support.Mock.Behaviour` and occasionally a parallel test hits that expectation but fails because it's coming from an unregistered pid.
This pr gives every test module its own set of `__MODULE__.Mock.Behaviour` mocks to define expectations on but keeps the same usage in the tests.
> sync-service: Use separate mock modules per-test

- examples/phoenix-liveview/package.json
So it's not included in the default npm:publish task
> Make phoenix-liveview example private

- .changeset/four-tomatoes-glow.md
- packages/sync-service/lib/electric/shapes/api/response.ex
Closes https://github.com/electric-sql/electric/issues/2770
I included reason `:closed` on top of `"closed"` to the existing handling clause for interrupted streams. Not sure if both actually occur or if the existing clause was a mistake @magnetised .
> fix: Catch reason `:closed` for a lost connection

- .changeset/fluffy-pants-wink.md
- packages/sync-service/lib/electric/connection/manager.ex
Ensures `:ready` stack event is fired even after a replication client restart
Addresses https://github.com/electric-sql/stratovolt/issues/660
> fix: Ensure `:ready` message fires after a replication client restart

- packages/elixir-client/test/support/money.ex
Fix the compilation issue introduced in https://github.com/electric-sql/electric/pull/2754.
> Fix compilation warning when running with MIX_ENV=test

- .changeset/eight-pigs-swim.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/connection_setup.ex
- packages/sync-service/test/electric/postgres/replication_client_test.exs
We have recently observed some source in Electric Cloud struggle due to lock and replication slot contention issues which in theory shouldn't have happened at all. The cause of the issues was an imperfect validation logic applied to the creation of new sources. As a consequence, some sources get created with a pooled connection URL.
More concretely, our validation can successfully weed out pooled connection strings from Supabase, but Neon's pool allows establishing replication connections by proxying them directly to the DB. As a result, Electric ends up acquiring an advisory lock on a pooled connection where the pooler runs in transaction mode, leading to a bunch of undesirable effects that prevent Electric's normal operation.
---
This PR addresses the cause of the issues by making the …
> Fix lock semantics for the exclusive connection lock when running against a pooler

- .changeset/calm-insects-fly.md
- packages/sync-service/lib/electric/replication/eval/expr.ex
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/shapes/shape_test.exs
Because the original sql where clause is normalised before serialisation, shapes generated with a consistent where clause would not match against existing, identical, shapes due to differences in the parser output.
So a shape generated with the where clause `(USER_ID = 'something')` would be deserialised with the where clause `user_id = 'something'` which wouldn't match against shapes coming from clients with the original form because the `location` fields in the deserialised version would be off-by-one due to the missing parentheses.
Fixes https://github.com/electric-sql/phoenix_sync/issues/56
> fix(sync-service): Make Shape.comparable robust after serialisation

- .changeset/lazy-rivers-camp.md
- packages/elixir-client/lib/electric/client.ex
- packages/elixir-client/lib/electric/client/authenticator/mock_authenticator.ex
- packages/elixir-client/lib/electric/client/ecto_adapter.ex
- packages/elixir-client/lib/electric/client/embedded.ex
- packages/elixir-client/lib/electric/client/fetch/request.ex
- packages/elixir-client/lib/electric/client/shape_definition.ex
- packages/elixir-client/test/electric/client/ecto_adapter_test.exs
- packages/elixir-client/test/electric/client/fetch/request_test.exs
- packages/elixir-client/test/electric/client/shape_definition_test.exs
- packages/elixir-client/test/electric/client_test.exs
- packages/elixir-client/test/support/money.ex
Allows for generating a ShapeDefinition from an Ecto.Changeset
Also bundles a few quality-of-life changes:
- ShapeDefinition.params/1 returns a `%{binary => binary}` map in query string mode, rather than a mix of atom and binary keys
- Widen accepted types for where parameters from `:string` to [:string, :integer, :float, :boolean]` to make life simpler for user. these types are trivial to convert to strings so why not do that for people
- Give ShapeDefinitions a `replica` setting. This is how it should have been to begin with -- the replica mode is a property of the shape, not of the stream
- Expose the ShapeDefinition validation schema so we can split options and validate partial shape parameters (Phoenix.Sync.PredefinedShape accepts a big bag of options that we need to assign …
> elixir-client: Build shape definition from changeset

- packages/sync-service/lib/electric/connection/manager.ex
It was added there in https://github.com/electric-sql/electric/pull/2791 because we had it available from the IDENTIFY_SYSTEM statement. But since it's not used for anything, not storing it anywhere is a better strategy for now.
> Remove pg_wal_flush_lsn from Connection.Manager's state

- .changeset/two-singers-care.md
- packages/elixir-client/config/config.exs
- packages/elixir-client/lib/electric/client/ecto_adapter.ex
- packages/elixir-client/lib/electric/client/ecto_adapter/array_decoder.ex
- packages/elixir-client/test/electric/client/ecto_adapter/array_decoder_test.exs
- packages/elixir-client/test/electric/client/ecto_adapter_test.exs
- packages/sync-service/lib/electric/shapes/api.ex
including:
- `{:array, type}`
- `:map`
- `:bitstring`
- `:binary`
And validate decoding of other types and embedded schemas
> elixir-client: Add support for more Ecto field types

- packages/sync-service/lib/electric/postgres/lock_connection.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/test/electric/concurrent_stream_test.exs
- packages/sync-service/test/electric/connection/manager_test.exs
- packages/sync-service/test/electric/postgres/lock_connection_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
- packages/sync-service/test/electric/process_registry_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/file_storage_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/shapes/monitor_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_setup.ex
Ensures that all processes started are started under the ExUnit test supervisor, in the hope that this gives us better guarantees about cleanups occurring at the right time and we reduce flakes that seem to potentially be related to timing issues.
> chore: Ensure test processes are supervised by the test supervisor

- .changeset/gentle-wolves-unite.md
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/lib/electric/replication/postgres_interop/casting.ex
- packages/sync-service/test/electric/replication/eval/runner_test.exs
Was trying to get a where clause in a shape to work, where either one field would match a value OR another field would, and in practice I would set one field to null and move the value over to the other (meaning that it should trigger an update) and I was seeing a delete coming through.
Digging through the code I found the issue to be that we were treating `AND`, `OR`, and `NOT` all as `strict?` operators, meaning that if any of their arguments are `NULL` we collapse the result to `NULL` also. However this is not the correct behaviour on postgres for the `OR` operator, as shown below:
```sql
select null and true; # -> null
select not null; # -> null
select null or true; # -> t
select null or false; # -> null
```
I've changed the `OR` operator to not be strict along with a simple test for …
> fix: `OR` operator in where clauses should not be strict

- packages/sync-service/test/electric/publisher_test.exs
These tests can occasionally fail with:
```
Assertion failed, no matching message after 5000ms
The process mailbox is empty.
code: assert_receive :publish_finished
```
The race condition occurs if the TestSubscriber receives the `:finish_processing_message` message before it receives the publisher call, in which case it swallows the message since `handle_info` is not implemented on TestSubscriber. A GenServer would log that a message had been received and not handled, but as `use GenServer` was omitted from the TestSubscriber the message was swallowed silently.
This PR:
- Adds `use GenServer` to the TestSubscriber as this is best practice (the race condition would have been obvious had it been included in the first place)
- Waits for `:message_received` from each of the subscribers before …
> chore(sync-service): Fix flakey Publisher tests

- package.json
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/typescript-client/package.json
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/constants.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/src/helpers.ts
- packages/typescript-client/src/types.ts
- packages/typescript-client/test/__snapshots__/client.test.ts.snap
- packages/typescript-client/test/client.test.ts
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/tsconfig.build.json
- packages/typescript-client/tsconfig.json
- patches/@microsoft__fetch-event-source.patch
- pnpm-lock.yaml
> WIP feat(client): experimental support for streaming SSE in live mode

- .changeset/tender-crabs-retire.md
- packages/experimental/test/support/test-context.ts
- packages/experimental/test/support/test-helpers.ts
- packages/sync-service/lib/electric/shapes/api.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/typescript-client/test/integration.test.ts
- packages/typescript-client/test/support/test-context.ts
- packages/typescript-client/test/support/test-helpers.ts
This PR started as an attempt to fix a flaky TS test, that basically just tested that it received updates to a shape.
After some investigation, I found that the reason it was flaking was that sometimes the updates arrived at the shape consumer the moment between the request:
1. Loaded the shape (its handle and latest offset)
2. Started listening for changes to the shape (which we only do if the request's offset is larger than or equal to the read latest offset)
In this case, the `:new changes` message would not have been received by the request process as the changes were processed before it started listening, and the latest offset is loaded is now out of date.
This leads to the request hanging for 20 seconds waiting for new updates (despite the update already having been processed). The …
> fix: Account for race between loading shape and listening for changes

- .changeset/few-eggs-relax.md
- packages/sync-service/lib/electric/replication/eval/env/known_functions.ex
- packages/sync-service/lib/electric/replication/eval/parser.ex
- packages/sync-service/lib/electric/replication/postgres_interop/casting.ex
- packages/sync-service/lib/pg_interop/array.ex
- packages/sync-service/test/electric/replication/eval/runner_test.exs
- packages/sync-service/test/support/pg_expression_generator.ex
Introduces some `StreamData` property tests for our PG expression parser and executor.
Not the prettiest but I did already find several issues, some of which I would need confirmation that they were not intentional:
1. `AND` should handle `false and null` case as `false`
2. Array concatenation with `null` should return the same array
3. `array_prepend` and `array_append` work with `null`s, and they actually add the null to the array
4. Array prepends and appends using `||` work with `null` but they keep the array the same, and they do not work with strings
5. Array contains and is contained have specific behaviours with `null` - if the array that should be contained has a `null` then it will never pass the check - whether the array containing the other has a `null` or not.
6. The `^` …
> fix: Ensure PG expression execution in Electric matches PG

- .changeset/brown-bugs-shout.md
- packages/sync-service/lib/electric/connection/manager.ex
Followup to https://github.com/electric-sql/electric/pull/2864
As @balegas suggested and @alco pointed out, these errors are not actionable and self-recovering, so we should not fire any stack events for them.
> fix: Remove `:pool_connection_error` stack event altogether

- .github/workflows/changesets_release.yml
With our current approach we end up skipping Docker image updates because the commits get overwritten - I propose always sending the latest versions of both the commit sha and the docker version and we just ensure we don't do unnecessary updates at the target.
> fix: Always include latest versions

- .changeset/silent-ears-agree.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/fetch.ts
- packages/typescript-client/src/helpers.ts
- packages/typescript-client/src/parser.ts
- packages/typescript-client/src/types.ts
- packages/typescript-client/test/client.test.ts
This PR addresses the issue raised in https://github.com/electric-sql/electric/pull/2546#issuecomment-3007137018. The crux of the issue is that messages might be processed several times if the SSE connection breaks after processing a message but before receiving the up-to-date message. This is because we only advance the offset when processing the up-to-date message, hence, we would fetch again at the old offset and receive some messages that we already processed.
The fix is easy: we batch SSE messages until we receive up-to-date and only process the messages at that point. The hard part was to write a unit test that reproduces this scenario. After a bit of trial and error i managed to do that by creating a custom fetch wrapper that proxies the SSE response but filters out the first …
> fix: buffer SSE messages until up-to-date message

- .changeset/healthy-needles-fetch.md
- packages/sync-service/lib/electric/connection/manager.ex
We are occasionally getting crashes because there is no function clause matching for `:pool_conn_down` messages with reason `:shutdown`, as we only cover `{:shutdown, reason}` (see [this Sentry issue](https://electricsql-04.sentry.io/issues/48398126/?environment=production&project=4508410462404688&query=is%3Aunresolved&referrer=issue-stream&stream_index=20))
I've generalized the handler for `:pool_conn_down` to handle all exit reasons, since they are mostly no-ops anyway.
> fix: Handle more pool connection exit reasons

- .changeset/unlucky-taxis-breathe.md
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/test/electric/db_connection_error_test.exs
Went through sentry and covered some more common errors that we should be able to recognize:
- Connection timeouts (tcp connect) [sentry1](https://electricsql-04.sentry.io/issues/46552901/?environment=production&project=4508410462404688&query=is%3Aunresolved%20Electric.DBConnection%20unknown%20error&referrer=issue-stream&stream_index=6) [sentry2](https://electricsql-04.sentry.io/issues/51034946/?alert_rule_id=105022&alert_timestamp=1751930919832&alert_type=email&notification_uuid=244b98d5-9159-490a-90dc-7020448febfa&project=4508410462404688&referrer=digest_email) - we already recognize some, but when they happen during `Postgrex.Protocol.connect` they come in a different format
- Pool timeouts [sentry](https://electricsql-04.sentry.io/issues/47793877/?environment=production&project=4508410 …
> fix: Recognize and parse more connection errors

- .changeset/chilled-oranges-type.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- website/docs/api/config.md
AntonOfTheWoods experiences the following error message:
```
Error while streaming response: :timeout
```
This is most probably due to slow response processing on the client side causing TCP backpressure. AntonOfTheWoods has asked for configuration to increase the timeout, so this PR introduces `ELECTRIC_TCP_SEND_TIMEOUT` to allow configuration of the TCP/SSL send timeout.
The default is `30s` as it is right now, but for example the timeout can be set to 60 seconds with:
```
ELECTRIC_TCP_SEND_TIMEOUT=60s
```
> feat(sync-service): Allow configuration of TCP send timeout

- .changeset/silly-ghosts-attack.md
- packages/sync-service/lib/electric/connection/manager.ex
Fixes [this sentry issue](https://electricsql-04.sentry.io/issues/48398126/events/e0ac0dc9f6fd4cce95644e05ee16f5cb/)
> fix: Ignore noproc pool connections dying

- website/blog/posts/2024-11-21-local-first-with-your-existing-api.md
I was reading this article and noticed this typo in this blog [post](https://electric-sql.com/blog/2024/11/21/local-first-with-your-existing-api#authorizing-writes)
**Image**
> blog: Fix typo

- .changeset/tough-cows-kick.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_setup.ex
No reason we should be seeing [errors like these](https://electricsql-04.sentry.io/issues/14716077/?environment=production&project=4508410462404688&query=is%3Aunresolved&referrer=issue-stream&stream_index=1) when we already have a `pg_version` available from the replication client.
Removing code that's unnecessary, simplifying the publication manager.
> fix: Require pg version for publication manager

- website/public/docker-compose.yaml
This changes uses fully qualified names for container images in the quickstart compose file.
Additionally, a healthcheck is added to the postgres service to allow electric service to wait till the database is ready before starting.
> chore: update quickstart compose file

- .changeset/little-impalas-lay.md
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/exceedingly-large-transaction.lux
- integration-tests/tests/invalidated-replication-slot.lux
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric.ex
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/lib/electric/postgres/logical_replication/decoder.ex
- packages/sync-service/lib/electric/postgres/logical_replication/messages.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/collector.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/postgres/decoder_test.exs
- packages/sync-service/test/electric/postgres/replication_client/collector_test.exs
- packages/sync-service/test/electric/postgres/replication_client_test.exs
Fixes https://github.com/electric-sql/electric/issues/2900
Fixes https://github.com/electric-sql/electric/issues/2101
We will now be handling the following two cases:
1. Transaction comes in with a replica identity not set to `FULL` - something got misconfigured, and the stream is no longer valid since changes don't contain all information we need
2. Transaction gets collected and its data content surpasses `max_txn_size`, which defaults to 250 MB (I can make it env var configurable)
When these things happen, we exit the replication client with an `:irrecoverable_slot` error, which gets parsed as a `DbConnectionError`.
I've added a `drop_replication_slot?` field on these errors to make it clearer whether an error should trigger slot drop, and subsequently a full stack reset. Combined with …
> fix: Restart stack on irrecoverable replication issues

- .changeset/tricky-ravens-roll.md
- .changeset/young-numbers-count.md
- integration-tests/tests/replication-lifetime.lux
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/interval_timer.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/replication/shape_log_collector.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/filter/where_condition.ex
- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
- packages/sync-service/lib/electric/telemetry/optional_spans.ex
- packages/sync-service/lib/electric/telemetry/sampler.ex
- packages/sync-service/test/electric/telemetry/interval_timer_test.exs
- packages/sync-service/test/electric/telemetry/open_telemetry_test.exs
This PR speeds up replication processing by 65%. The above benchmarks were run via docker which slows them down a bit, without docker processing time came down to 23µs (43.5K TPS) which is about [as fast as Postgres can go](https://www.enterprisedb.com/blog/performance-comparison-major-PostgreSQL-versions) (on a 72 CPU  144 GB RAM machine)
The performance improvements come from:
- Bespoke upfront span sampling. Standard OpenTelemetry sampling acts once the spans have been created. This bespoke mechanism samples at source to reduce the overhead of `with_span` from 13µs to practically nothing.
- Transaction logging is now at debug level
- Transaction metrics are sampled at source
- The `pg_txn.replication_client.process_x_log_data` span which measured decoding duration and other durations …
> feat(sync-service) Sample telemetry at source for faster replication stream processing

- .changeset/rare-taxis-end.md
- packages/elixir-client/lib/electric/client/embedded.ex
e.g. a 409 response returned by `Api.validate/2` needs to be mapped to a client response with the same status
> fix(electric-client): Properly translate error responses  returned by the validation step

- .changeset/big-tigers-perform.md
- packages/sync-service/lib/electric/shapes/monitor/cleanup_task_supervisor.ex
> fix(sync-service): Log warning rather than error if the shape cleanup tasks time out

- .changeset/wild-cameras-move.md
- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
- packages/sync-service/test/electric/telemetry/open_telemetry_test.exs
#2916 introduced upfront sampling, however this also sampled the span metrics. This PR keeps span metrics even if the OTEL span has not been included because of sampling.
Keeping the metrics does slow down replication processing, replication throughput benchmarks show a 10% slow down from 27µs/txn to 30µs/txn because of this PR, however we may consider this acceptable for now given how useful the metrics are.
> feat(sync-service): Include span metrics even if the OTEL span has been not included because of sampling

- .changeset/smooth-ducks-eat.md
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shape_cache/shape_status_agent.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/connection/manager_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/test_helper.exs
This work precedes the work I'm doing on https://github.com/electric-sql/electric/issues/2984
The `ShapeStatus` ETS table was being initialised by `ShapeCache`, but consumers also use it, and the consumer supervisor lives before the shape cache, causing issues in tests during shutdowns etc.
This changes _no_ behaviour in Electric (or at least it shouldn't!). I've refactored the tests and everything relevant to use shape cache in its new form.
I still don't love how it looks and I think it can be simplified further but this addresses the initial concern of moving it up front, and simplifies it as a mod arg passed at the stack supervisor level and then passed as is to appropriate modules, with a dedicated `ShapeStatusAgent` initializing and owning the table.
> chore: Refactor `ShapeStatus` table to begin separately before `ShapeCache` and consumers

- .changeset/purple-ligers-play.md
- packages/elixir-client/lib/electric/client/stream.ex
- packages/sync-service/lib/electric/shapes/api/params.ex
- packages/sync-service/lib/electric/shapes/api/response.ex
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/typescript-client/src/client.ts
- website/electric-api.yaml
Fixes https://github.com/electric-sql/electric/issues/3020
Before adapting the cursor for the purpose of 409s, I decided to use the handle itself which we were already using.
Here is my reasoninig:
1. Our main issue is that we are caching 409s (with or without a next handle) for 60 seconds - we are caching them as they are part of our regular request flow and it would create unnecessary load to break request coalescing and go to origin for them
1a. One immediate fix is to change the caching for 409s _without_ a handle to 1 second, the minimum to enable request coalescing. This means that on the next request cycle they would most likely run into a 409 _with_ a shape handle anyway.
1b. We could disable caching on 409s without a handle altogether - I _think_ that would would happen is that …
> fix: Consistent cache busting on 409s

- .changeset/late-berries-do.md
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/test/electric/postgres/configuration_test.exs
- packages/sync-service/test/electric/replication/publication_manager_db_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/db_setup.ex
This removes the code that was responsible for adding and maintaining the row filter on the publication (aka the WHERE clause).
We're still waiting on the final benchmark results from https://github.com/electric-sql/electric/pull/2895#issuecomment-3139023498 to have a better understanding of transaction processing times with row filtering enabled and disabled.
> Stop utilizing publication row filtering

- .changeset/silver-frogs-report.md
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/test/electric/db_connection_error_test.exs
Parsing [one more error](https://electricsql-04.sentry.io/issues/59667277/?environment=production&project=4508410462404688&query=is%3Aunresolved&referrer=issue-stream) that should be marked as retryable.
> fix: Parse query cancellation errors as retryable

- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
> Mention the 'columns' query param in the error message for generated columns

- .changeset/happy-parents-decide.md
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/snapshot_error.ex
- packages/sync-service/test/electric/db_connection_error_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/snapshot_error_test.exs
Closes https://github.com/electric-sql/stratovolt/issues/761
The errors we observed were because the publication created by Electric was being manually deleted by the developer. We should be safe to parse it into an error that restarts, ensuring consistency.
I've converted it to `retry_may_fix?: true` as 1) that was the current behaviour and 2) since this error basically restarts the replication client and the process of creating the slot/publication, this might be more appropriate?
@alco what do you think? should we force a harder restart on this error or rely on `retry_may_fix?`?
We are now capturing the missing publication error in `PublicationManager` as well and immediately terminating it, which causes a subsequent termination of `ShapeLogCollector` and thus a restart of the …
> fix: Handle missing publication errors

- website/docs/api/config.md
This option is effectively about enabling shape removal and it's not supposed to be publicly documented, and its documentation isn't helpful anyway.
> Unpublish the reference doc for internal configuration option

- .changeset/sour-suns-tell.md
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/test/electric/db_connection_error_test.exs
Fixes [Sentry issue](https://electricsql-04.sentry.io/issues/58939671/) - this is just another instance of insufficient resources, definitely retryable (until resources are freed).
> fix: Parse "remaining connection slots reserved" DB error as insufficient resources

- .changeset/twenty-foxes-kiss.md
- packages/sync-service/dev/gen_shapes.sh
- packages/sync-service/lib/electric/connection/supervisor.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shape_cache/crashing_file_storage.ex
- packages/sync-service/lib/electric/shape_cache/file_storage.ex
- packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
- packages/sync-service/lib/electric/shape_cache/pure_file_storage.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/shape_cache/shape_status_owner.ex
- packages/sync-service/lib/electric/shape_cache/storage.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
- packages/sync-service/test/support/test_storage.ex
Closes https://github.com/electric-sql/electric/issues/2984
We had observed that loading stored shapes took a long time, especially with larger number of shapes.
Doing some research most of the time was spent waiting on the various reads being done per-shape in order to load it up. @icehaunter is working on reducing those, but either way this would always scale with the number of shapes (at least 2-3 calls per shape). On slow FS like networked storage the time spent waiting on FS calls racks up pretty quickly.
After testing per-shape caching of metadata (reducing basically things to a single read per shape load), I concluded that to see a significant enough speedup we would need a global index that would avoid scaling FS operations with shapes recovered as much as possible.
Ultimately, …
> feat: Faster recovery times with single point controlled shutdown recovery

- .changeset/curly-wolves-wait.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/test/electric/connection/manager_test.exs
Followup to https://github.com/electric-sql/electric/pull/3065
By removing the shape log collector monitoring code, we also [removed](https://github.com/electric-sql/electric/pull/3065/files#diff-58fff6f19695125bcf9644f088b82fa5874ead4a15cb8c0ed5d5fec73ef2999eL709-L711) the dropping of the replication slot if a drop was requested.
This adds it back in as part of the conn man's termination handler along with a test.
> fix: Ensure slot is dropped upon termination if requested

- packages/sync-service/lib/electric/connection/manager.ex
Followup to https://github.com/electric-sql/electric/pull/3079 ...
I've noticed more errors on cloud - before we were ensuring the slot was dropped after the replication client was stopped, othrwise we run into `:object_in_use` errors - so in the termination procedure we should be doing the same:
1. terminate replication client
2. if pool is available, drop the slot
3. terminate the pool
4. terminate the lock connection
I cannot seem to reproduce this in the connection manager tests...
> fix: Clean up slot after the replication client

- .changeset/moody-pandas-decide.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer/materializer.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/plug/delete_shape_plug_test.exs
- packages/sync-service/test/electric/plug/router_test.exs
- packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
- packages/sync-service/test/electric/shape_cache/pure_file_storage_test.exs
- packages/sync-service/test/electric/shape_cache/storage_implementations_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/electric/shapes/consumer/materializer_test.exs
- packages/sync-service/test/electric/shapes/shape_test.exs
Closes #3037
Keeps around 2 structures - a reference counter for the values, and the key => value mapping, because on our replica modes we might not see old values that need to be counted down, especially on deletes.
Allows following one-to-many relations:
```sql
CREATE TABLE comments (..., task_id INT NOT NULL, ...);
CREATE TABLE tasks (id INT PRIMARY KEY, ...);
```
You can define a shape with `where: "id IN (SELECT task_id FROM comments WHERE ...)"` - or other applications of course.
> feat: support non-PK selects in subqueries

- .changeset/ninety-buses-pretend.md
- packages/elixir-client/lib/electric/client/ecto_adapter/postgres.ex
- packages/elixir-client/test/electric/client/ecto_adapter/postgres_test.exs
- packages/elixir-client/test/support/ulid.ex
Dumping a parameterized column with a :uuid type results in a binary
representation of the underlying bytes of the uuid. This doesn't work
with electric, which expects UUIDs to be string encoded.
Fixes #3083
> fix(elixir-client): Correctly encode uuid-backed columns in where clauses

- .changeset/rich-cats-shop.md
- packages/elixir-client/lib/electric/client/ecto_adapter.ex
- packages/elixir-client/test/electric/client/ecto_adapter/postgres_test.exs
- packages/elixir-client/test/electric/client/ecto_adapter_test.exs
- packages/elixir-client/test/support/ulid.ex
By converting them from the string encoding to raw bytes before passing to the type's load function we mimic the behaviour of loading direct from the db via postgrex.
> fix(elixir-client): Improve handling of uuid-based ecto types

- .changeset/proud-pears-jog.md
- packages/sync-service/lib/electric/replication/shape_log_collector/flush_tracker.ex
- packages/sync-service/test/electric/connection/manager/connection_backoff_test.exs
- packages/sync-service/test/electric/lsn_tracker_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector/flush_tracker_test.exs
- packages/sync-service/test/electric/replication/shape_log_collector_test.exs
- packages/sync-service/test/electric/shape_cache/pure_file_storage_test.exs
- packages/sync-service/test/electric/shapes/consumer/materializer_test.exs
Fixes https://github.com/electric-sql/electric/issues/3102
The main issue was that whenever we starter tracking flushes for a shape that we were not already tracking, we assumed its `last_flushed_offset` was the `last_global_flushed_offset`. This sounds like a reasonable assumption, and it is a valid lower bound for the new shape's last flushed offset, but it leads to the following scenario covered by the new test:
0. Initial state is `last_global_flushed_offset` is at transaction 9.
1. Transaction 10 for Shape A is ingested
2. Transaction 11 for Shape B is ingested
3. Flush ack for transaction 10 by Shape A is received
3a. `last_global_flushed_offset` is not updated as Shape B's most recent flush  was set to txn 9
4. Transaction 12 for Shape A is ingested
4a. We set Shape A's most recent …
> fix: Flush tracker acknowledgements under heavy load

- .changeset/early-rules-smile.md
- .changeset/giant-students-juggle.md
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/plug/serve_shape_plug.ex
- packages/sync-service/lib/electric/postgres/replication_client.ex
- packages/sync-service/lib/electric/postgres/replication_client/collector.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/monitor/ref_counter.ex
- packages/sync-service/lib/electric/telemetry/open_telemetry.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
- packages/sync-service/test/electric/postgres/replication_client/collector_test.exs
Closes https://github.com/electric-sql/electric/issues/3047
- Fixes `electric.postgres.replication.transaction_received.bytes` to use actual byte size of transaction
- I made the collector return an extra element in the tuple that is transaction meta to avoid adding more properties on the transaction itself unless they are actually needed in the shapes - no reason to copy over more things to all consumers
- Implemented thin wrapper over `:telemetry.execute` in OpenTelemetry module which we use for spans so that any stack related telemetry uses that and respects `telemetry_span_attrs`
- This ensures all stack metrics actually end up having a `source_id` on them in Cloud
> fix: Ensure all stack telemetry respects `telemetry_span_attrs`

- .changeset/chilled-dancers-sing.md
- packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
- packages/sync-service/test/electric/postgres/inspector/ets_inspector_test.exs
Overlaps a bit with @robacourt 's work, potentially relevant issue https://github.com/electric-sql/electric/issues/3053
Minimal work to avoid having the ETS inspector crash whenever we cannot grab a connection from the pool.
The pool dying is something to be expected throughout the lifetime of the app, but if the pool is dead then `Postgrex.transaction` violently exits.
In this PR I am not addressing the processes that use the inspector that can still crash as a consequence of the failure to load stuff. The goal of this PR is to prevent the ETS inspector itself from crashing and taking the cache down with it, leading to more DB pool contention upon restarting.
> fix: Avoid crashing ETS inspector on DB conn issue to preserve cache

- .changeset/spotty-oranges-pretend.md
- packages/typescript-client/src/types.ts
Fixes the issue with the transformer which is blocking CI due to failing typecheck.
The problem was that the `GetExtensions` type was inferring types that aren't extensions:
```ts
GetExtensions<{
id: number
name: string
org_id: number
}>
```
The snippet above was being resolved to `string | number` instead of `never`. That was wrong because `string` and `number` are built-in types so they don't count as extensions. Since this object type has no extensions it should return `never`.
Fixed that by changing the `GetExtensions` type to explicitly check whether the type extends the base `Row` type. If that's the case, then there are no extensions and we just return `never`. Otherwise, we infer the extensions.
> Fix GetExtensions to infer minimal Extensions

- .changeset/curly-rice-train.md
- .changeset/little-schools-destroy.md
- integration-tests/tests/_macros.luxinc
- integration-tests/tests/ipv6-to-ipv4-fallback.lux
- packages/sync-service/lib/electric/connection/manager.ex
- packages/sync-service/lib/electric/connection/manager/connection_resolver.ex
- packages/sync-service/lib/electric/connection/manager/pool.ex
- packages/sync-service/lib/electric/connection/manager/supervisor.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/lib/electric/status_monitor.ex
- packages/sync-service/lib/electric/telemetry/stack_telemetry.ex
- packages/sync-service/test/electric/connection/manager/connection_resolver_test.exs
- packages/sync-service/test/electric/connection/manager/pool_test.exs
- packages/sync-service/test/electric/connection/manager_test.exs
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/electric/status_monitor_test.exs
- packages/sync-service/test/support/test_utils.ex
Separating long-running snapshot connections from the various admin/metadata queries
Also move connection opts discovery into external process
> fix(sync-service): Split pg connections across two pools

- .github/workflows/elixir_tests.yml
- integration-tests/tests/_macros.luxinc
- packages/sync-service/dev/docker-compose.yml
Bitnami deprecated their public image - we should switch to https://hub.docker.com/r/edoburu/pgbouncer/ eventually
> fix: Use legacy bitnami image

- .changeset/calm-planes-whisper.md
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/monitor.ex
- packages/sync-service/lib/electric/shapes/monitor/cleanup_task_supervisor.ex
- packages/sync-service/lib/electric/shapes/monitor/ref_counter.ex
- packages/sync-service/test/electric/replication/publication_manager_db_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shapes/monitor_test.exs
- packages/sync-service/test/support/component_setup.ex
Now that we have simplified the publication manager, it lends itself to easier cleanups without needing the full shape.
This is part of the work of simplifying, unifying, and speeding up cleanups.
By making `remove_shape` only require the shape handle it simplifies the required information for cleaning up shapes - we only need the handle.
> feat: Simplify `PublicationManager` to not require full shape for removal

- .changeset/rude-cars-beam.md
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/test/electric/replication/publication_manager_test.exs
Working on simplifying publication manager and noticed that we had incorrect behaviour for concurrent updates to the same shape handle - requests after the first one would immediately reply without waiting for the publication to actually update.
Unlikely we're seeing this in production as we generally don't call ops on the same shape handle multiple times, perhaps only removals which don't particularly matter (not as much as adding a shape that is important for keeping track of the replication stream)
> fix: Fix premature replies to concurrent publication updates for same shape handle

- integration-tests/tests/not-owner-of-the-table.lux
- packages/sync-service/config/runtime.exs
- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/config.ex
- packages/sync-service/lib/electric/connection/manager/supervisor.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/replication/schema_reconciler.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
Just getting rid of a no-op function invocation that pollutes the log with periodic log entries.
> Avoid invoking PublicationManager from SchemaReconciler when there are no diverged relations

- .changeset/khaki-zebras-lay.md
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/expiry_manager.ex
- packages/sync-service/lib/electric/shape_cache/shape_status.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/connection/manager_test.exs
- packages/sync-service/test/electric/shape_cache/expiry_manager_test.exs
- packages/sync-service/test/electric/shape_cache/shape_status_test.exs
- packages/sync-service/test/support/component_setup.ex
Listing least recently used shape handles becomes more efficient.
Counting shapes becomes an O(1) operation.
The the shape counting operation being cheap now, we can remove the complexity of spamming ExpiryManager's inbox and debouncing expiry checks.
If the tenant is in a steady state where it doesn't see any new shape creations, the cost of the periodic check is a call to `:ets.info(..., :size)`. On the other end of the spectrum, if the tenant is constantly churning through new shapes, sending a message for each shape to ExpiryManager is pure overhead.
The current debouncing implementation violates OTP's conventions by using Process.sleep() inside a GenServer callback. This results in the ExpiryManager process accumulating messages in its inbox which immediately stands out among other …
> Extract shape's last_read timestamp into a separate ETS table

- examples/bash/client.bash
Before this change, QUERY_STRING would be assigned an empty value even when I was passing ?table=items query in the URL.
> (examples/bash): Fix sed syntax in the bash client

- examples/linearlite/src/App.tsx
- examples/linearlite/src/pages/Issue/index.tsx
I was trying to debug something unrelated and found that the IssuePage was getting into a bad state if you browsed directly to it in an incognito tab without visiting the main page first.
The fix is reasonably trivial: delay all rendering queries until the initial db dump in synced, like how the rest of the example works.
I also fixed the "not found" rendering. I don't think that `useLiveQuery(liveIssue).rows[0]` can ever be `null`: it will always be `Item | undefined` (typescript types it as `Item` unless you turn on noUncheckedIndexedAccess).
* check that navigating to issue with no synced issue database works
* open http://localhost:5173/ and click on an issue to get issue url (it will look like http://localhost:5173/issue/d8af89e7-d1cf-4488-8b1b-424f120d0aa6)
* open a new incognito …
> fix linearlite loading if issue url is opened directly with no synced issue database

- .changeset/odd-kangaroos-hunt.md
- packages/sync-service/lib/electric/connection/manager/supervisor.ex
- packages/sync-service/lib/electric/postgres/configuration.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/replication/schema_reconciler.ex
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shape_cache/expiry_manager.ex
- packages/sync-service/lib/electric/shape_cache/shape_cleaner.ex
- packages/sync-service/lib/electric/shapes.ex
- packages/sync-service/lib/electric/shapes/dynamic_consumer_supervisor.ex
- packages/sync-service/lib/electric/shapes/shape_cleaner.ex
- packages/sync-service/test/electric/replication/publication_manager_db_test.exs
- packages/sync-service/test/electric/replication/publication_manager_manual_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/shape_cache/expiry_manager_test.exs
- packages/sync-service/test/electric/shape_cache_test.exs
- packages/sync-service/test/electric/shape_cleaner_test.exs
- packages/sync-service/test/support/component_setup.ex
We had spread out deletions a bit too much over the code base, so this is a first attempt at unifying that again.
The main purpose is to move shape cleaning operations away from `ShapeCache`, and especially `clean_all_shapes_for_relations` which was running in a blocking manner, and on a relation change could affect potentially thousands of shapes and block the critical path unnecessarily.
I've kept the actual cleanup in `Electric.Shapes.Monitor` to avoid making this PR too large, and also because it lives outside of the shape supervision and is thus able to clean up storage even during stack restarts due to connection issues, although I'm not entirely sure that's good as it makes it hard to reason about race conditions (especially with restoring backed up state).
- Now …
> feat: Use separate `ShapeCleaner` process for shape removals to avoid blocking `ShapeCache`

- .changeset/little-seals-try.md
- integration-tests/tests/not-owner-of-the-table.lux
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/lib/electric/replication/schema_reconciler.ex
- packages/sync-service/test/electric/replication/publication_manager_db_test.exs
- packages/sync-service/test/electric/replication/publication_manager_manual_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/shape_cache/expiry_manager_test.exs
- packages/sync-service/test/support/component_setup.ex
Fixes https://github.com/electric-sql/electric/issues/3167
We started seeing this error with an update made on 22nd of September, and until then one of the relevant changes included is this: https://github.com/electric-sql/electric/pull/3108
Since @alco has introduced periodic forced publication updates anyway, and upon reconciling the schema we also trigger dropping relevant shapes (which would remove them from the publication on cleanup), we no longer need to refresh the publication manually IMO - not much to be gained other than unnecessary dependencies between our processes.
It's still worth investigating why we're seeing these timeouts (but was harder to debug because we were missing sentry metadata, see https://github.com/electric-sql/electric/pull/3166) - but ultimately we should …
> fix: Remove `refresh_publiation` API form PubMan

- .changeset/small-insects-relate.md
- packages/sync-service/lib/electric/postgres/inspector.ex
- packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
- packages/sync-service/lib/electric/shapes/api/params.ex
- packages/sync-service/lib/electric/shapes/shape.ex
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/electric/shapes/api_test.exs
- packages/sync-service/test/support/stub_inspector.ex
Fixes https://github.com/electric-sql/electric/issues/3175
I'm not super familiar with Ecto so I tried to stay as close to the end of the pipeline as possible for this.
I don't love that the inspector returns an `:ok` tuple _or_ a `:table_not_found` _or_ and `:error` tuple - either the table not found error should be in the error tuple or `connection_not_available` should not be in one - but we can fix with a subsequent PR.
Happy to accept feedback or direct fixes on this PR, just want to fix this error asap.
> fix: Handle connection not available error from inspector correctly

- packages/sync-service/lib/electric/shape_cache/shape_status.ex
Small amendment to https://github.com/electric-sql/electric/pull/3174 (no changeset added)
I had argued that we should raise if we find the (a) `shape -> handle` lookup but not the (b) `handle -> metadata` lookup in `get_existing_shape` - but with the fix I did to the raise the only guarantee is that if we find (a) but not (b), we know that (a) has been cleaned up (which wasn't the case before).
Scenario calling `get_existing_shape`:
1. `shape -> handle` exists, so we go to the offset lookup (`handle -> metadata`)
2. Before offset lookup is made, `remove_shape` is called
3a. Only `shape -> handle` is cleaned up before the offset lookup, so offset is found and shape is returned (all good)
3b. Both `shape -> handle` and `handle -> metadata` are cleaned up before offset lookup, so offset …
> fix: Amend raise in existing shape race

- website/docs/integrations/react.md
The arrow function in the example is missing the return (`=>`)
> fix(docs): arrow function in effect example

- .changeset/empty-spiders-peel.md
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/lib/electric/replication/publication_manager.ex
- packages/sync-service/test/electric/db_connection_error_test.exs
- packages/sync-service/test/electric/replication/publication_manager_test.exs
- packages/sync-service/test/support/component_setup.ex
- make `econnrefused` a retryable error, server might be overloaded, temporarily not running, we should not be shutting down so eagerly
- parse server login failures by poolers and make them retryable (currently only [this pgbouncer error](https://electricsql-04.sentry.io/issues/66120509/?environment=production&project=4508410462404688&query=is%3Aunresolved&referrer=issue-stream) captures but we can add more if we see them
- Remove dependency injection from pubman since we were already referencing `Configuration` module for manual publication updates - we use Repatch in tests instead.
- Fix type
> fix: Minor publication and connection error changes

- .changeset/many-pears-smell.md
- packages/sync-service/lib/electric/connection/manager/supervisor.ex
- packages/sync-service/lib/electric/shapes/dynamic_consumer_supervisor.ex
- packages/sync-service/test/support/component_setup.ex
This adds a supervisor layer where a `PartitionSupervisor` now carries the `DynamicConsumerSupervisor.name(stack_id)` name and it starts a number of `DynamicConsumerSupervisor` processes to shard load between them. This change is transparent for the rest of the code that uses `DynamicConsumerSupervisor`'s public API.
I've done some measurements by repeatedly starting Electric, waiting for it to start all consumer processes for 50K shapes, then terminating it with the `SIGTERM` signal. I have done 5 attempts for the current implementation in `main` and for this PR, measuring both the startup and shutdown time.
|  | Attempt 1 | Attempt 2 | Attempt 3 | Attempt 4 | Attempt 5 |
| --- | --- | --- | --- | --- | --- |
| PartitionSupervisor startup | 28.8s | 12.5s | 11.8s | 11.0s | 11.8s |
| …
> Partition DynamicConsumerSupervisor to improve startup and shutdown times

- .changeset/seven-tomatoes-jam.md
- packages/elixir-client/lib/electric/client/message.ex
- packages/elixir-client/lib/electric/client/stream.ex
- packages/elixir-client/test/electric/client/message_test.exs
- packages/elixir-client/test/electric/client_test.exs
- packages/elixir-client/test/support/client_helpers.ex
Don't want to bump the electric version requirement here yet
> fix(elixir-client): Add support for new snapshot-end control to elixir client

- .changeset/calm-rockets-glow.md
- packages/sync-service/lib/electric/replication/supervisor.ex
- packages/sync-service/lib/electric/status_monitor.ex
- packages/sync-service/test/electric/connection/manager_test.exs
- packages/sync-service/test/electric/status_monitor_test.exs
- packages/sync-service/test/support/test_utils.ex
The last process in a supervisor's children list will be the first to be terminated in a restart. This canary process registers itself with the stack status and any shutdown of the Recplication.Supervisor, either due to a crash or a stack restart, will mark the stack as down immediately.
Seems to prevent a lot of errors on stack termination locally: only active requests raise due to the exit of the "crashed" process rather than every request after the process crash until the consumers have been terminated.
Fixes #3190
> fix(sync-service): Add stack canary process to detect shutdown

- packages/sync-service/lib/electric/application.ex
- packages/sync-service/lib/electric/shape_cache.ex
- packages/sync-service/lib/electric/shapes/consumer.ex
- packages/sync-service/lib/electric/shapes/consumer_supervisor.ex
- packages/sync-service/lib/electric/stack_supervisor.ex
- packages/sync-service/test/electric/shapes/consumer_test.exs
- packages/sync-service/test/support/component_setup.ex
As @msfstef pointed out, we didn't have a test for the consumer's hibernation.
This required properly wiring the hibernation timeout through the stack config.
I also took the opportunity to use GenServer's built-in timeout functionality.
> chore(sync-service): Add test that validates consumer remains hibernated

- .changeset/lazy-walls-look.md
- packages/typescript-client/src/client.ts
- packages/typescript-client/src/helpers.ts
- packages/typescript-client/src/index.ts
- packages/typescript-client/test/helpers.test.ts
- packages/typescript-client/test/stream.test.ts
- website/docs/api/clients/typescript.md
Adds an optional `shardSubdomain` shape option to auto-shard the url subdomain in development:
```ts
const url = isProd
? 'https://example.com' 
: 'http://localhost:3000'
const stream = new ShapeStream({
url,
shardSubdomain: 'localhost'
})
```
```ts
/**
* Enable subdomain sharding to bypass browser HTTP/1.1 connection limits.
* This is useful in local development and is enabled by default for localhost URLs.
*
* See https://electric-sql.com/docs/guides/troubleshooting#slow-shapes-mdash-why-are-my-shapes-slow-in-the-browser-in-local-development
*
* When sharded, each shape stream gets a unique subdomain (e.g., `a7f2c.localhost`),
* which bypasses the browser HTTP/1.1 connection limits. This avoids the need to serve
* the development server over HTTP/2 (and thus HTTPS) in development.
*
* …
```
> Add `shardSubdomain` shape option.

- .github/workflows/elixir_tests.yml
- packages/sync-service/dev/docker-compose.yml
- scripts/reset_wal.sh
Starting with Postgres 18, Docker images for it have a new default value for the `PGDATA` environment variable. ([details](https://github.com/docker-library/postgres/pull/1259)).
In this PR I'm removing assumptions about the data directory path so that both CI workflows and local development works with both pre- and post-18 versions of Postgres images.
> Test the sync-service with Postgres 18

- .changeset/polite-ghosts-switch.md
- packages/sync-service/lib/electric/db_connection_error.ex
- packages/sync-service/test/electric/db_connection_error_test.exs
Fixes [error 1](https://electricsql-04.sentry.io/issues/67931755/?alert_rule_id=130196&alert_timestamp=1759588783369&alert_type=email&environment=production&notification_uuid=cdf63771-ae86-45eb-8d73-8e2171406e67&project=4508410462404688&referrer=alert_email) and [error 2](https://electricsql-04.sentry.io/issues/67990265/?alert_rule_id=130196&alert_timestamp=1759598732763&alert_type=email&environment=production&notification_uuid=ee54f307-5539-4335-8bce-a1190244eca2&project=4508410462404688&referrer=alert_email)
> fix: Parse more connection closures as retryable errors
